// Writes every Cinematic SVG master and renders every PNG / generated file. Deterministic: no timestamps.
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import * as M from "./mark.mjs";
import { svgToPng, toOpaquePng, resize } from "../lib/render.mjs";
import { writeIco } from "../lib/img.mjs";
import { token } from "../lib/tokens.mjs";
import { fontPath } from "../lib/fonts.mjs";
import { textPath } from "../lib/text.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../..");
const { C } = M;
const r2 = (n) => Math.round(n * 100) / 100;
const outputs = [];
function put(rel, data, size) {
  const p = join(root, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, data);
  if (size) outputs.push({ path: rel, width: size[0], height: size[1] });
}
const svgFile = (name, s) => writeFileSync(join(here, name), s);

// ---------- og.svg ----------
async function ogSvg() {
  const k = 72 / 240; // cap height 72 px
  const L = await M.lockupSvg("color");
  const font = await fontPath("bodoni-italic");
  const line = textPath({ font, axes: { opsz: 40, wght: 500 }, text: "Every source. One shelf.", size: 40 });
  const lh = L.h * k, capH = line.bbox.y1 - line.bbox.y0, total = lh + 48 + capH;
  const y0 = (630 - total) / 2, x0 = 48;
  const stops = token("cinematic", "scrim.stops"), alphas = token("cinematic", "scrim.alpha");
  const grad = stops.map((s, i) => [1 - s, alphas[i]]).reverse()
    .map(([o, a]) => `<stop offset="${r2(o * 1e3) / 1e3}" stop-color="#000000" stop-opacity="${a}"/>`).join("");
  const mtx = "0.15341 0.51607 0.05210 0 0  0.14840 0.49924 0.05040 0 0  0.13673 0.45997 0.04643 0 0  0 0 0 1 0";
  return M.svg("0 0 1200 630",
    `<defs><filter id="duo" color-interpolation-filters="sRGB"><feColorMatrix type="matrix" values="${mtx}"/></filter>` +
    `<linearGradient id="gutter" gradientUnits="userSpaceOnUse" x1="518" y1="0" x2="682" y2="0">${grad}</linearGradient></defs>` +
    `<rect width="1200" height="630" fill="${C.page}"/>` +
    `<g transform="translate(${x0} ${r2(y0 - L.top * k)}) scale(${k})">${L.inner}</g>` +
    `<path transform="translate(${r2(x0 - line.bbox.x0)} ${r2(y0 + lh + 48 - line.bbox.y0)})" d="${line.d}" fill="${C.bone}"/>` +
    `<image x="518" y="48" width="720" height="1080" filter="url(#duo)" xlink:href="../demo/covers/01-salt-and-iron.webp"/>` +
    `<rect x="518" y="48" width="164" height="582" fill="url(#gutter)"/>`,
    ` width="1200" height="630"`);
}

async function writeMasters() {
  svgFile("monogram.svg", M.monogramSvg());
  svgFile("monogram-small.svg", M.monogramSmallSvg());
  svgFile("monogram-bone-on-black.svg", M.monogramBoneOnBlack());
  svgFile("monogram-black-on-bone.svg", M.monogramBlackOnBone());
  svgFile("monogram-mono.svg", M.monogramMonoSvg());
  svgFile("wordmark.svg", (await M.wordmarkSvg("color")).svg);
  svgFile("wordmark-mono.svg", (await M.wordmarkSvg("bone")).svg);
  svgFile("wordmark-black.svg", (await M.wordmarkSvg("black")).svg);
  svgFile("lockup-stacked.svg", (await M.lockupSvg("color")).svg);
  svgFile("lockup-stacked-mono.svg", (await M.lockupSvg("mono")).svg);
  svgFile("favicon.svg", M.faviconSvg());
  svgFile("ic_stat_mm.svg", M.icStatSvg());
  svgFile("icon.svg", M.iconSvg());
  svgFile("icon-dark.svg", M.iconDarkSvg());
  svgFile("icon-tinted.svg", M.iconTintedSvg());
  svgFile("icon-foreground.svg", M.iconForegroundSvg());
  svgFile("icon-monochrome.svg", M.iconMonochromeSvg());
  svgFile("maskable.svg", M.maskableSvg());
  svgFile("og.svg", await ogSvg());
}

// ---------- generated code ----------
function dartPath(d) {
  const t = d.match(/[MLQCZ]|-?\d+(?:\.\d+)?/g);
  let i = 0, out = "Path()", n = () => t[i++];
  while (i < t.length) {
    const c = n();
    if (c === "M") out += `..moveTo(${n()}, ${n()})`;
    else if (c === "L") out += `..lineTo(${n()}, ${n()})`;
    else if (c === "Q") out += `..quadraticBezierTo(${n()}, ${n()}, ${n()}, ${n()})`;
    else if (c === "C") out += `..cubicTo(${n()}, ${n()}, ${n()}, ${n()}, ${n()}, ${n()})`;
    else if (c === "Z") out += "..close()";
    else throw new Error("unsupported path command " + c);
  }
  return out;
}
function writeCode() {
  const hdr = "// GENERATED by brand/cinematic/export.mjs — do not edit\n";
  const media = (w, h, d) => `(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${d}) and (orientation: portrait)`;
  const splash = [[1290, 2796, 430, 932, 3], [1179, 2556, 393, 852, 3], [1170, 2532, 390, 844, 3], [2048, 2732, 1024, 1366, 2]];
  put("frontend/src/skins/brand.generated.ts", hdr +
    `export const SKIN_FAVICONS = { cinematic: "/favicon.svg", glass: "/favicon-glass.svg" } as const;\n` +
    `export const APPLE_TOUCH_ICON = "/icons/apple-touch-icon.png";\nexport const APPLE_STARTUP_IMAGES = [\n` +
    splash.map(([pw, ph, w, h, d]) => `  { url: "/splash/apple-splash-${pw}x${ph}.png", media: "${media(w, h, d)}" },\n`).join("") + `] as const;\n`);
  put("frontend/src/skins/cinematic/mark.generated.ts", hdr +
    `export const MM_MARK = { viewBox: "0 0 1024 1024", upright: "${M.MONO.upright}", italic: "${M.MONO.italic}", bone: "${C.bone}", spot: "${C.spot}" } as const;\n`);
  put("mobile/lib/skins/cinematic/brand_mark.g.dart", hdr.replace("//", "//") +
    `// ignore_for_file: type=lint\nimport 'dart:ui';\n\nabstract final class CineMarkPaths {\n  static const Size canvas = Size(1024, 1024);\n` +
    `  static Path upright() => ${dartPath(M.MONO.upright)};\n  static Path italic() => ${dartPath(M.MONO.italic)};\n` +
    `  static Path intersection() => Path.combine(PathOperation.intersect, upright(), italic());\n}\n`);
}

async function main() {
  await writeMasters();
  const S = (n) => readFileSync(join(here, n), "utf8");
  const E = "brand/cinematic/export";
  const icon = await toOpaquePng(svgToPng(S("icon.svg"), { width: 1024 }));
  put(`${E}/icon-ios-1024.png`, icon, [1024, 1024]);
  put(`${E}/icon-ios-dark-1024.png`, svgToPng(S("icon-dark.svg"), { width: 1024 }), [1024, 1024]);
  put(`${E}/icon-ios-tinted-1024.png`, await toOpaquePng(svgToPng(S("icon-tinted.svg"), { width: 1024 })), [1024, 1024]);
  put(`${E}/android-foreground-1024.png`, svgToPng(S("icon-foreground.svg"), { width: 1024 }), [1024, 1024]);
  put(`${E}/android-monochrome-1024.png`, svgToPng(S("icon-monochrome.svg"), { width: 1024 }), [1024, 1024]);
  put("brand/splash/transparent-288.png",
    await sharp({ create: { width: 288, height: 288, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } }).png().toBuffer(), [288, 288]);
  for (const [d, px] of [["mdpi", 24], ["hdpi", 36], ["xhdpi", 48], ["xxhdpi", 72], ["xxxhdpi", 96]])
    put(`mobile/android/app/src/main/res/drawable-${d}/ic_stat_mm.png`, svgToPng(S("ic_stat_mm.svg"), { width: px }), [px, px]);
  put("frontend/public/favicon.svg", S("favicon.svg").replace(/>\s+</g, "><"));
  put("frontend/src/app/favicon.ico", writeIco([16, 32].map((w) => svgToPng(S("favicon.svg"), { width: w }))));
  outputs.push({ path: "frontend/src/app/favicon.ico", width: 32, height: 32, entries: [16, 32] });
  for (const [f, px] of [["icon-192", 192], ["icon-512", 512], ["apple-touch-icon", 180]])
    put(`frontend/public/icons/${f}.png`, await resize(icon, px), [px, px]);
  put("frontend/public/icons/maskable-512.png", await toOpaquePng(svgToPng(S("maskable.svg"), { width: 512 })), [512, 512]);
  for (const [w, h] of [[1290, 2796], [1179, 2556], [1170, 2532], [2048, 2732]])
    put(`frontend/public/splash/apple-splash-${w}x${h}.png`,
      await sharp({ create: { width: w, height: h, channels: 3, background: C.page } }).png({ compressionLevel: 9 }).toBuffer(), [w, h]);
  const cover = await sharp(join(here, "../demo/covers/01-salt-and-iron.webp")).png().toBuffer();
  const og = S("og.svg").replace("../demo/covers/01-salt-and-iron.webp", `data:image/png;base64,${cover.toString("base64")}`);
  put("frontend/public/og.png", await toOpaquePng(svgToPng(og, { width: 1200 })), [1200, 630]);
  put("mobile/docs/screenshots/app-icon.png", icon, [1024, 1024]);
  writeCode();
  outputs.sort((a, b) => (a.path < b.path ? -1 : 1));
  put(`${E}/manifest.json`, JSON.stringify({ outputs }, null, 1) + "\n");
  console.log(`exported ${outputs.length} files`);
}
await main();
