// Phosphor glyphs the Settings screens need beyond the shared sets (codepoints from brand/phosphor/codepoints.json).
import 'package:flutter/widgets.dart';
import 'package:manhwamaniacs/skins/glass/primitives/glyphs.dart';

abstract final class SettingsGlyphs {
  static const paintBrush = Glyph(regular: IconData(0xe6f0, fontFamily: 'PhosphorRegular'), fill: IconData(0xe6f0, fontFamily: 'PhosphorFill'), bold: IconData(0xe6f0, fontFamily: 'PhosphorBold'), light: IconData(0xe6f0, fontFamily: 'PhosphorLight'));
  static const bookOpen = Glyph(regular: IconData(0xe0e6, fontFamily: 'PhosphorRegular'), fill: IconData(0xe0e6, fontFamily: 'PhosphorFill'), bold: IconData(0xe0e6, fontFamily: 'PhosphorBold'), light: IconData(0xe0e6, fontFamily: 'PhosphorLight'));
  static const shieldWarning = Glyph(regular: IconData(0xe412, fontFamily: 'PhosphorRegular'), fill: IconData(0xe412, fontFamily: 'PhosphorFill'), bold: IconData(0xe412, fontFamily: 'PhosphorBold'), light: IconData(0xe412, fontFamily: 'PhosphorLight'));
  static const usersThree = Glyph(regular: IconData(0xe68e, fontFamily: 'PhosphorRegular'), fill: IconData(0xe68e, fontFamily: 'PhosphorFill'), bold: IconData(0xe68e, fontFamily: 'PhosphorBold'), light: IconData(0xe68e, fontFamily: 'PhosphorLight'));
  static const sparkle = Glyph(regular: IconData(0xe6a2, fontFamily: 'PhosphorRegular'), fill: IconData(0xe6a2, fontFamily: 'PhosphorFill'), bold: IconData(0xe6a2, fontFamily: 'PhosphorBold'), light: IconData(0xe6a2, fontFamily: 'PhosphorLight'));
  static const speakerHigh = Glyph(regular: IconData(0xe44a, fontFamily: 'PhosphorRegular'), fill: IconData(0xe44a, fontFamily: 'PhosphorFill'), bold: IconData(0xe44a, fontFamily: 'PhosphorBold'), light: IconData(0xe44a, fontFamily: 'PhosphorLight'));
  static const bellSimple = Glyph(regular: IconData(0xe0d0, fontFamily: 'PhosphorRegular'), fill: IconData(0xe0d0, fontFamily: 'PhosphorFill'), bold: IconData(0xe0d0, fontFamily: 'PhosphorBold'), light: IconData(0xe0d0, fontFamily: 'PhosphorLight'));
  static const lockSimple = Glyph(regular: IconData(0xe308, fontFamily: 'PhosphorRegular'), fill: IconData(0xe308, fontFamily: 'PhosphorFill'), bold: IconData(0xe308, fontFamily: 'PhosphorBold'), light: IconData(0xe308, fontFamily: 'PhosphorLight'));
  static const hardDrives = Glyph(regular: IconData(0xe2a0, fontFamily: 'PhosphorRegular'), fill: IconData(0xe2a0, fontFamily: 'PhosphorFill'), bold: IconData(0xe2a0, fontFamily: 'PhosphorBold'), light: IconData(0xe2a0, fontFamily: 'PhosphorLight'));
  static const cloudArrowUp = Glyph(regular: IconData(0xe1ae, fontFamily: 'PhosphorRegular'), fill: IconData(0xe1ae, fontFamily: 'PhosphorFill'), bold: IconData(0xe1ae, fontFamily: 'PhosphorBold'), light: IconData(0xe1ae, fontFamily: 'PhosphorLight'));
  static const plugsConnected = Glyph(regular: IconData(0xeb5a, fontFamily: 'PhosphorRegular'), fill: IconData(0xeb5a, fontFamily: 'PhosphorFill'), bold: IconData(0xeb5a, fontFamily: 'PhosphorBold'), light: IconData(0xeb5a, fontFamily: 'PhosphorLight'));
  static const pulse = Glyph(regular: IconData(0xe000, fontFamily: 'PhosphorRegular'), fill: IconData(0xe000, fontFamily: 'PhosphorFill'), bold: IconData(0xe000, fontFamily: 'PhosphorBold'), light: IconData(0xe000, fontFamily: 'PhosphorLight'));
  static const keyboard = Glyph(regular: IconData(0xe2d8, fontFamily: 'PhosphorRegular'), fill: IconData(0xe2d8, fontFamily: 'PhosphorFill'), bold: IconData(0xe2d8, fontFamily: 'PhosphorBold'), light: IconData(0xe2d8, fontFamily: 'PhosphorLight'));
  static const info = Glyph(regular: IconData(0xe2ce, fontFamily: 'PhosphorRegular'), fill: IconData(0xe2ce, fontFamily: 'PhosphorFill'), bold: IconData(0xe2ce, fontFamily: 'PhosphorBold'), light: IconData(0xe2ce, fontFamily: 'PhosphorLight'));
  static const magnifyingGlass = Glyph(regular: IconData(0xe30c, fontFamily: 'PhosphorRegular'), fill: IconData(0xe30c, fontFamily: 'PhosphorFill'), bold: IconData(0xe30c, fontFamily: 'PhosphorBold'), light: IconData(0xe30c, fontFamily: 'PhosphorLight'));
  static const gearSix = Glyph(regular: IconData(0xe272, fontFamily: 'PhosphorRegular'), fill: IconData(0xe272, fontFamily: 'PhosphorFill'), bold: IconData(0xe272, fontFamily: 'PhosphorBold'), light: IconData(0xe272, fontFamily: 'PhosphorLight'));
  static const speakerSlash = Glyph(regular: IconData(0xe45a, fontFamily: 'PhosphorRegular'), fill: IconData(0xe45a, fontFamily: 'PhosphorFill'), bold: IconData(0xe45a, fontFamily: 'PhosphorBold'), light: IconData(0xe45a, fontFamily: 'PhosphorLight'));
  static const cloudRain = Glyph(regular: IconData(0xe1b4, fontFamily: 'PhosphorRegular'), fill: IconData(0xe1b4, fontFamily: 'PhosphorFill'), bold: IconData(0xe1b4, fontFamily: 'PhosphorBold'), light: IconData(0xe1b4, fontFamily: 'PhosphorLight'));
  static const wind = Glyph(regular: IconData(0xe5d2, fontFamily: 'PhosphorRegular'), fill: IconData(0xe5d2, fontFamily: 'PhosphorFill'), bold: IconData(0xe5d2, fontFamily: 'PhosphorBold'), light: IconData(0xe5d2, fontFamily: 'PhosphorLight'));
  static const waves = Glyph(regular: IconData(0xe6de, fontFamily: 'PhosphorRegular'), fill: IconData(0xe6de, fontFamily: 'PhosphorFill'), bold: IconData(0xe6de, fontFamily: 'PhosphorBold'), light: IconData(0xe6de, fontFamily: 'PhosphorLight'));
  static const campfire = Glyph(regular: IconData(0xe9d8, fontFamily: 'PhosphorRegular'), fill: IconData(0xe9d8, fontFamily: 'PhosphorFill'), bold: IconData(0xe9d8, fontFamily: 'PhosphorBold'), light: IconData(0xe9d8, fontFamily: 'PhosphorLight'));
  static const dropHalf = Glyph(regular: IconData(0xe566, fontFamily: 'PhosphorRegular'), fill: IconData(0xe566, fontFamily: 'PhosphorFill'), bold: IconData(0xe566, fontFamily: 'PhosphorBold'), light: IconData(0xe566, fontFamily: 'PhosphorLight'));
  static const moonStars = Glyph(regular: IconData(0xe58e, fontFamily: 'PhosphorRegular'), fill: IconData(0xe58e, fontFamily: 'PhosphorFill'), bold: IconData(0xe58e, fontFamily: 'PhosphorBold'), light: IconData(0xe58e, fontFamily: 'PhosphorLight'));
}
