#!/usr/bin/env node
// Glyph build (shared/02 item 5). Per skin: traces the SVG masters into flat paths
// (oslllo-svg-fixer 6.0.1), keeps brand/<skin>/glyphs/codepoints.json append-only, builds the
// CineGlyphs / GlassGlyphs TTF (fantasticon 4.1.0) and writes the Dart and React outputs.
// Stdlib only; the two tools run pinned through npx. Deterministic: same masters, same bytes.
//   node brand/build-glyphs.mjs           build everything
//   node brand/build-glyphs.mjs --proof   also write docs/redesign/proof/shared-02/
// Temp files go under $MM_SCRATCH (the session scratchpad) or the OS temp dir.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const rel = (...p) => path.join(ROOT, ...p);
const icons = JSON.parse(fs.readFileSync(rel('design/icons.json'), 'utf8'));
const phosphor = JSON.parse(fs.readFileSync(rel('brand/phosphor/codepoints.json'), 'utf8'));
const PROOF = process.argv.includes('--proof');
const FIRST_CODEPOINT = 0xe900;

const SKINS = {
  cinematic: { prefix: 'Cine', font: 'CineGlyphs', defaultWeight: 'light', defaultSize: 24 },
  glass: { prefix: 'Glass', font: 'GlassGlyphs', defaultWeight: 'regular', defaultSize: 22 },
};
const PH_FAMILY = { regular: 'PhosphorRegular', thin: 'PhosphorThin', light: 'PhosphorLight', bold: 'PhosphorBold', fill: 'PhosphorFill', duotone: 'PhosphorDuotone' };

const header = (skin, c = '//') => `${c} GENERATED by brand/build-glyphs.mjs from design/icons.json and brand/${skin}/glyphs — do not edit.\n`;
const words = (s) => s.split('-');
const camel = (s) => words(s).map((w, i) => (i ? w[0].toUpperCase() + w.slice(1) : w)).join('');
const pascal = (s) => words(s).map((w) => w[0].toUpperCase() + w.slice(1)).join('');
const hex = (n) => `0x${n.toString(16).toUpperCase()}`;
const cap = (s) => s[0].toUpperCase() + s.slice(1);
// Dart enums cannot declare a value named `index` or `values` (Enum members)
const DART_RESERVED = new Set(['index', 'values', 'hashCode', 'runtimeType', 'name']);
const dartRole = (r) => (DART_RESERVED.has(camel(r)) ? `${camel(r)}Role` : camel(r));
// a glyph family is the component a glyph belongs to: strata-1 … strata-4 are one `Strata`
const family = (name) => name.replace(/^(strata)-\d$/, '$1');
const write = (file, text) => {
  fs.mkdirSync(path.dirname(rel(file)), { recursive: true });
  fs.writeFileSync(rel(file), text);
};

// ---------- 1. trace ----------
const tmpRoot = fs.mkdtempSync(path.join(process.env.MM_SCRATCH || os.tmpdir(), 'mm-glyphs-'));
function trace(skin) {
  const cfg = icons.skins[skin];
  const src = path.join(tmpRoot, skin, 'in');
  const out = path.join(tmpRoot, skin, 'traced');
  fs.mkdirSync(src, { recursive: true });
  fs.mkdirSync(out, { recursive: true });
  for (const name of icons.glyphs[skin]) {
    for (const weight of cfg.glyphWeights) {
      const master = fs.readFileSync(rel('brand', skin, 'glyphs', `${name}-${weight}.svg`), 'utf8');
      if (weight !== 'duotone') {
        fs.writeFileSync(path.join(src, `${name}-${weight}.svg`), master);
        continue;
      }
      // duotone: primary and secondary become two glyphs; the secondary loses its opacity
      const lines = master.split('\n');
      const sec = lines.findIndex((l) => l.startsWith('<g id="secondary"'));
      const pri = lines.findIndex((l) => l.startsWith('<g id="primary"'));
      if (sec < 0 || pri < 0) throw new Error(`${skin}/${name}-duotone.svg: missing primary or secondary group`);
      const without = (i) => lines.filter((_, j) => j !== i).join('\n');
      fs.writeFileSync(path.join(src, `${name}-duotone.svg`), without(sec));
      fs.writeFileSync(path.join(src, `${name}-duotone-secondary.svg`), without(pri).replace(' opacity="0.2"', ''));
    }
  }
  execFileSync('npx', ['--yes', 'oslllo-svg-fixer@6.0.1', '-s', src, '-d', out, '--sp', 'false'], { stdio: ['ignore', 'ignore', 'inherit'] });
  const paths = {};
  for (const f of fs.readdirSync(out).filter((f) => f.endsWith('.svg')).sort()) {
    const svg = fs.readFileSync(path.join(out, f), 'utf8');
    const ds = [...svg.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]);
    if (ds.length === 0) throw new Error(`${skin}/${f}: tracing produced no path`);
    const d = ds
      .join(' ')
      .replace(/-?\d*\.?\d+(?:e-?\d+)?/g, (n) => String(Math.round(Number(n) * 10) / 10))
      .replace(/\s*,\s*/g, ',')
      .replace(/\s+/g, ' ')
      .trim();
    const nums = (d.match(/-?\d*\.?\d+/g) || []).map(Number);
    const lo = Math.min(...nums);
    const hi = Math.max(...nums);
    // 16-unit safe inset, 1.5 units of tracing tolerance
    if (lo < 14.5 || hi > 241.5) throw new Error(`${skin}/${f}: traced outline spans ${lo}–${hi}, outside the 16–240 safe inset`);
    const id = f.replace(/\.svg$/, '');
    paths[id] = d;
    fs.writeFileSync(path.join(out, f), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" width="256" height="256"><path d="${d}"/></svg>\n`);
  }
  return { paths, tracedDir: out };
}

// ---------- 2. codepoints (append-only) ----------
function codepoints(skin, ids) {
  const file = rel('brand', skin, 'glyphs', 'codepoints.json');
  const cps = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : {};
  const used = new Set(Object.values(cps));
  let next = FIRST_CODEPOINT;
  for (const id of [...ids].sort()) {
    if (id in cps) continue;
    while (used.has(next)) next++;
    cps[id] = next;
    used.add(next);
  }
  const sorted = Object.fromEntries(Object.keys(cps).sort().map((k) => [k, cps[k]]));
  fs.writeFileSync(file, JSON.stringify(sorted, null, 2) + '\n');
  return sorted;
}

// ---------- 3. font ----------
function font(skin, tracedDir, cps) {
  const name = SKINS[skin].font;
  const outDir = path.join(tmpRoot, skin, 'font');
  fs.mkdirSync(outDir, { recursive: true });
  const config = {
    inputDir: tracedDir,
    outputDir: outDir,
    name,
    fontTypes: ['ttf'],
    assetTypes: ['json'],
    fontHeight: 1000,
    descent: 0,
    normalize: false,
    codepoints: cps,
    // svg2ttf stamps the build time into `head`; a fixed stamp keeps the TTF byte-identical between runs
    formatOptions: { ttf: { ts: 0 } },
  };
  const cfgFile = path.join(tmpRoot, skin, 'fantasticon.json');
  fs.writeFileSync(cfgFile, JSON.stringify(config, null, 2));
  execFileSync('npx', ['--yes', 'fantasticon@4.1.0', '-c', cfgFile, '--silent'], { stdio: ['ignore', 'ignore', 'inherit'] });
  fs.copyFileSync(path.join(outDir, `${name}.ttf`), rel('mobile/assets/fonts', `${name}.ttf`));
}

// ---------- roles ----------
function resolveRoles(skin) {
  const out = [];
  for (const [role, v] of Object.entries(icons.roles)) {
    const value = v[skin];
    if (value == null) continue;
    if (value.startsWith('glyph:')) {
      const g = value.slice(6);
      // back-depth names the strata family: the runtime swaps strata-1 … strata-4 by depth
      const glyph = icons.glyphs[skin].includes(g) ? g : `${g}-1`;
      if (!icons.glyphs[skin].includes(glyph)) throw new Error(`${skin} role ${role}: unknown glyph ${g}`);
      out.push({ role, kind: 'glyph', name: glyph, family: family(glyph) });
    } else {
      if (!phosphor[value]) throw new Error(`${skin} role ${role}: ${value} is not in brand/phosphor/codepoints.json`);
      out.push({ role, kind: 'phosphor', name: value });
    }
  }
  return out;
}

// ---------- 4–6. Dart ----------
function dart(skin, cps, roles) {
  const { prefix, font: fam } = SKINS[skin];
  const cfg = icons.skins[skin];
  const dir = `mobile/lib/skins/${skin}/icons`;
  const glyphClass = `${prefix}Glyphs`;
  const glyphFile = skin === 'cinematic' ? 'cine_glyphs.g.dart' : 'glass_glyphs.g.dart';

  let g = header(skin) + `import 'package:flutter/widgets.dart';\n\n/// Custom glyphs of the ${fam} font (mobile/assets/fonts/${fam}.ttf).\nabstract final class ${glyphClass} {\n`;
  for (const [id, cp] of Object.entries(cps)) g += `  static const IconData ${camel(id)} = IconData(${hex(cp)}, fontFamily: '${fam}');\n`;
  write(`${dir}/${glyphFile}`, g + '}\n');

  const names = [...new Set(roles.filter((r) => r.kind === 'phosphor').map((r) => r.name))].sort();
  let p = header(skin) + `import 'package:flutter/widgets.dart';\n`;
  for (const w of cfg.phosphorWeights) {
    p += `\n/// Phosphor 2.1 ${w} (family ${PH_FAMILY[w]}), every name the ${skin} roles use.\nabstract final class ${PH_FAMILY[w]} {\n`;
    for (const n of names) {
      const v = phosphor[n][w];
      if (w === 'duotone') {
        p += `  static const IconData ${camel(n)} = IconData(${hex(parseInt(v[0], 16))}, fontFamily: '${PH_FAMILY[w]}');\n`;
        if (v[1]) p += `  static const IconData ${camel(n)}Secondary = IconData(${hex(parseInt(v[1], 16))}, fontFamily: '${PH_FAMILY[w]}');\n`;
      } else {
        p += `  static const IconData ${camel(n)} = IconData(${hex(parseInt(v, 16))}, fontFamily: '${PH_FAMILY[w]}');\n`;
      }
    }
    p += '}\n';
  }
  write(`${dir}/phosphor.g.dart`, p);

  const roleEnum = `${prefix}IconRole`;
  const weightEnum = `${prefix}IconWeight`;
  const mapName = `${skin === 'cinematic' ? 'cine' : 'glass'}Icons`;
  const glyphWeight = (w) => (cfg.glyphWeights.includes(w) ? w : cfg.glyphFallback[w]);
  const ref = (r, w) =>
    r.kind === 'glyph' ? `${glyphClass}.${camel(`${r.name}-${glyphWeight(w)}`)}` : `${PH_FAMILY[w]}.${camel(r.name)}`;
  let t = header(skin) + `import 'package:flutter/widgets.dart';\n\nimport '${glyphFile}';\nimport 'phosphor.g.dart';\n\n`;
  t += `/// Semantic icon roles of design/icons.json that the ${skin} skin draws.`;
  if (roles.some((r) => DART_RESERVED.has(camel(r.role)))) t += ` A role named like an Enum member gets a \`Role\` suffix (index → indexRole).`;
  t += `\nenum ${roleEnum} { ${roles.map((r) => dartRole(r.role)).join(', ')} }\n\n`;
  t += `/// Weights the ${skin} skin uses${skin === 'glass' ? '; glyph roles map light, bold and thin through glyphFallback' : ''}.\nenum ${weightEnum} { ${cfg.phosphorWeights.join(', ')} }\n\n`;
  if (skin === 'glass') t += `/// back-depth maps to strata-1; the runtime swaps GlassGlyphs.strata1Regular … strata4Regular by depth (glass §7.37).\n`;
  t += `const Map<${roleEnum}, Map<${weightEnum}, IconData>> ${mapName} = {\n`;
  for (const r of roles) {
    t += `  ${roleEnum}.${dartRole(r.role)}: {\n`;
    for (const w of cfg.phosphorWeights) t += `    ${weightEnum}.${w}: ${ref(r, w)},\n`;
    t += '  },\n';
  }
  t += '};\n';
  if (skin === 'glass') {
    t += `\n/// The 0.2-opacity area drawn under the duotone glyph (glass §2.7, duotoneSecondaryOpacity).\nconst Map<${roleEnum}, IconData> glassDuotoneSecondary = {\n`;
    for (const r of roles) {
      if (r.kind === 'glyph') t += `  ${roleEnum}.${dartRole(r.role)}: ${glyphClass}.${camel(`${r.name}-duotone-secondary`)},\n`;
      else if (phosphor[r.name].duotone[1]) t += `  ${roleEnum}.${dartRole(r.role)}: PhosphorDuotone.${camel(r.name)}Secondary,\n`;
    }
    t += '};\n';
  }
  write(`${dir}/icon_roles.g.dart`, t);
}

// ---------- 7. React glyph components ----------
function react(skin, paths) {
  const { defaultWeight, defaultSize } = SKINS[skin];
  const cfg = icons.skins[skin];
  const weights = cfg.glyphWeights;
  const fams = [...new Set(icons.glyphs[skin].map(family))];
  let s = header(skin) + `import type { SVGProps } from "react";\n\n`;
  s += `export type GlyphWeight = ${weights.map((w) => JSON.stringify(w)).join(' | ')};\n\n`;
  s += `export type GlyphProps = Omit<SVGProps<SVGSVGElement>, "color"> & {\n  /** Default "${defaultWeight}". */\n  weight?: GlyphWeight;\n  /** Default ${defaultSize}. */\n  size?: number | string;\n  /** Default "currentColor". */\n  color?: string;\n  /** Accessible name; without it the glyph is decorative (aria-hidden). */\n  title?: string;\n};\n\n`;
  s += `type Outline = { d: string; secondary?: string };\n\n`;
  s += `const PATHS: Record<string, Record<GlyphWeight, Outline>> = {\n`;
  for (const name of icons.glyphs[skin]) {
    s += `  ${JSON.stringify(name)}: {\n`;
    for (const w of weights) {
      const sec = paths[`${name}-${w}-secondary`];
      s += `    ${w}: { d: ${JSON.stringify(paths[`${name}-${w}`])}${sec ? `, secondary: ${JSON.stringify(sec)}` : ''} },\n`;
    }
    s += '  },\n';
  }
  s += '};\n\n';
  s += `function Glyph({ name, weight = ${JSON.stringify(defaultWeight)}, size = ${defaultSize}, color = "currentColor", title, ...rest }: GlyphProps & { name: string }) {
  const outline = PATHS[name][weight];
  const a11y = title ? { role: "img" } : { "aria-hidden": true };
  return (
    <svg viewBox="0 0 256 256" width={size} height={size} fill={color} focusable="false" {...a11y} {...rest}>
      {title ? <title>{title}</title> : null}
      {outline.secondary ? <path d={outline.secondary} opacity={${cfg.duotoneSecondaryOpacity ?? 0.2}} /> : null}
      <path d={outline.d} />
    </svg>
  );
}\n\n`;
  for (const f of fams) {
    if (f === 'strata') {
      s += `/** strata-1 … strata-4: the number of lit bars, counted from the bottom. */\nexport function Strata({ level, ...props }: GlyphProps & { level: 1 | 2 | 3 | 4 }) {\n  return <Glyph name={\`strata-\${level}\`} {...props} />;\n}\n\n`;
    } else {
      s += `export function ${pascal(f)}(props: GlyphProps) {\n  return <Glyph name=${JSON.stringify(f)} {...props} />;\n}\n\n`;
    }
  }
  s += `export const GLYPHS = {\n${fams.map((f) => `  ${JSON.stringify(f)}: ${pascal(f)},`).join('\n')}\n} as const;\n\nexport type GlyphName = keyof typeof GLYPHS;\n`;
  write(`frontend/src/skins/${skin}/icons/glyphs.generated.tsx`, s);
}

// ---------- 8. web role tables ----------
function webRoles(skin, roles) {
  const cfg = icons.skins[skin];
  let s = header(skin) + `// Strings only: web/01 imports the named components from "@phosphor-icons/react/ssr".\n\n`;
  s += `export const ICON_ROLES = {\n`;
  for (const r of roles) {
    const key = /^[a-z]+$/.test(r.role) ? r.role : JSON.stringify(r.role);
    s += r.kind === 'glyph'
      ? `  ${key}: { kind: "glyph", name: ${JSON.stringify(r.family)} },\n`
      : `  ${key}: { kind: "phosphor", name: ${JSON.stringify(r.name)}, component: ${JSON.stringify(`${pascal(r.name)}Icon`)} },\n`;
  }
  s += `} as const;\n\nexport type IconRole = keyof typeof ICON_ROLES;\n\n`;
  s += `export const ICON_RULES = ${JSON.stringify(cfg, null, 2).replace(/"([a-zA-Z]+)":/g, '$1:')} as const;\n`;
  write(`frontend/src/skins/${skin}/icons/roles.generated.ts`, s);
}

// ---------- 9. Dart test ----------
function dartTest(all) {
  const g = all.glass;
  let s = header('{cinematic,glass}') + `import 'package:flutter_test/flutter_test.dart';
import 'package:manhwamaniacs/skins/cinematic/icons/cine_glyphs.g.dart';
import 'package:manhwamaniacs/skins/cinematic/icons/icon_roles.g.dart';
import 'package:manhwamaniacs/skins/glass/icons/glass_glyphs.g.dart';
import 'package:manhwamaniacs/skins/glass/icons/icon_roles.g.dart';
import 'package:manhwamaniacs/skins/glass/icons/phosphor.g.dart' as glass;

void main() {
  test('every Cinematic role has all three weights', () {
    expect(cineIcons.keys, unorderedEquals(CineIconRole.values));
    for (final role in CineIconRole.values) {
      expect(cineIcons[role]!.keys, unorderedEquals(CineIconWeight.values), reason: role.name);
    }
  });

  test('every Glass role has all six weights', () {
    expect(glassIcons.keys, unorderedEquals(GlassIconRole.values));
    for (final role in GlassIconRole.values) {
      expect(glassIcons[role]!.keys, unorderedEquals(GlassIconWeight.values), reason: role.name);
    }
  });

  test('font families', () {
    expect(CineGlyphs.mmMarkFill.fontFamily, 'CineGlyphs');
    expect(GlassGlyphs.mmMarkFill.fontFamily, 'GlassGlyphs');
    expect(glass.PhosphorRegular.caretLeft.fontFamily, 'PhosphorRegular');
    expect(glass.PhosphorDuotone.houseSimpleSecondary.fontFamily, 'PhosphorDuotone');
  });

  test('every Glass role whose duotone exists has a secondary', () {
    expect(glassDuotoneSecondary.keys, unorderedEquals(<GlassIconRole>[
${g.roles.filter((r) => r.kind === 'glyph' || phosphor[r.name].duotone[1]).map((r) => `      GlassIconRole.${dartRole(r.role)},`).join('\n')}
    ]));
  });
}
`;
  write('mobile/test/skins/generated_icons_test.dart', s);
}

// ---------- 7. proof ----------
function proof(all) {
  const esc = (t) => String(t).replace(/&/g, '&amp;').replace(/</g, '&lt;');
  const md = ['# Shared 02: icon roles', '', 'GENERATED by brand/build-glyphs.mjs --proof from design/icons.json — do not edit.', '', '| role | cinematic | glass |', '|---|---|---|'];
  for (const [role, v] of Object.entries(icons.roles)) md.push(`| \`${role}\` | ${v.cinematic ? `\`${v.cinematic}\`` : '—'} | ${v.glass ? `\`${v.glass}\`` : '—'} |`);
  write('docs/redesign/proof/shared-02/roles.md', md.join('\n') + '\n');

  for (const skin of Object.keys(SKINS)) {
    const { paths, cps, roles } = all[skin];
    const cfg = icons.skins[skin];
    const ink = skin === 'cinematic' ? '#F3F0E8' : '#FFFFFF';
    const bg = skin === 'cinematic' ? '#000000' : '#05060A';
    const muted = '#8A877F';
    const W = 1440;
    const cellW = 320;
    const rowH = 300;
    const glyphs = icons.glyphs[skin];
    const top = 80;
    const H = Math.max(top + glyphs.length * rowH, top + 56 + roles.length * 22) + 40;
    const shape = (id, x, y, size) => {
      const sec = paths[`${id}-secondary`];
      const t = `transform="translate(${x} ${y}) scale(${size / 256})"`;
      return (sec ? `<path ${t} d="${sec}" fill="${ink}" opacity="0.2"/>` : '') + `<path ${t} d="${paths[id]}" fill="${ink}"/>`;
    };
    let body = `<text x="24" y="44" font-size="26" fill="${ink}">${SKINS[skin].font}: ${glyphs.length} glyphs × ${cfg.glyphWeights.join(' / ')} at 256, 48, 24, 16 px</text>`;
    glyphs.forEach((name, row) => {
      const y = top + row * rowH;
      cfg.glyphWeights.forEach((w, col) => {
        const id = `${name}-${w}`;
        const x = 24 + col * cellW;
        body += `<rect x="${x}" y="${y}" width="256" height="256" fill="none" stroke="#2B2A27"/>`;
        body += shape(id, x, y, 256) + shape(id, x + 264, y, 48) + shape(id, x + 264, y + 64, 24) + shape(id, x + 264, y + 100, 16);
        const cp = hex(cps[id]) + (cps[`${id}-secondary`] ? ` + ${hex(cps[`${id}-secondary`])}` : '');
        body += `<text x="${x}" y="${y + 276}" font-size="13" fill="${muted}">${esc(id)} ${cp}</text>`;
      });
    });
    const tx = 24 + cfg.glyphWeights.length * cellW + 16;
    const ab = (w) => w[0].toUpperCase();
    const r = cfg.rules;
    const phRule = skin === 'cinematic'
      ? `${ab(r.default)} · ${ab(r.small)} ≤ ${r.smallAtOrBelow} · ${ab(r.active)} active`
      : `${ab(r.default)} · ${ab(r.active)} active · ${ab(r.pressed)} pressed`;
    const ruleOf = (x) => (x.kind === 'glyph' ? `glyph ${cfg.glyphWeights.map(ab).join('/')}` : phRule);
    const legend = cfg.phosphorWeights.map((w) => `${ab(w)}=${w}`).join(' ');
    body += `<text x="${tx}" y="${top + 10}" font-size="14" fill="${ink}">role · icon · weight rule (${roles.length} roles)</text>`;
    body += `<text x="${tx}" y="${top + 30}" font-size="11" fill="${muted}">${esc(legend)}</text>`;
    roles.forEach((x, i) => {
      body += `<text x="${tx}" y="${top + 56 + i * 22}" font-size="11" fill="${muted}">${esc(x.role)} · <tspan fill="${ink}">${esc(x.kind === 'glyph' ? `glyph:${x.name}` : x.name)}</tspan> · ${esc(ruleOf(x))}</text>`;
    });
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" font-family="IBM Plex Mono, ui-monospace, monospace">\n<rect width="${W}" height="${H}" fill="${bg}"/>\n${body}\n</svg>\n`;
    write(`docs/redesign/proof/shared-02/glyphs-${skin}.svg`, svg);
  }
}

// ---------- run ----------
const all = {};
try {
  for (const skin of Object.keys(SKINS)) {
    const { paths, tracedDir } = trace(skin);
    const cps = codepoints(skin, Object.keys(paths));
    const missing = Object.keys(cps).filter((id) => !paths[id]);
    if (missing.length) throw new Error(`${skin}: codepoints.json ids without a master: ${missing.join(', ')}`);
    font(skin, tracedDir, cps);
    const roles = resolveRoles(skin);
    dart(skin, cps, roles);
    react(skin, paths);
    webRoles(skin, roles);
    all[skin] = { paths, cps, roles };
    console.log(`${skin}: ${Object.keys(paths).length} traced ids, ${roles.length} roles, ${SKINS[skin].font}.ttf`);
  }
  dartTest(all);
  if (PROOF) {
    proof(all);
    console.log('proof: docs/redesign/proof/shared-02/{glyphs-cinematic.svg,glyphs-glass.svg,roles.md}');
  }
} finally {
  fs.rmSync(tmpRoot, { recursive: true, force: true });
}
