// GENERATED by brand/cinematic/export.mjs — do not edit
export const SKIN_FAVICONS = { cinematic: "/favicon.svg", glass: "/favicon-glass.svg" } as const;
export const APPLE_TOUCH_ICON = "/icons/apple-touch-icon.png";
export const APPLE_STARTUP_IMAGES = [
  { url: "/splash/apple-splash-1290x2796.png", media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  { url: "/splash/apple-splash-1179x2556.png", media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  { url: "/splash/apple-splash-1170x2532.png", media: "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  { url: "/splash/apple-splash-2048x2732.png", media: "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
] as const;
