// GENERATED by design/build.mjs from design/contract.json — do not edit.

export const SCREEN_IDS = ["setup","login","register","profiles","profileNew","profileEdit","profilesManage","onboarding","tonight","library","updates","collections","collection","history","bookmarks","picks","numbers","annual","featureByFollow","feature","recap","circle","circleMember","discover","sources","source","reader","readAll","novel","downloads","dialogue","index","settings","status","readerLanding"] as const;
export type ScreenId = (typeof SCREEN_IDS)[number];

export interface ScreenSpec {
  readonly path: string;
  readonly params: readonly string[];
  readonly query: readonly string[];
  readonly aliases: readonly { readonly path: string; readonly platforms: readonly ("web" | "app")[] }[];
  readonly redirect: { readonly web?: string; readonly app?: string } | null;
}

export const SCREENS = {
  setup: { path: "/setup", params: [], query: [], aliases: [], redirect: {web: "/login"} },
  login: { path: "/login", params: [], query: [], aliases: [], redirect: null },
  register: { path: "/register", params: [], query: [], aliases: [], redirect: null },
  profiles: { path: "/profiles", params: [], query: [], aliases: [], redirect: null },
  profileNew: { path: "/profiles/new", params: [], query: [], aliases: [{path: "/profiles/create",platforms: ["app"]}], redirect: null },
  profileEdit: { path: "/profiles/:id/edit", params: ["id"], query: [], aliases: [{path: "/profiles/edit/:id",platforms: ["app"]}], redirect: null },
  profilesManage: { path: "/profiles/manage", params: [], query: [], aliases: [], redirect: null },
  onboarding: { path: "/welcome", params: [], query: ["step"], aliases: [], redirect: null },
  tonight: { path: "/", params: [], query: [], aliases: [], redirect: null },
  library: { path: "/library", params: [], query: ["q","status","sort","fav","view","select","tab","reading_status","tags"], aliases: [{path: "/library/browse",platforms: ["web","app"]}], redirect: null },
  updates: { path: "/updates", params: [], query: ["tab"], aliases: [], redirect: null },
  collections: { path: "/library/collections", params: [], query: [], aliases: [{path: "/collections",platforms: ["app"]}], redirect: null },
  collection: { path: "/library/collections/:id", params: ["id"], query: [], aliases: [{path: "/collections/:id",platforms: ["app"]}], redirect: null },
  history: { path: "/library/history", params: [], query: [], aliases: [], redirect: null },
  bookmarks: { path: "/library/bookmarks", params: [], query: ["source","series"], aliases: [], redirect: null },
  picks: { path: "/library/recommendations", params: [], query: ["genre"], aliases: [], redirect: null },
  numbers: { path: "/library/statistics", params: [], query: ["range","year"], aliases: [], redirect: null },
  annual: { path: "/library/statistics/annual/:year", params: ["year"], query: [], aliases: [], redirect: null },
  featureByFollow: { path: "/library/:followedId", params: ["followedId"], query: [], aliases: [], redirect: null },
  feature: { path: "/sources/:sourceId/series/:seriesKey", params: ["sourceId","seriesKey"], query: [], aliases: [], redirect: null },
  recap: { path: "/recap/:sourceId/:seriesKey", params: ["sourceId","seriesKey"], query: ["to","scope"], aliases: [], redirect: null },
  circle: { path: "/circle", params: [], query: ["tab"], aliases: [], redirect: null },
  circleMember: { path: "/circle/:profileId", params: ["profileId"], query: [], aliases: [], redirect: null },
  discover: { path: "/search", params: [], query: ["q","scope"], aliases: [], redirect: null },
  sources: { path: "/sources", params: [], query: [], aliases: [], redirect: null },
  source: { path: "/sources/:sourceId", params: ["sourceId"], query: ["mode","genre","q"], aliases: [], redirect: null },
  reader: { path: "/reader/:sourceId/:seriesKey/:chapterKey", params: ["sourceId","seriesKey","chapterKey"], query: ["page","at","all"], aliases: [{path: "/library/read/:sourceId/:seriesKey/:chapterKey",platforms: ["app"]},{path: "/sources/:sourceId/series/:seriesKey/chapters/:chapterKey/read",platforms: ["app"]}], redirect: null },
  readAll: { path: "/read-all/:sourceId/:seriesKey", params: ["sourceId","seriesKey"], query: ["from","page","at"], aliases: [], redirect: null },
  novel: { path: "/novels/:sourceId/:seriesKey/:chapterKey", params: ["sourceId","seriesKey","chapterKey"], query: ["page","para","at","listen"], aliases: [{path: "/novels/read/:sourceId/:seriesKey/:chapterKey",platforms: ["app"]}], redirect: null },
  downloads: { path: "/downloads", params: [], query: ["tab"], aliases: [], redirect: null },
  dialogue: { path: "/ocr", params: [], query: ["q"], aliases: [{path: "/ocr/search",platforms: ["app"]}], redirect: null },
  index: { path: "/more", params: [], query: [], aliases: [], redirect: null },
  settings: { path: "/settings", params: [], query: [], aliases: [{path: "/settings/:section",platforms: ["web","app"]}], redirect: null },
  status: { path: "/admin/status", params: [], query: [], aliases: [], redirect: null },
  readerLanding: { path: "/reader", params: [], query: [], aliases: [], redirect: {app: "/library"} },
} as const satisfies Record<ScreenId, ScreenSpec>;

export const SETTINGS_SECTIONS = ["profile","appearance","reading-manga","reading-novels","listen","ambient","storage","content","circle","feedback","notifications","keyboard","server","admin","diagnostics","about","ai","security","members","backup"] as const;
export type SettingsSection = (typeof SETTINGS_SECTIONS)[number];
export const SETTINGS_SECTION_SPECS = {
  profile: {platforms: ["web","app"],pushed: false},
  appearance: {platforms: ["web","app"],pushed: false},
  "reading-manga": {platforms: ["web","app"],pushed: false},
  "reading-novels": {platforms: ["web","app"],pushed: false},
  listen: {platforms: ["web","app"],pushed: false},
  ambient: {platforms: ["web","app"],pushed: false},
  storage: {platforms: ["web","app"],pushed: false},
  content: {platforms: ["web","app"],pushed: false},
  circle: {platforms: ["web","app"],pushed: false},
  feedback: {platforms: ["web","app"],pushed: false},
  notifications: {platforms: ["web","app"],pushed: false},
  keyboard: {platforms: ["web","app"],pushed: false},
  server: {platforms: ["app"],pushed: false},
  admin: {platforms: ["web","app"],pushed: false},
  diagnostics: {platforms: ["web","app"],pushed: false,webDebugOnly: true},
  about: {platforms: ["web","app"],pushed: false},
  ai: {platforms: ["web","app"],pushed: false},
  security: {platforms: ["web","app"],pushed: true},
  members: {platforms: ["web","app"],pushed: true},
  backup: {platforms: ["web","app"],pushed: true},
} as const satisfies Record<SettingsSection, { platforms: readonly string[]; pushed: boolean; webDebugOnly?: boolean }>;

export const SHEET_IDS = ["chapters","settings","contents","type","voices","cast","player","soundscape","note","save-files","tags","recommend","audiobook","how-it-works","offer","image","move-source","filters","manage-tags","collection-new","collection-edit","collection-share","add-series","run","whats-new","app-update","shortcuts","licenses","letter-note"] as const;
export type SheetId = (typeof SHEET_IDS)[number];

export const FLAGS = { glassAvailable: false } as const;

export const HAPTIC_EVENTS = ["tap.primary","tap.secondary","toggle.on","toggle.off","select","nav.change","longpress.open","sheet.detent","sheet.dismiss","refresh.arm","refresh.fire","follow.add","follow.remove","favorite","bookmark.add","download.start","download.done","download.fail","delete.confirm","undo","reader.enter","page.turn","scrub.tick","scrub.boundary","chapter.complete","chapter.next","autoscroll.toggle","autoscroll.step","autoscroll.end","zoom.snap","listen.toggle","voice.assign","sleep.fade","streak.extend","streak.milestone","recap.countdown.end","annual.page","share.export","reaction.send","recommend.send","gate.confirm","splash.impress","profile.select","skin.switch","reader.unlock","success","error","nav.scrub","nav.reselect","nav.push","nav.pop","nav.root","stack.open","stack.pick","detent.tick","detent.magnet","detent.limit","press.lift","throw.commit","motion.catch","magnet.capture","magnet.drop","reorder.lift","reorder.pass","reorder.drop","sheet.pass","threshold.cross","threshold.back","refresh.done","hold.ramp","hold.done","chapter.arm","chapter.seam","zoom.limit","panel.step","ocr.hit","autoscroll.start","voice.center","recap.ready","goal.met","share.lift","share.flip","reaction.bloom","reaction.cross","logo.land","logo.settle","logo.reduced","annual.podium","annual.summary","warning"] as const;
export type HapticEvent = (typeof HAPTIC_EVENTS)[number];
export const SOUND_EVENTS = ["tap.primary","toggle.on","toggle.off","select","nav.change","follow.add","favorite","bookmark.add","download.done","download.fail","undo","reader.enter","page.turn","refresh.arm","scrub.boundary","chapter.complete","chapter.next","autoscroll.toggle","voice.assign","streak.extend","streak.milestone","annual.page","share.export","reaction.send","recommend.send","gate.confirm","skin.switch","reader.unlock","error","sheet.open","splash.reveal","detent.tick","sheet.pass","scrub.tick","nav.scrub","sheet.close","nav.push","nav.pop","nav.root","stack.open","logo.land","throw.commit","motion.catch","magnet.capture","recap.ready","magnet.drop","annual.podium","hold.done","goal.met","annual.summary","share.flip","logo.settle"] as const;
export type SoundEvent = (typeof SOUND_EVENTS)[number];

/** A haptic value (design/lib/haptics.mjs grammar): a pattern, a sequence or a repeat. */
export type HapticPattern = string;
export type HapticValue =
  | HapticPattern
  | readonly [HapticPattern, ...{ readonly after: number; readonly then: HapticPattern }[]]
  | { readonly repeat: HapticPattern; readonly every: number; readonly max: number };
export type AhapEvent =
  | { readonly type: "T"; readonly t: number; readonly i: number; readonly s: number }
  | { readonly type: "C"; readonly t: number; readonly dur: number; readonly i: number; readonly s: number };

type PathValue = string | number;
type QueryValue = string | number | boolean | null;

// The builder of design/lib/route.mjs: segments through encodeURIComponent, the query through
// URLSearchParams in insertion order, undefined and null values skipped.
function buildRoute(pattern: string, params: readonly PathValue[], query?: Readonly<Record<string, unknown>>): string {
  let i = 0;
  const path = pattern.replace(/:[A-Za-z]+/g, () => encodeURIComponent(String(params[i++])));
  const entries = [];
  for (const [k, v] of Object.entries(query ?? {})) if (v !== undefined && v !== null) entries.push([k, String(v)]);
  const qs = new URLSearchParams(entries).toString();
  return qs ? path + "?" + qs : path;
}

export const ROUTES = {
  setup: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/setup", [], query),
  login: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/login", [], query),
  register: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/register", [], query),
  profiles: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/profiles", [], query),
  profileNew: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/profiles/new", [], query),
  profileEdit: (id: PathValue, query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/profiles/:id/edit", [id], query),
  profilesManage: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/profiles/manage", [], query),
  onboarding: (query?: { step?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | null; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/welcome", [], query),
  tonight: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/", [], query),
  library: (query?: { q?: QueryValue; status?: "reading" | "unread" | "completed" | null; sort?: QueryValue; fav?: QueryValue; view?: QueryValue; select?: QueryValue; tab?: QueryValue; reading_status?: "unread" | "reading" | "completed" | "on_hold" | "plan_to_read" | "dropped" | null; tags?: QueryValue; sheet?: SheetId | null }): string => buildRoute("/library", [], query),
  updates: (query?: { tab?: "following" | "unread" | "followed" | null; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/updates", [], query),
  collections: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/library/collections", [], query),
  collection: (id: PathValue, query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/library/collections/:id", [id], query),
  history: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/library/history", [], query),
  bookmarks: (query?: { source?: QueryValue; series?: QueryValue; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/library/bookmarks", [], query),
  picks: (query?: { genre?: QueryValue; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/library/recommendations", [], query),
  numbers: (query?: { range?: 7 | 30 | 90 | "year" | null; year?: QueryValue; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/library/statistics", [], query),
  annual: (year: PathValue, query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/library/statistics/annual/:year", [year], query),
  featureByFollow: (followedId: PathValue, query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/library/:followedId", [followedId], query),
  feature: (sourceId: PathValue, seriesKey: PathValue, query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/sources/:sourceId/series/:seriesKey", [sourceId, seriesKey], query),
  recap: (sourceId: PathValue, seriesKey: PathValue, query: { to: QueryValue; scope?: "series" | "chapter" | null; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/recap/:sourceId/:seriesKey", [sourceId, seriesKey], query),
  circle: (query?: { tab?: "activity" | "letters" | "shelves" | null; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/circle", [], query),
  circleMember: (profileId: PathValue, query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/circle/:profileId", [profileId], query),
  discover: (query?: { q?: QueryValue; scope?: "all" | "library" | "sources" | "dialogue" | "text" | "ask" | null; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/search", [], query),
  sources: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/sources", [], query),
  source: (sourceId: PathValue, query?: { mode?: QueryValue; genre?: QueryValue; q?: QueryValue; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/sources/:sourceId", [sourceId], query),
  reader: (sourceId: PathValue, seriesKey: PathValue, chapterKey: PathValue, query?: { page?: QueryValue; at?: QueryValue; all?: QueryValue; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/reader/:sourceId/:seriesKey/:chapterKey", [sourceId, seriesKey, chapterKey], query),
  readAll: (sourceId: PathValue, seriesKey: PathValue, query?: { from?: QueryValue; page?: QueryValue; at?: QueryValue; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/read-all/:sourceId/:seriesKey", [sourceId, seriesKey], query),
  novel: (sourceId: PathValue, seriesKey: PathValue, chapterKey: PathValue, query?: { page?: QueryValue; para?: QueryValue; at?: QueryValue; listen?: QueryValue; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/novels/:sourceId/:seriesKey/:chapterKey", [sourceId, seriesKey, chapterKey], query),
  downloads: (query?: { tab?: "chapters" | "queue" | "storage" | null; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/downloads", [], query),
  dialogue: (query?: { q?: QueryValue; sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/ocr", [], query),
  index: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/more", [], query),
  settings: (section?: SettingsSection, query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string =>
    section === undefined ? buildRoute("/settings", [], query) : buildRoute("/settings/:section", [section], query),
  status: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/admin/status", [], query),
  readerLanding: (query?: { sheet?: SheetId | null; view?: "cover" | "milestone" | null }): string => buildRoute("/reader", [], query),
} as const;
