// GENERATED by brand/build-glyphs.mjs from design/icons.json and brand/glass/glyphs — do not edit.
import 'package:flutter/widgets.dart';

/// Custom glyphs of the GlassGlyphs font (mobile/assets/fonts/GlassGlyphs.ttf).
abstract final class GlassGlyphs {
  static const IconData ageGateDuotone = IconData(0xE900, fontFamily: 'GlassGlyphs');
  static const IconData ageGateDuotoneSecondary = IconData(0xE901, fontFamily: 'GlassGlyphs');
  static const IconData ageGateFill = IconData(0xE902, fontFamily: 'GlassGlyphs');
  static const IconData ageGateRegular = IconData(0xE903, fontFamily: 'GlassGlyphs');
  static const IconData bubbleSearchDuotone = IconData(0xE904, fontFamily: 'GlassGlyphs');
  static const IconData bubbleSearchDuotoneSecondary = IconData(0xE905, fontFamily: 'GlassGlyphs');
  static const IconData bubbleSearchFill = IconData(0xE906, fontFamily: 'GlassGlyphs');
  static const IconData bubbleSearchRegular = IconData(0xE907, fontFamily: 'GlassGlyphs');
  static const IconData dropletDuotone = IconData(0xE908, fontFamily: 'GlassGlyphs');
  static const IconData dropletDuotoneSecondary = IconData(0xE909, fontFamily: 'GlassGlyphs');
  static const IconData dropletFill = IconData(0xE90A, fontFamily: 'GlassGlyphs');
  static const IconData dropletRegular = IconData(0xE90B, fontFamily: 'GlassGlyphs');
  static const IconData flywheelDuotone = IconData(0xE90C, fontFamily: 'GlassGlyphs');
  static const IconData flywheelDuotoneSecondary = IconData(0xE90D, fontFamily: 'GlassGlyphs');
  static const IconData flywheelFill = IconData(0xE90E, fontFamily: 'GlassGlyphs');
  static const IconData flywheelRegular = IconData(0xE90F, fontFamily: 'GlassGlyphs');
  static const IconData mmMarkDuotone = IconData(0xE910, fontFamily: 'GlassGlyphs');
  static const IconData mmMarkDuotoneSecondary = IconData(0xE911, fontFamily: 'GlassGlyphs');
  static const IconData mmMarkFill = IconData(0xE912, fontFamily: 'GlassGlyphs');
  static const IconData mmMarkRegular = IconData(0xE913, fontFamily: 'GlassGlyphs');
  static const IconData panelFocusDuotone = IconData(0xE914, fontFamily: 'GlassGlyphs');
  static const IconData panelFocusDuotoneSecondary = IconData(0xE915, fontFamily: 'GlassGlyphs');
  static const IconData panelFocusFill = IconData(0xE916, fontFamily: 'GlassGlyphs');
  static const IconData panelFocusRegular = IconData(0xE917, fontFamily: 'GlassGlyphs');
  static const IconData sparkleSlashDuotone = IconData(0xE918, fontFamily: 'GlassGlyphs');
  static const IconData sparkleSlashDuotoneSecondary = IconData(0xE919, fontFamily: 'GlassGlyphs');
  static const IconData sparkleSlashFill = IconData(0xE91A, fontFamily: 'GlassGlyphs');
  static const IconData sparkleSlashRegular = IconData(0xE91B, fontFamily: 'GlassGlyphs');
  static const IconData strata1Duotone = IconData(0xE91C, fontFamily: 'GlassGlyphs');
  static const IconData strata1DuotoneSecondary = IconData(0xE91D, fontFamily: 'GlassGlyphs');
  static const IconData strata1Fill = IconData(0xE91E, fontFamily: 'GlassGlyphs');
  static const IconData strata1Regular = IconData(0xE91F, fontFamily: 'GlassGlyphs');
  static const IconData strata2Duotone = IconData(0xE920, fontFamily: 'GlassGlyphs');
  static const IconData strata2DuotoneSecondary = IconData(0xE921, fontFamily: 'GlassGlyphs');
  static const IconData strata2Fill = IconData(0xE922, fontFamily: 'GlassGlyphs');
  static const IconData strata2Regular = IconData(0xE923, fontFamily: 'GlassGlyphs');
  static const IconData strata3Duotone = IconData(0xE924, fontFamily: 'GlassGlyphs');
  static const IconData strata3DuotoneSecondary = IconData(0xE925, fontFamily: 'GlassGlyphs');
  static const IconData strata3Fill = IconData(0xE926, fontFamily: 'GlassGlyphs');
  static const IconData strata3Regular = IconData(0xE927, fontFamily: 'GlassGlyphs');
  static const IconData strata4Duotone = IconData(0xE928, fontFamily: 'GlassGlyphs');
  static const IconData strata4DuotoneSecondary = IconData(0xE929, fontFamily: 'GlassGlyphs');
  static const IconData strata4Fill = IconData(0xE92A, fontFamily: 'GlassGlyphs');
  static const IconData strata4Regular = IconData(0xE92B, fontFamily: 'GlassGlyphs');
  static const IconData stripScrollDuotone = IconData(0xE92C, fontFamily: 'GlassGlyphs');
  static const IconData stripScrollDuotoneSecondary = IconData(0xE92D, fontFamily: 'GlassGlyphs');
  static const IconData stripScrollFill = IconData(0xE92E, fontFamily: 'GlassGlyphs');
  static const IconData stripScrollRegular = IconData(0xE92F, fontFamily: 'GlassGlyphs');
  static const IconData voice31Duotone = IconData(0xE930, fontFamily: 'GlassGlyphs');
  static const IconData voice31DuotoneSecondary = IconData(0xE931, fontFamily: 'GlassGlyphs');
  static const IconData voice31Fill = IconData(0xE932, fontFamily: 'GlassGlyphs');
  static const IconData voice31Regular = IconData(0xE933, fontFamily: 'GlassGlyphs');
}
