// GENERATED by brand/build-glyphs.mjs from design/icons.json and brand/cinematic/glyphs — do not edit.
import 'package:flutter/widgets.dart';

/// Custom glyphs of the CineGlyphs font (mobile/assets/fonts/CineGlyphs.ttf).
abstract final class CineGlyphs {
  static const IconData annualFill = IconData(0xE900, fontFamily: 'CineGlyphs');
  static const IconData annualLight = IconData(0xE901, fontFamily: 'CineGlyphs');
  static const IconData annualRegular = IconData(0xE902, fontFamily: 'CineGlyphs');
  static const IconData bubbleSearchFill = IconData(0xE903, fontFamily: 'CineGlyphs');
  static const IconData bubbleSearchLight = IconData(0xE904, fontFamily: 'CineGlyphs');
  static const IconData bubbleSearchRegular = IconData(0xE905, fontFamily: 'CineGlyphs');
  static const IconData certificate18Fill = IconData(0xE906, fontFamily: 'CineGlyphs');
  static const IconData certificate18Light = IconData(0xE907, fontFamily: 'CineGlyphs');
  static const IconData certificate18Regular = IconData(0xE908, fontFamily: 'CineGlyphs');
  static const IconData flame1Fill = IconData(0xE909, fontFamily: 'CineGlyphs');
  static const IconData flame1Light = IconData(0xE90A, fontFamily: 'CineGlyphs');
  static const IconData flame1Regular = IconData(0xE90B, fontFamily: 'CineGlyphs');
  static const IconData flame3Fill = IconData(0xE90C, fontFamily: 'CineGlyphs');
  static const IconData flame3Light = IconData(0xE90D, fontFamily: 'CineGlyphs');
  static const IconData flame3Regular = IconData(0xE90E, fontFamily: 'CineGlyphs');
  static const IconData highlighterFill = IconData(0xE90F, fontFamily: 'CineGlyphs');
  static const IconData highlighterLight = IconData(0xE910, fontFamily: 'CineGlyphs');
  static const IconData highlighterRegular = IconData(0xE911, fontFamily: 'CineGlyphs');
  static const IconData mmMarkFill = IconData(0xE912, fontFamily: 'CineGlyphs');
  static const IconData mmMarkLight = IconData(0xE913, fontFamily: 'CineGlyphs');
  static const IconData mmMarkRegular = IconData(0xE914, fontFamily: 'CineGlyphs');
  static const IconData panelFocusFill = IconData(0xE915, fontFamily: 'CineGlyphs');
  static const IconData panelFocusLight = IconData(0xE916, fontFamily: 'CineGlyphs');
  static const IconData panelFocusRegular = IconData(0xE917, fontFamily: 'CineGlyphs');
  static const IconData stripScrollFill = IconData(0xE918, fontFamily: 'CineGlyphs');
  static const IconData stripScrollLight = IconData(0xE919, fontFamily: 'CineGlyphs');
  static const IconData stripScrollRegular = IconData(0xE91A, fontFamily: 'CineGlyphs');
  static const IconData voice31Fill = IconData(0xE91B, fontFamily: 'CineGlyphs');
  static const IconData voice31Light = IconData(0xE91C, fontFamily: 'CineGlyphs');
  static const IconData voice31Regular = IconData(0xE91D, fontFamily: 'CineGlyphs');
}
