// GENERATED by brand/build-glyphs.mjs from design/icons.json and brand/cinematic/glyphs — do not edit.
import 'package:flutter/widgets.dart';

import 'cine_glyphs.g.dart';
import 'phosphor.g.dart';

/// Semantic icon roles of design/icons.json that the cinematic skin draws. A role named like an Enum member gets a `Role` suffix (index → indexRole).
enum CineIconRole { back, close, search, home, library, discover, downloads, indexRole, updates, sources, collections, history, bookmark, stats, circle, settings, status, picks, dialogueSearch, readerSettings, type, contents, listen, play, pause, chapterPrevious, chapterNext, download, downloaded, pin, favourite, follow, following, notify, share, recommend, filter, sort, viewGrid, viewList, select, delete, edit, overflow, fullscreenEnter, fullscreenExit, zoomIn, zoomOut, brightness, warmth, offline, refresh, external, soundscape, autoScroll, stripMode, guidedView, flame, streakShort, streakLong, ageGate, voiceCast, annual, highlighter, brandMark }

/// Weights the cinematic skin uses.
enum CineIconWeight { light, regular, fill }

const Map<CineIconRole, Map<CineIconWeight, IconData>> cineIcons = {
  CineIconRole.back: {
    CineIconWeight.light: PhosphorLight.arrowLeft,
    CineIconWeight.regular: PhosphorRegular.arrowLeft,
    CineIconWeight.fill: PhosphorFill.arrowLeft,
  },
  CineIconRole.close: {
    CineIconWeight.light: PhosphorLight.x,
    CineIconWeight.regular: PhosphorRegular.x,
    CineIconWeight.fill: PhosphorFill.x,
  },
  CineIconRole.search: {
    CineIconWeight.light: PhosphorLight.magnifyingGlass,
    CineIconWeight.regular: PhosphorRegular.magnifyingGlass,
    CineIconWeight.fill: PhosphorFill.magnifyingGlass,
  },
  CineIconRole.home: {
    CineIconWeight.light: PhosphorLight.moonStars,
    CineIconWeight.regular: PhosphorRegular.moonStars,
    CineIconWeight.fill: PhosphorFill.moonStars,
  },
  CineIconRole.library: {
    CineIconWeight.light: PhosphorLight.books,
    CineIconWeight.regular: PhosphorRegular.books,
    CineIconWeight.fill: PhosphorFill.books,
  },
  CineIconRole.discover: {
    CineIconWeight.light: PhosphorLight.compass,
    CineIconWeight.regular: PhosphorRegular.compass,
    CineIconWeight.fill: PhosphorFill.compass,
  },
  CineIconRole.downloads: {
    CineIconWeight.light: PhosphorLight.downloadSimple,
    CineIconWeight.regular: PhosphorRegular.downloadSimple,
    CineIconWeight.fill: PhosphorFill.downloadSimple,
  },
  CineIconRole.indexRole: {
    CineIconWeight.light: PhosphorLight.listNumbers,
    CineIconWeight.regular: PhosphorRegular.listNumbers,
    CineIconWeight.fill: PhosphorFill.listNumbers,
  },
  CineIconRole.updates: {
    CineIconWeight.light: PhosphorLight.bellSimple,
    CineIconWeight.regular: PhosphorRegular.bellSimple,
    CineIconWeight.fill: PhosphorFill.bellSimple,
  },
  CineIconRole.sources: {
    CineIconWeight.light: PhosphorLight.globeSimple,
    CineIconWeight.regular: PhosphorRegular.globeSimple,
    CineIconWeight.fill: PhosphorFill.globeSimple,
  },
  CineIconRole.collections: {
    CineIconWeight.light: PhosphorLight.stackSimple,
    CineIconWeight.regular: PhosphorRegular.stackSimple,
    CineIconWeight.fill: PhosphorFill.stackSimple,
  },
  CineIconRole.history: {
    CineIconWeight.light: PhosphorLight.clockCounterClockwise,
    CineIconWeight.regular: PhosphorRegular.clockCounterClockwise,
    CineIconWeight.fill: PhosphorFill.clockCounterClockwise,
  },
  CineIconRole.bookmark: {
    CineIconWeight.light: PhosphorLight.bookmarkSimple,
    CineIconWeight.regular: PhosphorRegular.bookmarkSimple,
    CineIconWeight.fill: PhosphorFill.bookmarkSimple,
  },
  CineIconRole.stats: {
    CineIconWeight.light: PhosphorLight.chartBar,
    CineIconWeight.regular: PhosphorRegular.chartBar,
    CineIconWeight.fill: PhosphorFill.chartBar,
  },
  CineIconRole.circle: {
    CineIconWeight.light: PhosphorLight.usersThree,
    CineIconWeight.regular: PhosphorRegular.usersThree,
    CineIconWeight.fill: PhosphorFill.usersThree,
  },
  CineIconRole.settings: {
    CineIconWeight.light: PhosphorLight.gearSix,
    CineIconWeight.regular: PhosphorRegular.gearSix,
    CineIconWeight.fill: PhosphorFill.gearSix,
  },
  CineIconRole.status: {
    CineIconWeight.light: PhosphorLight.pulse,
    CineIconWeight.regular: PhosphorRegular.pulse,
    CineIconWeight.fill: PhosphorFill.pulse,
  },
  CineIconRole.picks: {
    CineIconWeight.light: PhosphorLight.sparkle,
    CineIconWeight.regular: PhosphorRegular.sparkle,
    CineIconWeight.fill: PhosphorFill.sparkle,
  },
  CineIconRole.dialogueSearch: {
    CineIconWeight.light: CineGlyphs.bubbleSearchLight,
    CineIconWeight.regular: CineGlyphs.bubbleSearchRegular,
    CineIconWeight.fill: CineGlyphs.bubbleSearchFill,
  },
  CineIconRole.readerSettings: {
    CineIconWeight.light: PhosphorLight.slidersHorizontal,
    CineIconWeight.regular: PhosphorRegular.slidersHorizontal,
    CineIconWeight.fill: PhosphorFill.slidersHorizontal,
  },
  CineIconRole.type: {
    CineIconWeight.light: PhosphorLight.textAa,
    CineIconWeight.regular: PhosphorRegular.textAa,
    CineIconWeight.fill: PhosphorFill.textAa,
  },
  CineIconRole.contents: {
    CineIconWeight.light: PhosphorLight.listNumbers,
    CineIconWeight.regular: PhosphorRegular.listNumbers,
    CineIconWeight.fill: PhosphorFill.listNumbers,
  },
  CineIconRole.listen: {
    CineIconWeight.light: PhosphorLight.headphones,
    CineIconWeight.regular: PhosphorRegular.headphones,
    CineIconWeight.fill: PhosphorFill.headphones,
  },
  CineIconRole.play: {
    CineIconWeight.light: PhosphorLight.play,
    CineIconWeight.regular: PhosphorRegular.play,
    CineIconWeight.fill: PhosphorFill.play,
  },
  CineIconRole.pause: {
    CineIconWeight.light: PhosphorLight.pause,
    CineIconWeight.regular: PhosphorRegular.pause,
    CineIconWeight.fill: PhosphorFill.pause,
  },
  CineIconRole.chapterPrevious: {
    CineIconWeight.light: PhosphorLight.skipBack,
    CineIconWeight.regular: PhosphorRegular.skipBack,
    CineIconWeight.fill: PhosphorFill.skipBack,
  },
  CineIconRole.chapterNext: {
    CineIconWeight.light: PhosphorLight.skipForward,
    CineIconWeight.regular: PhosphorRegular.skipForward,
    CineIconWeight.fill: PhosphorFill.skipForward,
  },
  CineIconRole.download: {
    CineIconWeight.light: PhosphorLight.cloudArrowDown,
    CineIconWeight.regular: PhosphorRegular.cloudArrowDown,
    CineIconWeight.fill: PhosphorFill.cloudArrowDown,
  },
  CineIconRole.downloaded: {
    CineIconWeight.light: PhosphorLight.checkSquare,
    CineIconWeight.regular: PhosphorRegular.checkSquare,
    CineIconWeight.fill: PhosphorFill.checkSquare,
  },
  CineIconRole.pin: {
    CineIconWeight.light: PhosphorLight.pushPin,
    CineIconWeight.regular: PhosphorRegular.pushPin,
    CineIconWeight.fill: PhosphorFill.pushPin,
  },
  CineIconRole.favourite: {
    CineIconWeight.light: PhosphorLight.star,
    CineIconWeight.regular: PhosphorRegular.star,
    CineIconWeight.fill: PhosphorFill.star,
  },
  CineIconRole.follow: {
    CineIconWeight.light: PhosphorLight.plus,
    CineIconWeight.regular: PhosphorRegular.plus,
    CineIconWeight.fill: PhosphorFill.plus,
  },
  CineIconRole.following: {
    CineIconWeight.light: PhosphorLight.check,
    CineIconWeight.regular: PhosphorRegular.check,
    CineIconWeight.fill: PhosphorFill.check,
  },
  CineIconRole.notify: {
    CineIconWeight.light: PhosphorLight.bellRinging,
    CineIconWeight.regular: PhosphorRegular.bellRinging,
    CineIconWeight.fill: PhosphorFill.bellRinging,
  },
  CineIconRole.share: {
    CineIconWeight.light: PhosphorLight.export,
    CineIconWeight.regular: PhosphorRegular.export,
    CineIconWeight.fill: PhosphorFill.export,
  },
  CineIconRole.recommend: {
    CineIconWeight.light: PhosphorLight.paperPlaneTilt,
    CineIconWeight.regular: PhosphorRegular.paperPlaneTilt,
    CineIconWeight.fill: PhosphorFill.paperPlaneTilt,
  },
  CineIconRole.filter: {
    CineIconWeight.light: PhosphorLight.funnelSimple,
    CineIconWeight.regular: PhosphorRegular.funnelSimple,
    CineIconWeight.fill: PhosphorFill.funnelSimple,
  },
  CineIconRole.sort: {
    CineIconWeight.light: PhosphorLight.arrowsDownUp,
    CineIconWeight.regular: PhosphorRegular.arrowsDownUp,
    CineIconWeight.fill: PhosphorFill.arrowsDownUp,
  },
  CineIconRole.viewGrid: {
    CineIconWeight.light: PhosphorLight.squaresFour,
    CineIconWeight.regular: PhosphorRegular.squaresFour,
    CineIconWeight.fill: PhosphorFill.squaresFour,
  },
  CineIconRole.viewList: {
    CineIconWeight.light: PhosphorLight.rows,
    CineIconWeight.regular: PhosphorRegular.rows,
    CineIconWeight.fill: PhosphorFill.rows,
  },
  CineIconRole.select: {
    CineIconWeight.light: PhosphorLight.checkSquareOffset,
    CineIconWeight.regular: PhosphorRegular.checkSquareOffset,
    CineIconWeight.fill: PhosphorFill.checkSquareOffset,
  },
  CineIconRole.delete: {
    CineIconWeight.light: PhosphorLight.trashSimple,
    CineIconWeight.regular: PhosphorRegular.trashSimple,
    CineIconWeight.fill: PhosphorFill.trashSimple,
  },
  CineIconRole.edit: {
    CineIconWeight.light: PhosphorLight.pencilSimpleLine,
    CineIconWeight.regular: PhosphorRegular.pencilSimpleLine,
    CineIconWeight.fill: PhosphorFill.pencilSimpleLine,
  },
  CineIconRole.overflow: {
    CineIconWeight.light: PhosphorLight.dotsThree,
    CineIconWeight.regular: PhosphorRegular.dotsThree,
    CineIconWeight.fill: PhosphorFill.dotsThree,
  },
  CineIconRole.fullscreenEnter: {
    CineIconWeight.light: PhosphorLight.cornersOut,
    CineIconWeight.regular: PhosphorRegular.cornersOut,
    CineIconWeight.fill: PhosphorFill.cornersOut,
  },
  CineIconRole.fullscreenExit: {
    CineIconWeight.light: PhosphorLight.cornersIn,
    CineIconWeight.regular: PhosphorRegular.cornersIn,
    CineIconWeight.fill: PhosphorFill.cornersIn,
  },
  CineIconRole.zoomIn: {
    CineIconWeight.light: PhosphorLight.magnifyingGlassPlus,
    CineIconWeight.regular: PhosphorRegular.magnifyingGlassPlus,
    CineIconWeight.fill: PhosphorFill.magnifyingGlassPlus,
  },
  CineIconRole.zoomOut: {
    CineIconWeight.light: PhosphorLight.magnifyingGlassMinus,
    CineIconWeight.regular: PhosphorRegular.magnifyingGlassMinus,
    CineIconWeight.fill: PhosphorFill.magnifyingGlassMinus,
  },
  CineIconRole.brightness: {
    CineIconWeight.light: PhosphorLight.sunDim,
    CineIconWeight.regular: PhosphorRegular.sunDim,
    CineIconWeight.fill: PhosphorFill.sunDim,
  },
  CineIconRole.warmth: {
    CineIconWeight.light: PhosphorLight.thermometerSimple,
    CineIconWeight.regular: PhosphorRegular.thermometerSimple,
    CineIconWeight.fill: PhosphorFill.thermometerSimple,
  },
  CineIconRole.offline: {
    CineIconWeight.light: PhosphorLight.wifiSlash,
    CineIconWeight.regular: PhosphorRegular.wifiSlash,
    CineIconWeight.fill: PhosphorFill.wifiSlash,
  },
  CineIconRole.refresh: {
    CineIconWeight.light: PhosphorLight.arrowClockwise,
    CineIconWeight.regular: PhosphorRegular.arrowClockwise,
    CineIconWeight.fill: PhosphorFill.arrowClockwise,
  },
  CineIconRole.external: {
    CineIconWeight.light: PhosphorLight.arrowSquareOut,
    CineIconWeight.regular: PhosphorRegular.arrowSquareOut,
    CineIconWeight.fill: PhosphorFill.arrowSquareOut,
  },
  CineIconRole.soundscape: {
    CineIconWeight.light: PhosphorLight.waveform,
    CineIconWeight.regular: PhosphorRegular.waveform,
    CineIconWeight.fill: PhosphorFill.waveform,
  },
  CineIconRole.autoScroll: {
    CineIconWeight.light: CineGlyphs.stripScrollLight,
    CineIconWeight.regular: CineGlyphs.stripScrollRegular,
    CineIconWeight.fill: CineGlyphs.stripScrollFill,
  },
  CineIconRole.stripMode: {
    CineIconWeight.light: CineGlyphs.stripScrollLight,
    CineIconWeight.regular: CineGlyphs.stripScrollRegular,
    CineIconWeight.fill: CineGlyphs.stripScrollFill,
  },
  CineIconRole.guidedView: {
    CineIconWeight.light: CineGlyphs.panelFocusLight,
    CineIconWeight.regular: CineGlyphs.panelFocusRegular,
    CineIconWeight.fill: CineGlyphs.panelFocusFill,
  },
  CineIconRole.flame: {
    CineIconWeight.light: PhosphorLight.flame,
    CineIconWeight.regular: PhosphorRegular.flame,
    CineIconWeight.fill: PhosphorFill.flame,
  },
  CineIconRole.streakShort: {
    CineIconWeight.light: CineGlyphs.flame1Light,
    CineIconWeight.regular: CineGlyphs.flame1Regular,
    CineIconWeight.fill: CineGlyphs.flame1Fill,
  },
  CineIconRole.streakLong: {
    CineIconWeight.light: CineGlyphs.flame3Light,
    CineIconWeight.regular: CineGlyphs.flame3Regular,
    CineIconWeight.fill: CineGlyphs.flame3Fill,
  },
  CineIconRole.ageGate: {
    CineIconWeight.light: CineGlyphs.certificate18Light,
    CineIconWeight.regular: CineGlyphs.certificate18Regular,
    CineIconWeight.fill: CineGlyphs.certificate18Fill,
  },
  CineIconRole.voiceCast: {
    CineIconWeight.light: CineGlyphs.voice31Light,
    CineIconWeight.regular: CineGlyphs.voice31Regular,
    CineIconWeight.fill: CineGlyphs.voice31Fill,
  },
  CineIconRole.annual: {
    CineIconWeight.light: CineGlyphs.annualLight,
    CineIconWeight.regular: CineGlyphs.annualRegular,
    CineIconWeight.fill: CineGlyphs.annualFill,
  },
  CineIconRole.highlighter: {
    CineIconWeight.light: CineGlyphs.highlighterLight,
    CineIconWeight.regular: CineGlyphs.highlighterRegular,
    CineIconWeight.fill: CineGlyphs.highlighterFill,
  },
  CineIconRole.brandMark: {
    CineIconWeight.light: CineGlyphs.mmMarkLight,
    CineIconWeight.regular: CineGlyphs.mmMarkRegular,
    CineIconWeight.fill: CineGlyphs.mmMarkFill,
  },
};
