// GENERATED by design/build.mjs from design/contract.json — do not edit.
// ignore_for_file: type=lint

import 'dart:convert';

enum ScreenId {
  setup('setup', '/setup'),
  login('login', '/login'),
  register('register', '/register'),
  profiles('profiles', '/profiles'),
  profileNew('profileNew', '/profiles/new'),
  profileEdit('profileEdit', '/profiles/:id/edit'),
  profilesManage('profilesManage', '/profiles/manage'),
  onboarding('onboarding', '/welcome'),
  tonight('tonight', '/'),
  library('library', '/library'),
  updates('updates', '/updates'),
  collections('collections', '/library/collections'),
  collection('collection', '/library/collections/:id'),
  history('history', '/library/history'),
  bookmarks('bookmarks', '/library/bookmarks'),
  picks('picks', '/library/recommendations'),
  numbers('numbers', '/library/statistics'),
  annual('annual', '/library/statistics/annual/:year'),
  featureByFollow('featureByFollow', '/library/:followedId'),
  feature('feature', '/sources/:sourceId/series/:seriesKey'),
  recap('recap', '/recap/:sourceId/:seriesKey'),
  circle('circle', '/circle'),
  circleMember('circleMember', '/circle/:profileId'),
  discover('discover', '/search'),
  sources('sources', '/sources'),
  source('source', '/sources/:sourceId'),
  reader('reader', '/reader/:sourceId/:seriesKey/:chapterKey'),
  readAll('readAll', '/read-all/:sourceId/:seriesKey'),
  novel('novel', '/novels/:sourceId/:seriesKey/:chapterKey'),
  downloads('downloads', '/downloads'),
  dialogue('dialogue', '/ocr'),
  indexHub('index', '/more'),
  settings('settings', '/settings'),
  status('status', '/admin/status'),
  readerLanding('readerLanding', '/reader');

  const ScreenId(this.id, this.path);

  final String id;
  final String path;
}

/// Route patterns and encoding builders (cinematic/DESIGN.md §8.0.3). Path segments go through
/// Uri.encodeComponent; the query is WHATWG form-encoded like the web's URLSearchParams, in the
/// map's insertion order, with null values skipped.
abstract final class Routes {
  static const setupPattern = '/setup';
  static String setup([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(setupPattern, const [], query);
  }
  
  static const loginPattern = '/login';
  static String login([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(loginPattern, const [], query);
  }
  
  static const registerPattern = '/register';
  static String register([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(registerPattern, const [], query);
  }
  
  static const profilesPattern = '/profiles';
  static String profiles([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(profilesPattern, const [], query);
  }
  
  static const profileNewPattern = '/profiles/new';
  static const List<String> profileNewAliases = ['/profiles/create'];
  static String profileNew([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(profileNewPattern, const [], query);
  }
  
  static const profileEditPattern = '/profiles/:id/edit';
  static const List<String> profileEditAliases = ['/profiles/edit/:id'];
  static String profileEdit(Object id, [Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(profileEditPattern, [id], query);
  }
  
  static const profilesManagePattern = '/profiles/manage';
  static String profilesManage([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(profilesManagePattern, const [], query);
  }
  
  static const onboardingPattern = '/welcome';
  static String onboarding([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'step', 'sheet', 'view'}));
    return _build(onboardingPattern, const [], query);
  }
  
  static const tonightPattern = '/';
  static String tonight([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(tonightPattern, const [], query);
  }
  
  static const libraryPattern = '/library';
  static const List<String> libraryAliases = ['/library/browse'];
  static String library([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'q', 'status', 'sort', 'fav', 'view', 'select', 'tab', 'reading_status', 'tags', 'sheet'}));
    return _build(libraryPattern, const [], query);
  }
  
  static const updatesPattern = '/updates';
  static String updates([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'tab', 'sheet', 'view'}));
    return _build(updatesPattern, const [], query);
  }
  
  static const collectionsPattern = '/library/collections';
  static const List<String> collectionsAliases = ['/collections'];
  static String collections([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(collectionsPattern, const [], query);
  }
  
  static const collectionPattern = '/library/collections/:id';
  static const List<String> collectionAliases = ['/collections/:id'];
  static String collection(Object id, [Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(collectionPattern, [id], query);
  }
  
  static const historyPattern = '/library/history';
  static String history([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(historyPattern, const [], query);
  }
  
  static const bookmarksPattern = '/library/bookmarks';
  static String bookmarks([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'source', 'series', 'sheet', 'view'}));
    return _build(bookmarksPattern, const [], query);
  }
  
  static const picksPattern = '/library/recommendations';
  static String picks([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'genre', 'sheet', 'view'}));
    return _build(picksPattern, const [], query);
  }
  
  static const numbersPattern = '/library/statistics';
  static String numbers([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'range', 'year', 'sheet', 'view'}));
    return _build(numbersPattern, const [], query);
  }
  
  static const annualPattern = '/library/statistics/annual/:year';
  static String annual(Object year, [Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(annualPattern, [year], query);
  }
  
  static const featureByFollowPattern = '/library/:followedId';
  static String featureByFollow(Object followedId, [Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(featureByFollowPattern, [followedId], query);
  }
  
  static const featurePattern = '/sources/:sourceId/series/:seriesKey';
  static String feature(Object sourceId, Object seriesKey, [Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(featurePattern, [sourceId, seriesKey], query);
  }
  
  static const recapPattern = '/recap/:sourceId/:seriesKey';
  static String recap(Object sourceId, Object seriesKey, Map<String, Object?> query) {
    assert(_known(query, const {'to', 'scope', 'sheet', 'view'}));
    assert(query['to'] != null);
    return _build(recapPattern, [sourceId, seriesKey], query);
  }
  
  static const circlePattern = '/circle';
  static String circle([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'tab', 'sheet', 'view'}));
    return _build(circlePattern, const [], query);
  }
  
  static const circleMemberPattern = '/circle/:profileId';
  static String circleMember(Object profileId, [Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(circleMemberPattern, [profileId], query);
  }
  
  static const discoverPattern = '/search';
  static String discover([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'q', 'scope', 'sheet', 'view'}));
    return _build(discoverPattern, const [], query);
  }
  
  static const sourcesPattern = '/sources';
  static String sources([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(sourcesPattern, const [], query);
  }
  
  static const sourcePattern = '/sources/:sourceId';
  static String source(Object sourceId, [Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'mode', 'genre', 'q', 'sheet', 'view'}));
    return _build(sourcePattern, [sourceId], query);
  }
  
  static const readerPattern = '/reader/:sourceId/:seriesKey/:chapterKey';
  static const List<String> readerAliases = ['/library/read/:sourceId/:seriesKey/:chapterKey', '/sources/:sourceId/series/:seriesKey/chapters/:chapterKey/read'];
  static String reader(Object sourceId, Object seriesKey, Object chapterKey, [Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'page', 'at', 'all', 'sheet', 'view'}));
    return _build(readerPattern, [sourceId, seriesKey, chapterKey], query);
  }
  
  static const readAllPattern = '/read-all/:sourceId/:seriesKey';
  static String readAll(Object sourceId, Object seriesKey, [Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'from', 'page', 'at', 'sheet', 'view'}));
    return _build(readAllPattern, [sourceId, seriesKey], query);
  }
  
  static const novelPattern = '/novels/:sourceId/:seriesKey/:chapterKey';
  static const List<String> novelAliases = ['/novels/read/:sourceId/:seriesKey/:chapterKey'];
  static String novel(Object sourceId, Object seriesKey, Object chapterKey, [Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'page', 'para', 'at', 'listen', 'sheet', 'view'}));
    return _build(novelPattern, [sourceId, seriesKey, chapterKey], query);
  }
  
  static const downloadsPattern = '/downloads';
  static String downloads([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'tab', 'sheet', 'view'}));
    return _build(downloadsPattern, const [], query);
  }
  
  static const dialoguePattern = '/ocr';
  static const List<String> dialogueAliases = ['/ocr/search'];
  static String dialogue([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'q', 'sheet', 'view'}));
    return _build(dialoguePattern, const [], query);
  }
  
  static const indexHubPattern = '/more';
  static String indexHub([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(indexHubPattern, const [], query);
  }
  
  static const settingsPattern = '/settings';
  static const List<String> settingsAliases = ['/settings/:section'];
  static String settings([SettingsSection? section, Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return section == null ? _build(settingsPattern, const [], query) : _build('/settings/:section', [section.slug], query);
  }
  
  static const statusPattern = '/admin/status';
  static String status([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(statusPattern, const [], query);
  }
  
  static const readerLandingPattern = '/reader';
  static const readerLandingRedirect = '/library';
  static String readerLanding([Map<String, Object?> query = const {}]) {
    assert(_known(query, const {'sheet', 'view'}));
    return _build(readerLandingPattern, const [], query);
  }
  
  static bool _known(Map<String, Object?> query, Set<String> names) => query.keys.every(names.contains);

  static String _build(String pattern, List<Object> params, Map<String, Object?> query) {
    var i = 0;
    final path = pattern.replaceAllMapped(RegExp(r':[A-Za-z]+'), (_) => Uri.encodeComponent(params[i++].toString()));
    final qs = [
      for (final e in query.entries)
        if (e.value != null) '${_formEncode(e.key)}=${_formEncode(e.value.toString())}',
    ].join('&');
    return qs.isEmpty ? path : '$path?$qs';
  }

  /// application/x-www-form-urlencoded exactly as URLSearchParams writes it: UTF-8 bytes,
  /// A-Z a-z 0-9 * - . _ kept, space as +, every other byte %XX. (Uri(queryParameters:) differs:
  /// it keeps ~ and encodes *.)
  static String _formEncode(String s) {
    final out = StringBuffer();
    for (final b in utf8.encode(s)) {
      if ((b >= 0x30 && b <= 0x39) || (b >= 0x41 && b <= 0x5A) || (b >= 0x61 && b <= 0x7A) || b == 0x2A || b == 0x2D || b == 0x2E || b == 0x5F) {
        out.writeCharCode(b);
      } else if (b == 0x20) {
        out.write('+');
      } else {
        out.write('%${b.toRadixString(16).toUpperCase().padLeft(2, '0')}');
      }
    }
    return out.toString();
  }
}

enum SettingsSection {
  profile('profile'),
  appearance('appearance'),
  readingManga('reading-manga'),
  readingNovels('reading-novels'),
  listen('listen'),
  ambient('ambient'),
  storage('storage'),
  content('content'),
  circle('circle'),
  feedback('feedback'),
  notifications('notifications'),
  keyboard('keyboard'),
  server('server'),
  admin('admin'),
  diagnostics('diagnostics'),
  about('about'),
  ai('ai'),
  security('security'),
  members('members'),
  backup('backup');

  const SettingsSection(this.slug);

  final String slug;
}

abstract final class SheetIds {
  static const chapters = 'chapters';
  static const settings = 'settings';
  static const contents = 'contents';
  static const type = 'type';
  static const voices = 'voices';
  static const cast = 'cast';
  static const player = 'player';
  static const soundscape = 'soundscape';
  static const note = 'note';
  static const saveFiles = 'save-files';
  static const tags = 'tags';
  static const recommend = 'recommend';
  static const audiobook = 'audiobook';
  static const howItWorks = 'how-it-works';
  static const offer = 'offer';
  static const image = 'image';
  static const moveSource = 'move-source';
  static const filters = 'filters';
  static const manageTags = 'manage-tags';
  static const collectionNew = 'collection-new';
  static const collectionEdit = 'collection-edit';
  static const collectionShare = 'collection-share';
  static const addSeries = 'add-series';
  static const run = 'run';
  static const whatsNew = 'whats-new';
  static const appUpdate = 'app-update';
  static const shortcuts = 'shortcuts';
  static const licenses = 'licenses';
  static const letterNote = 'letter-note';

  static const List<String> all = [chapters, settings, contents, type, voices, cast, player, soundscape, note, saveFiles, tags, recommend, audiobook, howItWorks, offer, image, moveSource, filters, manageTags, collectionNew, collectionEdit, collectionShare, addSeries, run, whatsNew, appUpdate, shortcuts, licenses, letterNote];
}

abstract final class Flags {
  static const bool glassAvailable = false;
}

enum HapticEvent {
  tapPrimary('tap.primary'),
  tapSecondary('tap.secondary'),
  toggleOn('toggle.on'),
  toggleOff('toggle.off'),
  select('select'),
  navChange('nav.change'),
  longpressOpen('longpress.open'),
  sheetDetent('sheet.detent'),
  sheetDismiss('sheet.dismiss'),
  refreshArm('refresh.arm'),
  refreshFire('refresh.fire'),
  followAdd('follow.add'),
  followRemove('follow.remove'),
  favorite('favorite'),
  bookmarkAdd('bookmark.add'),
  downloadStart('download.start'),
  downloadDone('download.done'),
  downloadFail('download.fail'),
  deleteConfirm('delete.confirm'),
  undo('undo'),
  readerEnter('reader.enter'),
  pageTurn('page.turn'),
  scrubTick('scrub.tick'),
  scrubBoundary('scrub.boundary'),
  chapterComplete('chapter.complete'),
  chapterNext('chapter.next'),
  autoscrollToggle('autoscroll.toggle'),
  autoscrollStep('autoscroll.step'),
  autoscrollEnd('autoscroll.end'),
  zoomSnap('zoom.snap'),
  listenToggle('listen.toggle'),
  voiceAssign('voice.assign'),
  sleepFade('sleep.fade'),
  streakExtend('streak.extend'),
  streakMilestone('streak.milestone'),
  recapCountdownEnd('recap.countdown.end'),
  annualPage('annual.page'),
  shareExport('share.export'),
  reactionSend('reaction.send'),
  recommendSend('recommend.send'),
  gateConfirm('gate.confirm'),
  splashImpress('splash.impress'),
  profileSelect('profile.select'),
  skinSwitch('skin.switch'),
  readerUnlock('reader.unlock'),
  success('success'),
  error('error'),
  navScrub('nav.scrub'),
  navReselect('nav.reselect'),
  navPush('nav.push'),
  navPop('nav.pop'),
  navRoot('nav.root'),
  stackOpen('stack.open'),
  stackPick('stack.pick'),
  detentTick('detent.tick'),
  detentMagnet('detent.magnet'),
  detentLimit('detent.limit'),
  pressLift('press.lift'),
  throwCommit('throw.commit'),
  motionCatch('motion.catch'),
  magnetCapture('magnet.capture'),
  magnetDrop('magnet.drop'),
  reorderLift('reorder.lift'),
  reorderPass('reorder.pass'),
  reorderDrop('reorder.drop'),
  sheetPass('sheet.pass'),
  thresholdCross('threshold.cross'),
  thresholdBack('threshold.back'),
  refreshDone('refresh.done'),
  holdRamp('hold.ramp'),
  holdDone('hold.done'),
  chapterArm('chapter.arm'),
  chapterSeam('chapter.seam'),
  zoomLimit('zoom.limit'),
  panelStep('panel.step'),
  ocrHit('ocr.hit'),
  autoscrollStart('autoscroll.start'),
  voiceCenter('voice.center'),
  recapReady('recap.ready'),
  goalMet('goal.met'),
  shareLift('share.lift'),
  shareFlip('share.flip'),
  reactionBloom('reaction.bloom'),
  reactionCross('reaction.cross'),
  logoLand('logo.land'),
  logoSettle('logo.settle'),
  logoReduced('logo.reduced'),
  annualPodium('annual.podium'),
  annualSummary('annual.summary'),
  warning('warning');

  const HapticEvent(this.id);

  final String id;
}

enum SoundEvent {
  tapPrimary('tap.primary'),
  toggleOn('toggle.on'),
  toggleOff('toggle.off'),
  select('select'),
  navChange('nav.change'),
  followAdd('follow.add'),
  favorite('favorite'),
  bookmarkAdd('bookmark.add'),
  downloadDone('download.done'),
  downloadFail('download.fail'),
  undo('undo'),
  readerEnter('reader.enter'),
  pageTurn('page.turn'),
  refreshArm('refresh.arm'),
  scrubBoundary('scrub.boundary'),
  chapterComplete('chapter.complete'),
  chapterNext('chapter.next'),
  autoscrollToggle('autoscroll.toggle'),
  voiceAssign('voice.assign'),
  streakExtend('streak.extend'),
  streakMilestone('streak.milestone'),
  annualPage('annual.page'),
  shareExport('share.export'),
  reactionSend('reaction.send'),
  recommendSend('recommend.send'),
  gateConfirm('gate.confirm'),
  skinSwitch('skin.switch'),
  readerUnlock('reader.unlock'),
  error('error'),
  sheetOpen('sheet.open'),
  splashReveal('splash.reveal'),
  detentTick('detent.tick'),
  sheetPass('sheet.pass'),
  scrubTick('scrub.tick'),
  navScrub('nav.scrub'),
  sheetClose('sheet.close'),
  navPush('nav.push'),
  navPop('nav.pop'),
  navRoot('nav.root'),
  stackOpen('stack.open'),
  logoLand('logo.land'),
  throwCommit('throw.commit'),
  motionCatch('motion.catch'),
  magnetCapture('magnet.capture'),
  recapReady('recap.ready'),
  magnetDrop('magnet.drop'),
  annualPodium('annual.podium'),
  holdDone('hold.done'),
  goalMet('goal.met'),
  annualSummary('annual.summary'),
  shareFlip('share.flip'),
  logoSettle('logo.settle');

  const SoundEvent(this.id);

  final String id;
}
