// GENERATED by design/build.mjs from design/tokens/*.json — do not edit.
// ignore_for_file: type=lint

import 'package:flutter/material.dart';
import 'package:flutter/physics.dart';

/// A spring token {ms, bounce}. Motion's visual duration maps to Flutter through ms × flutterScale,
/// so the stiffness matches Motion's (cinematic/DESIGN.md §2.8.4, S13).
class SpringToken {
  const SpringToken({required this.ms, required this.bounce, this.flutterScale = 1.2});

  final int ms;
  final double bounce;
  final double flutterScale;

  SpringDescription get description =>
      SpringDescription.withDurationAndBounce(duration: Duration(milliseconds: (ms * flutterScale).round()), bounce: bounce);
}

/// A curve with its own duration (the stack's {ms, bezier} form).
class CurveToken {
  const CurveToken({required this.ms, required this.curve});

  final int ms;
  final Curve curve;

  Duration get duration => Duration(milliseconds: ms);
}

/// Stagger spacings in ms (cinematic/DESIGN.md §4.6).
class MotionStagger {
  const MotionStagger({this.item, this.row, this.cap, this.startDelay, this.fade});

  final int? item;
  final int? row;
  final int? cap;
  final int? startDelay;
  final int? fade;
}

class GridSpec {
  const GridSpec({required this.columns, required this.margin, required this.gutter, this.max = double.infinity});

  final int columns;
  final double margin;
  final double gutter;
  final double max;
}

/// Thick rule, gap, thin rule, stacked top to bottom.
class OxfordRule {
  const OxfordRule({required this.thick, required this.gap, required this.thin, required this.color});

  final double thick;
  final double gap;
  final double thin;
  final Color color;

  double get height => thick + gap + thin;
}

/// One step of a haptic value: play [pattern] [afterMs] after the previous step, optionally
/// repeating every [repeatEveryMs] up to [maxRepeats] times.
class HapticStep {
  const HapticStep({required this.pattern, this.afterMs = 0, this.repeatEveryMs, this.maxRepeats});

  final String pattern;
  final int afterMs;
  final int? repeatEveryMs;
  final int? maxRepeats;
}

/// One AHAP event: type 'T' (transient) or 'C' (continuous); times in seconds.
class AhapEvent {
  const AhapEvent({required this.type, required this.time, this.duration, required this.intensity, required this.sharpness});

  final String type;
  final double time;
  final double? duration;
  final double intensity;
  final double sharpness;
}

class FocusRingSpec {
  const FocusRingSpec({required this.width, required this.offset, required this.color, this.innerColor, this.innerWidth, this.glow, this.glowColor});

  final double width;
  final double offset;
  final Color color;
  final Color? innerColor;
  final double? innerWidth;
  final double? glow;
  final Color? glowColor;
}

/// Reproduces a CSS radial-gradient ellipse of rx × width by ry × height centred at (cx, cy) of the
/// box: a RadialGradient's radius is a fraction of the shortest side, so scale it per axis.
class CssEllipse extends GradientTransform {
  const CssEllipse({required this.rx, required this.ry, this.cx = 0.5, this.cy = 0.5});

  final double rx;
  final double ry;
  final double cx;
  final double cy;

  @override
  Matrix4 transform(Rect bounds, {TextDirection? textDirection}) {
    final s = bounds.shortestSide;
    final px = bounds.left + cx * bounds.width;
    final py = bounds.top + cy * bounds.height;
    return Matrix4.translationValues(px, py, 0)
        .multiplied(Matrix4.diagonal3Values(rx * bounds.width / s, ry * bounds.height / s, 1))
        .multiplied(Matrix4.translationValues(-px, -py, 0));
  }
}
