// GENERATED from the settings index table of the mobile/39 prompt (no `design/glass-settings-index.json` exists yet).
// When web/39 lands that JSON, `node design/build.mjs` regenerates this file and this header is replaced.

/// Where a setting shows (glass 8.25): `apps` is ios and android.
enum SettingsPlatforms { all, apps, web, android }

/// One entry per row of glass 8.25.1 to 8.25.16 (glass 8.25): `{id, label, keywords[], section, platforms, admin}`.
class SettingsIndexEntry {
  const SettingsIndexEntry(this.id, this.label, this.section, this.platforms, this.admin, this.keywords);

  final String id, label, section;
  final SettingsPlatforms platforms;
  final bool admin;
  final List<String> keywords;
}

const List<SettingsIndexEntry> kSettingsIndex = [
  SettingsIndexEntry('skin', 'Skin', 'appearance', SettingsPlatforms.all, false, ['theme', 'edition', 'cinematic', 'glass', 'look']),
  SettingsIndexEntry('solid-glass', 'Solid glass', 'appearance', SettingsPlatforms.all, false, ['transparency', 'blur', 'opaque']),
  SettingsIndexEntry('increase-contrast', 'Increase contrast', 'appearance', SettingsPlatforms.all, false, ['contrast', 'borders', 'accessibility']),
  SettingsIndexEntry('legible-text', 'Legible text', 'appearance', SettingsPlatforms.all, false, ['font', 'atkinson', 'dyslexia', 'readable']),
  SettingsIndexEntry('reduce-motion', 'Reduce motion in this app', 'appearance', SettingsPlatforms.all, false, ['animation', 'motion', 'accessibility']),
  SettingsIndexEntry('screen-reader-mode', 'Screen reader mode', 'appearance', SettingsPlatforms.web, false, ['voiceover', 'talkback', 'accessibility']),
  SettingsIndexEntry('light-follows-device', 'Light follows the device', 'appearance', SettingsPlatforms.all, false, ['tilt', 'motion', 'specular']),
  SettingsIndexEntry('app-icon-follows-skin', 'App icon follows the skin', 'appearance', SettingsPlatforms.apps, false, ['icon', 'home screen']),
  SettingsIndexEntry('reader-direction', 'Direction', 'reading-manga', SettingsPlatforms.all, false, ['left to right', 'right to left', 'vertical', 'rtl']),
  SettingsIndexEntry('reader-brightness', 'Brightness', 'reading-manga', SettingsPlatforms.all, false, ['dim', 'light']),
  SettingsIndexEntry('reader-warmth', 'Warmth', 'reading-manga', SettingsPlatforms.all, false, ['night', 'amber', 'blue light']),
  SettingsIndexEntry('reader-fit', 'Fit', 'reading-manga', SettingsPlatforms.all, false, ['width', 'height', 'original', 'zoom']),
  SettingsIndexEntry('reader-tap-zones', 'Tap zones', 'reading-manga', SettingsPlatforms.all, false, ['taps', 'left', 'right', 'menu']),
  SettingsIndexEntry('reader-chapters', 'Chapters', 'reading-manga', SettingsPlatforms.all, false, ['continuous', 'one at a time']),
  SettingsIndexEntry('reader-page-gap', 'Page gap', 'reading-manga', SettingsPlatforms.all, false, ['gap', 'spacing', 'strip']),
  SettingsIndexEntry('reader-cinema', 'Cinema mode by default', 'reading-manga', SettingsPlatforms.all, false, ['immersive', 'hide controls']),
  SettingsIndexEntry('reader-keep-awake', 'Keep screen awake', 'reading-manga', SettingsPlatforms.apps, false, ['sleep', 'screen', 'wake']),
  SettingsIndexEntry('reader-auto-next', 'Auto next chapter', 'reading-manga', SettingsPlatforms.all, false, ['next', 'continue']),
  SettingsIndexEntry('reader-lock', 'Lock reader controls', 'reading-manga', SettingsPlatforms.all, false, ['lock', 'taps', 'unlock']),
  SettingsIndexEntry('reader-volume-keys', 'Volume keys turn pages', 'reading-manga', SettingsPlatforms.android, false, ['volume', 'buttons']),
  SettingsIndexEntry('reader-refresh-rate', 'Refresh rate', 'reading-manga', SettingsPlatforms.android, false, ['120', 'hz', 'smooth', 'fps']),
  SettingsIndexEntry('reader-reset', 'Reset reader settings', 'reading-manga', SettingsPlatforms.all, false, ['defaults', 'restore', 'reset']),
  SettingsIndexEntry('novel-face', 'Reading face', 'reading-novels', SettingsPlatforms.all, false, ['font', 'literata', 'sans', 'atkinson']),
  SettingsIndexEntry('novel-size', 'Text size', 'reading-novels', SettingsPlatforms.all, false, ['font size', 'bigger', 'smaller']),
  SettingsIndexEntry('novel-line-height', 'Line height', 'reading-novels', SettingsPlatforms.all, false, ['leading', 'spacing']),
  SettingsIndexEntry('novel-measure', 'Measure', 'reading-novels', SettingsPlatforms.all, false, ['column', 'width', 'line length']),
  SettingsIndexEntry('novel-paper', 'Paper', 'reading-novels', SettingsPlatforms.all, false, ['background', 'sepia', 'colour']),
  SettingsIndexEntry('novel-mode', 'Scroll or paged', 'reading-novels', SettingsPlatforms.all, false, ['pages', 'scroll', 'layout']),
  SettingsIndexEntry('novel-page-turn', 'Page turn', 'reading-novels', SettingsPlatforms.all, false, ['slide', 'lift', 'fade']),
  SettingsIndexEntry('listen-speed', 'Default speed', 'listen', SettingsPlatforms.all, false, ['narration', 'playback', 'rate']),
  SettingsIndexEntry('listen-continue', 'Continue to the next chapter', 'listen', SettingsPlatforms.all, false, ['autoplay', 'next']),
  SettingsIndexEntry('listen-sleep', 'Sleep timer default', 'listen', SettingsPlatforms.all, false, ['sleep', 'timer']),
  SettingsIndexEntry('listen-shake', 'Shake to extend', 'listen', SettingsPlatforms.apps, false, ['shake', 'sleep timer']),
  SettingsIndexEntry('ambient-page-tint', 'Page-tinted chrome', 'ambient', SettingsPlatforms.all, false, ['colour', 'tint', 'dynamic']),
  SettingsIndexEntry('ambient-cruise', 'Cruise default speed', 'ambient', SettingsPlatforms.all, false, ['auto-scroll', 'autoscroll', 'speed']),
  SettingsIndexEntry('ambient-guided', 'Guided view by default', 'ambient', SettingsPlatforms.all, false, ['panels', 'panel by panel']),
  SettingsIndexEntry('ambient-soundscape', 'Soundscape defaults', 'ambient', SettingsPlatforms.all, false, ['ambience', 'rain', 'sound']),
  SettingsIndexEntry('mature-content', 'Show 18+ content', 'content', SettingsPlatforms.all, false, ['adult', 'mature', 'nsfw', 'gate']),
  SettingsIndexEntry('haptics', 'Haptics', 'feedback', SettingsPlatforms.apps, false, ['vibration', 'taptic']),
  SettingsIndexEntry('haptics-feel', 'Feel it', 'feedback', SettingsPlatforms.apps, false, ['test', 'vibration']),
  SettingsIndexEntry('ui-sounds', 'UI sounds', 'feedback', SettingsPlatforms.all, false, ['clicks', 'sound effects']),
  SettingsIndexEntry('ui-sounds-volume', 'UI sounds volume', 'feedback', SettingsPlatforms.all, false, ['loudness']),
  SettingsIndexEntry('ui-sounds-hear', 'Hear it', 'feedback', SettingsPlatforms.all, false, ['preview', 'test']),
  SettingsIndexEntry('soundscape-scene', 'Soundscape', 'feedback', SettingsPlatforms.all, false, ['ambience', 'rain', 'wind', 'ocean']),
  SettingsIndexEntry('soundscape-match', 'Match the story', 'feedback', SettingsPlatforms.all, false, ['genre', 'automatic']),
  SettingsIndexEntry('soundscape-mix', 'Soundscape mix', 'feedback', SettingsPlatforms.all, false, ['bed', 'detail', 'tone']),
  SettingsIndexEntry('soundscape-volume', 'Soundscape volume', 'feedback', SettingsPlatforms.all, false, ['loudness']),
  SettingsIndexEntry('soundscape-lower', 'Lower under narration', 'feedback', SettingsPlatforms.all, false, ['duck', 'listen']),
  SettingsIndexEntry('updates-schedule', 'Update checks', 'notifications', SettingsPlatforms.all, true, ['last check', 'next check']),
  SettingsIndexEntry('updates-auto', 'Check for new chapters automatically', 'notifications', SettingsPlatforms.all, true, ['updates', 'background']),
  SettingsIndexEntry('updates-startup', 'Check when the server starts', 'notifications', SettingsPlatforms.all, true, ['startup']),
  SettingsIndexEntry('updates-notify', 'Notify me about new chapters', 'notifications', SettingsPlatforms.all, true, ['notifications', 'alerts']),
  SettingsIndexEntry('updates-interval', 'Check interval', 'notifications', SettingsPlatforms.all, true, ['minutes', 'frequency']),
  SettingsIndexEntry('catalogue-cache', 'Source catalogue cache', 'notifications', SettingsPlatforms.all, true, ['cache', 'ttl']),
  SettingsIndexEntry('change-password', 'Change password', 'security', SettingsPlatforms.all, false, ['password']),
  SettingsIndexEntry('sessions', 'Where you\'re signed in', 'security', SettingsPlatforms.all, false, ['devices', 'sessions', 'sign out']),
  SettingsIndexEntry('sign-out-everywhere', 'Sign out everywhere', 'security', SettingsPlatforms.all, false, ['revoke', 'devices']),
  SettingsIndexEntry('members', 'Members', 'members', SettingsPlatforms.all, true, ['accounts', 'users', 'deactivate', 'delete']),
  SettingsIndexEntry('storage', 'Storage', 'storage', SettingsPlatforms.all, false, ['downloads', 'space', 'cache']),
  SettingsIndexEntry('backup-nightly', 'Nightly backup', 'backup', SettingsPlatforms.all, true, ['backup status']),
  SettingsIndexEntry('backup-export', 'Export backup', 'backup', SettingsPlatforms.all, true, ['download database']),
  SettingsIndexEntry('backup-restore', 'Restore from a backup', 'backup', SettingsPlatforms.all, true, ['import', 'restore']),
  SettingsIndexEntry('server-url', 'API base URL', 'server', SettingsPlatforms.apps, false, ['server', 'address', 'url']),
  SettingsIndexEntry('diag-rendering', 'Rendering performance', 'diagnostics', SettingsPlatforms.all, false, ['fps', 'jank', 'frames']),
  SettingsIndexEntry('diag-display', 'Display', 'diagnostics', SettingsPlatforms.apps, false, ['refresh rate', 'resolution']),
  SettingsIndexEntry('diag-device', 'Device', 'diagnostics', SettingsPlatforms.all, false, ['version', 'build']),
  SettingsIndexEntry('diag-image-cache', 'Image cache', 'diagnostics', SettingsPlatforms.apps, false, ['memory', 'images']),
  SettingsIndexEntry('diag-glass', 'Glass renderer', 'diagnostics', SettingsPlatforms.all, false, ['impeller', 'refraction', 'layers']),
  SettingsIndexEntry('diag-motion-timings', 'Show motion timings', 'diagnostics', SettingsPlatforms.all, false, ['animation', 'debug']),
  SettingsIndexEntry('diag-calibration', 'Glass calibration', 'diagnostics', SettingsPlatforms.all, false, ['checkerboard', 'debug']),
  SettingsIndexEntry('diag-preview-glass', 'Preview Glass skin', 'diagnostics', SettingsPlatforms.all, false, ['debug', 'skin']),
  SettingsIndexEntry('shortcuts', 'Keyboard shortcuts', 'keyboard', SettingsPlatforms.all, false, ['keys', 'hotkeys']),
  SettingsIndexEntry('single-key-shortcuts', 'Single-key shortcuts', 'keyboard', SettingsPlatforms.all, false, ['keys', 'letters']),
  SettingsIndexEntry('account', 'Account', 'profile', SettingsPlatforms.all, false, ['username', 'name']),
  SettingsIndexEntry('profiles', 'Profiles', 'profile', SettingsPlatforms.all, false, ['manage profiles', 'add profile']),
  SettingsIndexEntry('sign-out', 'Sign out', 'profile', SettingsPlatforms.all, false, ['log out']),
  SettingsIndexEntry('app-updates', 'Updates', 'about', SettingsPlatforms.all, false, ['version', 'update', 'sidestore', 'apk']),
  SettingsIndexEntry('whats-new', 'What\'s New', 'about', SettingsPlatforms.all, false, ['changelog', 'release notes']),
  SettingsIndexEntry('licences', 'Open-source licences', 'about', SettingsPlatforms.all, false, ['licenses', 'credits', 'fonts']),
  SettingsIndexEntry('share-reading', 'Share what I\'m reading', 'circle', SettingsPlatforms.all, false, ['sharing', 'activity', 'privacy']),
  SettingsIndexEntry('show-reactions', 'Show my reactions', 'circle', SettingsPlatforms.all, false, ['reactions']),
  SettingsIndexEntry('accept-recommendations', 'Accept recommendations', 'circle', SettingsPlatforms.all, false, ['letters', 'recommend']),
  SettingsIndexEntry('show-presence', 'Show me in presence', 'circle', SettingsPlatforms.all, false, ['reading now', 'online']),
  SettingsIndexEntry('shared-shelves', 'Let others add me to shared shelves', 'circle', SettingsPlatforms.all, false, ['collections', 'shelves']),
  SettingsIndexEntry('share-streak', 'Share my streak', 'circle', SettingsPlatforms.all, false, ['streak', 'flame']),
  SettingsIndexEntry('include-mature-activity', 'Include 18+ titles in my activity', 'circle', SettingsPlatforms.all, false, ['adult', 'mature']),
  SettingsIndexEntry('hidden-from-circle', 'Hidden from my Circle', 'circle', SettingsPlatforms.all, false, ['hide', 'exclude']),
  SettingsIndexEntry('clear-activity', 'Clear my activity', 'circle', SettingsPlatforms.all, false, ['delete', 'history']),
  SettingsIndexEntry('previously-on', 'Previously on', 'ai', SettingsPlatforms.all, false, ['recap', 'summary']),
  SettingsIndexEntry('recap-skip', 'Series you asked not to recap', 'ai', SettingsPlatforms.all, false, ['recap', 'skip']),
  SettingsIndexEntry('clear-not-interested', 'Clear "Not interested"', 'ai', SettingsPlatforms.all, false, ['reset', 'picks']),
  SettingsIndexEntry('ai-status', 'AI status', 'ai', SettingsPlatforms.all, false, ['availability', 'asks']),
];
