// GENERATED by brand/build-glyphs.mjs from design/icons.json and brand/glass/glyphs — do not edit.
// Strings only: web/01 imports the named components from "@phosphor-icons/react/ssr".

export const ICON_ROLES = {
  back: { kind: "phosphor", name: "caret-left", component: "CaretLeftIcon" },
  "back-depth": { kind: "glyph", name: "strata" },
  close: { kind: "phosphor", name: "x", component: "XIcon" },
  search: { kind: "phosphor", name: "magnifying-glass", component: "MagnifyingGlassIcon" },
  home: { kind: "phosphor", name: "house-simple", component: "HouseSimpleIcon" },
  library: { kind: "phosphor", name: "books", component: "BooksIcon" },
  updates: { kind: "phosphor", name: "bell-simple", component: "BellSimpleIcon" },
  sources: { kind: "phosphor", name: "globe-hemisphere-west", component: "GlobeHemisphereWestIcon" },
  bookmark: { kind: "phosphor", name: "bookmark-simple", component: "BookmarkSimpleIcon" },
  stats: { kind: "phosphor", name: "chart-bar", component: "ChartBarIcon" },
  circle: { kind: "phosphor", name: "users-three", component: "UsersThreeIcon" },
  settings: { kind: "phosphor", name: "gear-six", component: "GearSixIcon" },
  status: { kind: "phosphor", name: "pulse", component: "PulseIcon" },
  picks: { kind: "phosphor", name: "sparkle", component: "SparkleIcon" },
  "dialogue-search": { kind: "glyph", name: "bubble-search" },
  "reader-settings": { kind: "phosphor", name: "sliders-horizontal", component: "SlidersHorizontalIcon" },
  type: { kind: "phosphor", name: "text-aa", component: "TextAaIcon" },
  contents: { kind: "phosphor", name: "list-numbers", component: "ListNumbersIcon" },
  listen: { kind: "phosphor", name: "headphones", component: "HeadphonesIcon" },
  play: { kind: "phosphor", name: "play", component: "PlayIcon" },
  pause: { kind: "phosphor", name: "pause", component: "PauseIcon" },
  "chapter-previous": { kind: "phosphor", name: "skip-back", component: "SkipBackIcon" },
  "chapter-next": { kind: "phosphor", name: "skip-forward", component: "SkipForwardIcon" },
  download: { kind: "phosphor", name: "cloud-arrow-down", component: "CloudArrowDownIcon" },
  downloaded: { kind: "glyph", name: "droplet" },
  pin: { kind: "phosphor", name: "push-pin", component: "PushPinIcon" },
  favourite: { kind: "phosphor", name: "star", component: "StarIcon" },
  follow: { kind: "phosphor", name: "plus", component: "PlusIcon" },
  following: { kind: "phosphor", name: "check", component: "CheckIcon" },
  notify: { kind: "phosphor", name: "bell-ringing", component: "BellRingingIcon" },
  share: { kind: "phosphor", name: "export", component: "ExportIcon" },
  recommend: { kind: "phosphor", name: "paper-plane-tilt", component: "PaperPlaneTiltIcon" },
  filter: { kind: "phosphor", name: "funnel-simple", component: "FunnelSimpleIcon" },
  sort: { kind: "phosphor", name: "arrows-down-up", component: "ArrowsDownUpIcon" },
  select: { kind: "phosphor", name: "check-circle", component: "CheckCircleIcon" },
  delete: { kind: "phosphor", name: "trash-simple", component: "TrashSimpleIcon" },
  edit: { kind: "phosphor", name: "pencil-simple", component: "PencilSimpleIcon" },
  overflow: { kind: "phosphor", name: "dots-three", component: "DotsThreeIcon" },
  brightness: { kind: "phosphor", name: "sun", component: "SunIcon" },
  warmth: { kind: "phosphor", name: "thermometer-simple", component: "ThermometerSimpleIcon" },
  offline: { kind: "phosphor", name: "wifi-slash", component: "WifiSlashIcon" },
  refresh: { kind: "phosphor", name: "arrow-clockwise", component: "ArrowClockwiseIcon" },
  external: { kind: "phosphor", name: "arrow-square-out", component: "ArrowSquareOutIcon" },
  soundscape: { kind: "phosphor", name: "waveform", component: "WaveformIcon" },
  "auto-scroll": { kind: "glyph", name: "flywheel" },
  "strip-mode": { kind: "glyph", name: "strip-scroll" },
  "guided-view": { kind: "glyph", name: "panel-focus" },
  flame: { kind: "phosphor", name: "flame", component: "FlameIcon" },
  "age-gate": { kind: "glyph", name: "age-gate" },
  "voice-cast": { kind: "glyph", name: "voice-31" },
  "brand-mark": { kind: "glyph", name: "mm-mark" },
  "ai-unavailable": { kind: "glyph", name: "sparkle-slash" },
} as const;

export type IconRole = keyof typeof ICON_ROLES;

export const ICON_RULES = {
  phosphorWeights: [
    "regular",
    "duotone",
    "fill",
    "light",
    "bold",
    "thin"
  ],
  glyphWeights: [
    "regular",
    "duotone",
    "fill"
  ],
  glyphFallback: {
    light: "regular",
    bold: "fill",
    thin: "regular"
  },
  rules: {
    default: "regular",
    active: "duotone",
    pressed: "fill",
    inline: "regular",
    ornamental: "light",
    dense: "bold",
    reaction: "fill"
  },
  sizes: {
    default: 22,
    inline: 20,
    ornamentalMin: 48,
    ornamentalMax: 64,
    denseMin: 14,
    denseMax: 16,
    reactionStrip: 24,
    reactionPicker: 36
  },
  hit: {
    coarse: 44,
    android: 48
  },
  duotoneSecondaryOpacity: 0.2
} as const;
