// GENERATED by brand/cinematic/export.mjs — do not edit
// ignore_for_file: type=lint
import 'dart:ui';

abstract final class CineMarkPaths {
  static const Size canvas = Size(1024, 1024);
  static Path upright() => Path()..moveTo(349.14, 637.03)..lineTo(257.66, 386.97)..lineTo(318.04, 386.97)..lineTo(379.57, 550.83)..lineTo(437.32, 386.97)..lineTo(437.81, 386.97)..lineTo(350.29, 637.03)..close()..moveTo(257.99, 386.97)..lineTo(257.99, 633.08)..lineTo(283.66, 633.08)..lineTo(283.66, 633.74)..lineTo(233.65, 633.74)..lineTo(233.65, 633.08)..lineTo(257.34, 633.08)..lineTo(257.34, 387.63)..lineTo(232, 387.63)..lineTo(232, 386.97)..close()..moveTo(520.73, 386.97)..lineTo(520.73, 387.63)..lineTo(497.7, 387.63)..lineTo(497.7, 633.08)..lineTo(520.73, 633.08)..lineTo(520.73, 633.74)..lineTo(411.16, 633.74)..lineTo(411.16, 633.08)..lineTo(437.48, 633.08)..lineTo(437.48, 386.97)..close();
  static Path italic() => Path()..moveTo(571.05, 637.03)..lineTo(532.23, 386.97)..lineTo(592.61, 386.97)..lineTo(619.75, 551.48)..lineTo(711.88, 386.97)..lineTo(712.54, 386.97)..lineTo(572.37, 637.03)..close()..moveTo(457.21, 633.74)..lineTo(457.21, 633.08)..lineTo(509.69, 633.08)..lineTo(509.69, 633.74)..close()..moveTo(479.25, 633.74)..lineTo(531.9, 387.63)..lineTo(506.56, 387.63)..lineTo(506.56, 386.97)..lineTo(532.56, 386.97)..lineTo(479.91, 633.74)..close()..moveTo(636.53, 633.74)..lineTo(636.53, 633.08)..lineTo(745.94, 633.08)..lineTo(745.94, 633.74)..close()..moveTo(659.56, 633.74)..lineTo(712.21, 386.97)..lineTo(792, 386.97)..lineTo(792, 387.63)..lineTo(771.93, 387.63)..lineTo(719.61, 633.74)..close();
  static Path intersection() => Path.combine(PathOperation.intersect, upright(), italic());
}
