// GENERATED by design/build.mjs from design/tokens/cinematic.json — do not edit.
// ignore_for_file: type=lint

/// The named moves of the motion table; each label is what the motion-timings overlay prints.
enum MotionName {
  cut('CUT'),
  set('SET'),
  folioFlip('FOLIO FLIP'),
  page('PAGE'),
  matchCut('MATCH CUT'),
  dip('DIP'),
  columnWipe('COLUMN WIPE'),
  iris('IRIS'),
  insert('INSERT'),
  rise('RISE'),
  dissolve('DISSOLVE'),
  rackFocus('RACK FOCUS'),
  develop('DEVELOP'),
  drift('DRIFT'),
  flicker('FLICKER'),
  ruleDraw('RULE DRAW'),
  letterSet('LETTER SET'),
  type('TYPE'),
  trailerScrub('TRAILER SCRUB'),
  cutToHome('CUT TO HOME'),
  lightbox('LIGHTBOX'),
  arm('ARM'),
  countdown('COUNTDOWN'),
  voicePulse('VOICE PULSE'),
  ignite('IGNITE'),
  flame('FLAME'),
  dolly('DOLLY'),
  unseal('UNSEAL'),
  creditsRoll('CREDITS ROLL'),
  ruleSlide('RULE SLIDE'),
  panel('PANEL'),
  slate('SLATE'),
  paddlePage('PADDLE PAGE'),
  unfold('UNFOLD'),
  leaderDraw('LEADER DRAW'),
  highlightSweep('HIGHLIGHT SWEEP'),
  stopThePress('STOP THE PRESS'),
  credits('CREDITS');

  const MotionName(this.label);

  final String label;
}
