// GENERATED by design/build.mjs from design/tokens/cinematic.json — do not edit.
// ignore_for_file: type=lint

import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:manhwamaniacs/skins/contract.g.dart';
import 'package:manhwamaniacs/skins/token_types.g.dart';

class CineTokens extends ThemeExtension<CineTokens> {
  const CineTokens({
    required this.colorPaper0,
    required this.colorPaper1,
    required this.colorPaper2,
    required this.colorPaper3,
    required this.colorPaper4,
    required this.colorRule1,
    required this.colorRule2,
    required this.colorInk30,
    required this.colorInk45,
    required this.colorInk60,
    required this.colorInk80,
    required this.colorInk100,
    required this.colorSpot,
    required this.colorSpotPress,
    required this.colorSpotWash,
    required this.colorSpotGlow,
    required this.colorProof,
    required this.colorProofPress,
    required this.colorProofWash,
    required this.colorSet,
    required this.colorInfo,
    required this.colorNote,
    required this.colorOnart,
    required this.colorHairlineArt,
    required this.colorGalley,
    required this.colorLeaderSweep,
    required this.colorLightbox,
    required this.colorMatteGuided,
    required this.colorWarmth,
    required this.colorAmbientFallbackDuo,
    required this.colorAmbientFallbackTint,
    required this.colorAmbientFallbackInk,
    required this.colorMoodRomantic,
    required this.colorMoodAction,
    required this.colorMoodComedy,
    required this.colorMoodHorror,
    required this.colorMoodSliceOfLife,
    required this.colorMoodFantasy,
    required this.colorSpeaker1,
    required this.colorSpeaker2,
    required this.colorSpeaker3,
    required this.colorSpeaker4,
    required this.colorSpeaker5,
    required this.colorSpeaker6,
    required this.colorSpeaker7,
    required this.colorSpeaker8,
    required this.colorSpeaker9,
    required this.colorSpeaker10,
    required this.colorStockNitratePage,
    required this.colorStockNitrateInk,
    required this.colorStockNitrateMuted,
    required this.colorStockInkPage,
    required this.colorStockInkInk,
    required this.colorStockInkMuted,
    required this.colorStockSepiaNightPage,
    required this.colorStockSepiaNightInk,
    required this.colorStockSepiaNightMuted,
    required this.colorStockDuskPage,
    required this.colorStockDuskInk,
    required this.colorStockDuskMuted,
    required this.colorStockMossPage,
    required this.colorStockMossInk,
    required this.colorStockMossMuted,
    required this.colorStockRosewoodPage,
    required this.colorStockRosewoodInk,
    required this.colorStockRosewoodMuted,
    required this.colorGroundBlack,
    required this.colorGroundInk,
    required this.colorGroundSlate,
    required this.colorAvatarViolet,
    required this.colorAvatarCyan,
    required this.colorAvatarRose,
    required this.colorAvatarAmber,
    required this.colorAvatarEmerald,
    required this.colorAvatarEmber,
    required this.colorAvatarBlade,
    required this.colorAvatarPhantom,
    required this.colorAvatarArcane,
    required this.colorAvatarLunar,
    required this.colorAvatarStar,
    required this.colorAvatarReader,
    required this.space0,
    required this.space1,
    required this.space2,
    required this.space3,
    required this.space4,
    required this.space5,
    required this.space6,
    required this.space8,
    required this.space10,
    required this.space12,
    required this.space16,
    required this.space20,
    required this.space24,
    required this.space32,
    required this.gridPhone,
    required this.gridTablet,
    required this.gridDesktop,
    required this.gridWide,
    required this.gridCinema,
    required this.bpTablet,
    required this.bpFrame,
    required this.bpDesktop,
    required this.bpWide,
    required this.bpCinema,
    required this.radius0,
    required this.radiusRound,
    required this.blurLetter,
    required this.blurRack,
    required this.blurBleed,
    required this.blurCard,
    required this.blurDefocus,
    required this.hitMin,
    required this.hitAndroid,
    required this.hitFine,
    required this.ruleHair,
    required this.ruleStrong,
    required this.ruleInk,
    required this.ruleHeavy,
    required this.ruleSpot,
    required this.ruleProof,
    required this.ruleOxford,
    required this.focusWidth,
    required this.focusOffset,
    required this.focusHalo,
    required this.zPage,
    required this.zSticky,
    required this.zChrome,
    required this.zPanel,
    required this.zSheet,
    required this.zDialog,
    required this.zToast,
    required this.zLightbox,
    required this.zShutter,
    required this.zDebug,
    required this.scrimGutter,
    required this.scrimFootBlack,
    required this.scrimRailEnd,
    required this.scrimVignette,
    required this.scrimModal,
    required this.durCut,
    required this.durTick,
    required this.durBeat,
    required this.durLine,
    required this.durColumn,
    required this.durSpread,
    required this.durWipeClose,
    required this.durWipeOpen,
    required this.durDissolve,
    required this.durReel,
    required this.durDrift,
    required this.durType,
    required this.durCaret,
    required this.durLetter,
    required this.durLetterBlur,
    required this.durHoldToast,
    required this.durHoldToastError,
    required this.durHoldToastAction,
    required this.durHoldToastUndo,
    required this.durHoldRating,
    required this.durHoldPanelBase,
    required this.durHoldPanelWord,
    required this.durHoldPanelCap,
    required this.durHoldDip,
    required this.durHoldError,
    required this.durHoldGlance,
    required this.durHoldSuccess,
    required this.durHoldConnected,
    required this.durHoldChip,
    required this.durHoldFlash,
    required this.durHoldBrief,
    required this.durHoldEdition,
    required this.durHoldAnnualPage,
    required this.durHoldAnnualList,
    required this.durDwellPreview,
    required this.durDwellBackdrop,
    required this.durFlicker,
    required this.durArm,
    required this.durCountdownRecap,
    required this.durCountdownNext,
    required this.durSampleTint,
    required this.durPageturn,
    required this.durSnap,
    required this.durReduced,
    required this.durClip,
    required this.durPageOut,
    required this.durDim,
    required this.durTapscroll,
    required this.durMatchBack,
    required this.durRise,
    required this.durGlide,
    required this.durStoppress,
    required this.durRack,
    required this.durIrisOut,
    required this.durLoopRule,
    required this.durLoopPreview,
    required this.durFlameFlicker,
    required this.durFlameRisk,
    required this.durFlameRing,
    required this.durFlameSpark,
    required this.durFadeFirst,
    required this.durFadeCut,
    required this.durFadeHint,
    required this.durLeader,
    required this.durRollColophon,
    required this.easeSettle,
    required this.easeLift,
    required this.easeTurn,
    required this.easeSet,
    required this.easeDrift,
    required this.easeScroll,
    required this.easeLinear,
    required this.springRelease,
    required this.springSheet,
    required this.springScrub,
    required this.scalarStaggerGrid,
    required this.scalarStaggerList,
    required this.scalarStaggerLetter,
    required this.scalarStaggerWord,
    required this.scalarStaggerFly,
    required this.scalarLetterRise,
    required this.scalarRubber,
    required this.scalarPaceTop,
    required this.scalarPaceWords,
    required this.scalarPaceMin,
    required this.scalarPaceMax,
    required this.typeCover,
    required this.typeMasthead,
    required this.typeHeadline,
    required this.typeSection,
    required this.typeSubhead,
    required this.typeNumeral,
    required this.typePull,
    required this.typeField,
    required this.typeDeck,
    required this.typeBody,
    required this.typeBodyItalic,
    required this.typeTitle,
    required this.typeUi,
    required this.typeLabel,
    required this.typeKicker,
    required this.typeCredit,
    required this.typeCreditLabel,
    required this.typeNav,
    required this.typeCaption,
    required this.typeFolio,
    required this.typeFolioLg,
    required this.typeMicro,
    required this.fontDisplay,
    required this.fontGrotesk,
    required this.fontText,
    required this.fontFolio,
    required this.fontLiterata,
    required this.fontSourceSerif,
    required this.fontAtkinson,
  });

  final Color colorPaper0;
  final Color colorPaper1;
  final Color colorPaper2;
  final Color colorPaper3;
  final Color colorPaper4;
  final Color colorRule1;
  final Color colorRule2;
  final Color colorInk30;
  final Color colorInk45;
  final Color colorInk60;
  final Color colorInk80;
  final Color colorInk100;
  final Color colorSpot;
  final Color colorSpotPress;
  final Color colorSpotWash;
  final Color colorSpotGlow;
  final Color colorProof;
  final Color colorProofPress;
  final Color colorProofWash;
  final Color colorSet;
  final Color colorInfo;
  final Color colorNote;
  final Color colorOnart;
  final Color colorHairlineArt;
  final Color colorGalley;
  final Color colorLeaderSweep;
  final Color colorLightbox;
  final Color colorMatteGuided;
  final Color colorWarmth;
  final Color colorAmbientFallbackDuo;
  final Color colorAmbientFallbackTint;
  final Color colorAmbientFallbackInk;
  final Color colorMoodRomantic;
  final Color colorMoodAction;
  final Color colorMoodComedy;
  final Color colorMoodHorror;
  final Color colorMoodSliceOfLife;
  final Color colorMoodFantasy;
  final Color colorSpeaker1;
  final Color colorSpeaker2;
  final Color colorSpeaker3;
  final Color colorSpeaker4;
  final Color colorSpeaker5;
  final Color colorSpeaker6;
  final Color colorSpeaker7;
  final Color colorSpeaker8;
  final Color colorSpeaker9;
  final Color colorSpeaker10;
  final Color colorStockNitratePage;
  final Color colorStockNitrateInk;
  final Color colorStockNitrateMuted;
  final Color colorStockInkPage;
  final Color colorStockInkInk;
  final Color colorStockInkMuted;
  final Color colorStockSepiaNightPage;
  final Color colorStockSepiaNightInk;
  final Color colorStockSepiaNightMuted;
  final Color colorStockDuskPage;
  final Color colorStockDuskInk;
  final Color colorStockDuskMuted;
  final Color colorStockMossPage;
  final Color colorStockMossInk;
  final Color colorStockMossMuted;
  final Color colorStockRosewoodPage;
  final Color colorStockRosewoodInk;
  final Color colorStockRosewoodMuted;
  final Color colorGroundBlack;
  final Color colorGroundInk;
  final Color colorGroundSlate;
  final Color colorAvatarViolet;
  final Color colorAvatarCyan;
  final Color colorAvatarRose;
  final Color colorAvatarAmber;
  final Color colorAvatarEmerald;
  final Color colorAvatarEmber;
  final Color colorAvatarBlade;
  final Color colorAvatarPhantom;
  final Color colorAvatarArcane;
  final Color colorAvatarLunar;
  final Color colorAvatarStar;
  final Color colorAvatarReader;
  final double space0;
  final double space1;
  final double space2;
  final double space3;
  final double space4;
  final double space5;
  final double space6;
  final double space8;
  final double space10;
  final double space12;
  final double space16;
  final double space20;
  final double space24;
  final double space32;
  final GridSpec gridPhone;
  final GridSpec gridTablet;
  final GridSpec gridDesktop;
  final GridSpec gridWide;
  final GridSpec gridCinema;
  final double bpTablet;
  final double bpFrame;
  final double bpDesktop;
  final double bpWide;
  final double bpCinema;
  final double radius0;
  final double radiusRound;
  final double blurLetter;
  final double blurRack;
  final double blurBleed;
  final double blurCard;
  final double blurDefocus;
  final double hitMin;
  final double hitAndroid;
  final double hitFine;
  final BorderSide ruleHair;
  final BorderSide ruleStrong;
  final BorderSide ruleInk;
  final BorderSide ruleHeavy;
  final BorderSide ruleSpot;
  final BorderSide ruleProof;
  final OxfordRule ruleOxford;
  final double focusWidth;
  final double focusOffset;
  final double focusHalo;
  final int zPage;
  final int zSticky;
  final int zChrome;
  final int zPanel;
  final int zSheet;
  final int zDialog;
  final int zToast;
  final int zLightbox;
  final int zShutter;
  final int zDebug;
  final LinearGradient scrimGutter;
  final LinearGradient scrimFootBlack;
  final LinearGradient scrimRailEnd;
  final RadialGradient scrimVignette;
  final Color scrimModal;
  final Duration durCut;
  final Duration durTick;
  final Duration durBeat;
  final Duration durLine;
  final Duration durColumn;
  final Duration durSpread;
  final Duration durWipeClose;
  final Duration durWipeOpen;
  final Duration durDissolve;
  final Duration durReel;
  final Duration durDrift;
  final Duration durType;
  final Duration durCaret;
  final Duration durLetter;
  final Duration durLetterBlur;
  final Duration durHoldToast;
  final Duration durHoldToastError;
  final Duration durHoldToastAction;
  final Duration durHoldToastUndo;
  final Duration durHoldRating;
  final Duration durHoldPanelBase;
  final Duration durHoldPanelWord;
  final Duration durHoldPanelCap;
  final Duration durHoldDip;
  final Duration durHoldError;
  final Duration durHoldGlance;
  final Duration durHoldSuccess;
  final Duration durHoldConnected;
  final Duration durHoldChip;
  final Duration durHoldFlash;
  final Duration durHoldBrief;
  final Duration durHoldEdition;
  final Duration durHoldAnnualPage;
  final Duration durHoldAnnualList;
  final Duration durDwellPreview;
  final Duration durDwellBackdrop;
  final Duration durFlicker;
  final Duration durArm;
  final Duration durCountdownRecap;
  final Duration durCountdownNext;
  final Duration durSampleTint;
  final Duration durPageturn;
  final Duration durSnap;
  final Duration durReduced;
  final Duration durClip;
  final Duration durPageOut;
  final Duration durDim;
  final Duration durTapscroll;
  final Duration durMatchBack;
  final Duration durRise;
  final Duration durGlide;
  final Duration durStoppress;
  final Duration durRack;
  final Duration durIrisOut;
  final Duration durLoopRule;
  final Duration durLoopPreview;
  final Duration durFlameFlicker;
  final Duration durFlameRisk;
  final Duration durFlameRing;
  final Duration durFlameSpark;
  final Duration durFadeFirst;
  final Duration durFadeCut;
  final Duration durFadeHint;
  final Duration durLeader;
  final Duration durRollColophon;
  final Curve easeSettle;
  final Curve easeLift;
  final Curve easeTurn;
  final Curve easeSet;
  final Curve easeDrift;
  final Curve easeScroll;
  final Curve easeLinear;
  final SpringToken springRelease;
  final SpringToken springSheet;
  final SpringToken springScrub;
  final MotionStagger scalarStaggerGrid;
  final MotionStagger scalarStaggerList;
  final MotionStagger scalarStaggerLetter;
  final MotionStagger scalarStaggerWord;
  final MotionStagger scalarStaggerFly;
  final double scalarLetterRise;
  final double scalarRubber;
  final double scalarPaceTop;
  final double scalarPaceWords;
  final double scalarPaceMin;
  final double scalarPaceMax;
  final CineTextRole typeCover;
  final CineTextRole typeMasthead;
  final CineTextRole typeHeadline;
  final CineTextRole typeSection;
  final CineTextRole typeSubhead;
  final CineTextRole typeNumeral;
  final CineTextRole typePull;
  final CineTextRole typeField;
  final CineTextRole typeDeck;
  final CineTextRole typeBody;
  final CineTextRole typeBodyItalic;
  final CineTextRole typeTitle;
  final CineTextRole typeUi;
  final CineTextRole typeLabel;
  final CineTextRole typeKicker;
  final CineTextRole typeCredit;
  final CineTextRole typeCreditLabel;
  final CineTextRole typeNav;
  final CineTextRole typeCaption;
  final CineTextRole typeFolio;
  final CineTextRole typeFolioLg;
  final CineTextRole typeMicro;
  final String fontDisplay;
  final String fontGrotesk;
  final String fontText;
  final String fontFolio;
  final String fontLiterata;
  final String fontSourceSerif;
  final String fontAtkinson;

  @override
  CineTokens copyWith({
    Color? colorPaper0,
    Color? colorPaper1,
    Color? colorPaper2,
    Color? colorPaper3,
    Color? colorPaper4,
    Color? colorRule1,
    Color? colorRule2,
    Color? colorInk30,
    Color? colorInk45,
    Color? colorInk60,
    Color? colorInk80,
    Color? colorInk100,
    Color? colorSpot,
    Color? colorSpotPress,
    Color? colorSpotWash,
    Color? colorSpotGlow,
    Color? colorProof,
    Color? colorProofPress,
    Color? colorProofWash,
    Color? colorSet,
    Color? colorInfo,
    Color? colorNote,
    Color? colorOnart,
    Color? colorHairlineArt,
    Color? colorGalley,
    Color? colorLeaderSweep,
    Color? colorLightbox,
    Color? colorMatteGuided,
    Color? colorWarmth,
    Color? colorAmbientFallbackDuo,
    Color? colorAmbientFallbackTint,
    Color? colorAmbientFallbackInk,
    Color? colorMoodRomantic,
    Color? colorMoodAction,
    Color? colorMoodComedy,
    Color? colorMoodHorror,
    Color? colorMoodSliceOfLife,
    Color? colorMoodFantasy,
    Color? colorSpeaker1,
    Color? colorSpeaker2,
    Color? colorSpeaker3,
    Color? colorSpeaker4,
    Color? colorSpeaker5,
    Color? colorSpeaker6,
    Color? colorSpeaker7,
    Color? colorSpeaker8,
    Color? colorSpeaker9,
    Color? colorSpeaker10,
    Color? colorStockNitratePage,
    Color? colorStockNitrateInk,
    Color? colorStockNitrateMuted,
    Color? colorStockInkPage,
    Color? colorStockInkInk,
    Color? colorStockInkMuted,
    Color? colorStockSepiaNightPage,
    Color? colorStockSepiaNightInk,
    Color? colorStockSepiaNightMuted,
    Color? colorStockDuskPage,
    Color? colorStockDuskInk,
    Color? colorStockDuskMuted,
    Color? colorStockMossPage,
    Color? colorStockMossInk,
    Color? colorStockMossMuted,
    Color? colorStockRosewoodPage,
    Color? colorStockRosewoodInk,
    Color? colorStockRosewoodMuted,
    Color? colorGroundBlack,
    Color? colorGroundInk,
    Color? colorGroundSlate,
    Color? colorAvatarViolet,
    Color? colorAvatarCyan,
    Color? colorAvatarRose,
    Color? colorAvatarAmber,
    Color? colorAvatarEmerald,
    Color? colorAvatarEmber,
    Color? colorAvatarBlade,
    Color? colorAvatarPhantom,
    Color? colorAvatarArcane,
    Color? colorAvatarLunar,
    Color? colorAvatarStar,
    Color? colorAvatarReader,
    double? space0,
    double? space1,
    double? space2,
    double? space3,
    double? space4,
    double? space5,
    double? space6,
    double? space8,
    double? space10,
    double? space12,
    double? space16,
    double? space20,
    double? space24,
    double? space32,
    GridSpec? gridPhone,
    GridSpec? gridTablet,
    GridSpec? gridDesktop,
    GridSpec? gridWide,
    GridSpec? gridCinema,
    double? bpTablet,
    double? bpFrame,
    double? bpDesktop,
    double? bpWide,
    double? bpCinema,
    double? radius0,
    double? radiusRound,
    double? blurLetter,
    double? blurRack,
    double? blurBleed,
    double? blurCard,
    double? blurDefocus,
    double? hitMin,
    double? hitAndroid,
    double? hitFine,
    BorderSide? ruleHair,
    BorderSide? ruleStrong,
    BorderSide? ruleInk,
    BorderSide? ruleHeavy,
    BorderSide? ruleSpot,
    BorderSide? ruleProof,
    OxfordRule? ruleOxford,
    double? focusWidth,
    double? focusOffset,
    double? focusHalo,
    int? zPage,
    int? zSticky,
    int? zChrome,
    int? zPanel,
    int? zSheet,
    int? zDialog,
    int? zToast,
    int? zLightbox,
    int? zShutter,
    int? zDebug,
    LinearGradient? scrimGutter,
    LinearGradient? scrimFootBlack,
    LinearGradient? scrimRailEnd,
    RadialGradient? scrimVignette,
    Color? scrimModal,
    Duration? durCut,
    Duration? durTick,
    Duration? durBeat,
    Duration? durLine,
    Duration? durColumn,
    Duration? durSpread,
    Duration? durWipeClose,
    Duration? durWipeOpen,
    Duration? durDissolve,
    Duration? durReel,
    Duration? durDrift,
    Duration? durType,
    Duration? durCaret,
    Duration? durLetter,
    Duration? durLetterBlur,
    Duration? durHoldToast,
    Duration? durHoldToastError,
    Duration? durHoldToastAction,
    Duration? durHoldToastUndo,
    Duration? durHoldRating,
    Duration? durHoldPanelBase,
    Duration? durHoldPanelWord,
    Duration? durHoldPanelCap,
    Duration? durHoldDip,
    Duration? durHoldError,
    Duration? durHoldGlance,
    Duration? durHoldSuccess,
    Duration? durHoldConnected,
    Duration? durHoldChip,
    Duration? durHoldFlash,
    Duration? durHoldBrief,
    Duration? durHoldEdition,
    Duration? durHoldAnnualPage,
    Duration? durHoldAnnualList,
    Duration? durDwellPreview,
    Duration? durDwellBackdrop,
    Duration? durFlicker,
    Duration? durArm,
    Duration? durCountdownRecap,
    Duration? durCountdownNext,
    Duration? durSampleTint,
    Duration? durPageturn,
    Duration? durSnap,
    Duration? durReduced,
    Duration? durClip,
    Duration? durPageOut,
    Duration? durDim,
    Duration? durTapscroll,
    Duration? durMatchBack,
    Duration? durRise,
    Duration? durGlide,
    Duration? durStoppress,
    Duration? durRack,
    Duration? durIrisOut,
    Duration? durLoopRule,
    Duration? durLoopPreview,
    Duration? durFlameFlicker,
    Duration? durFlameRisk,
    Duration? durFlameRing,
    Duration? durFlameSpark,
    Duration? durFadeFirst,
    Duration? durFadeCut,
    Duration? durFadeHint,
    Duration? durLeader,
    Duration? durRollColophon,
    Curve? easeSettle,
    Curve? easeLift,
    Curve? easeTurn,
    Curve? easeSet,
    Curve? easeDrift,
    Curve? easeScroll,
    Curve? easeLinear,
    SpringToken? springRelease,
    SpringToken? springSheet,
    SpringToken? springScrub,
    MotionStagger? scalarStaggerGrid,
    MotionStagger? scalarStaggerList,
    MotionStagger? scalarStaggerLetter,
    MotionStagger? scalarStaggerWord,
    MotionStagger? scalarStaggerFly,
    double? scalarLetterRise,
    double? scalarRubber,
    double? scalarPaceTop,
    double? scalarPaceWords,
    double? scalarPaceMin,
    double? scalarPaceMax,
    CineTextRole? typeCover,
    CineTextRole? typeMasthead,
    CineTextRole? typeHeadline,
    CineTextRole? typeSection,
    CineTextRole? typeSubhead,
    CineTextRole? typeNumeral,
    CineTextRole? typePull,
    CineTextRole? typeField,
    CineTextRole? typeDeck,
    CineTextRole? typeBody,
    CineTextRole? typeBodyItalic,
    CineTextRole? typeTitle,
    CineTextRole? typeUi,
    CineTextRole? typeLabel,
    CineTextRole? typeKicker,
    CineTextRole? typeCredit,
    CineTextRole? typeCreditLabel,
    CineTextRole? typeNav,
    CineTextRole? typeCaption,
    CineTextRole? typeFolio,
    CineTextRole? typeFolioLg,
    CineTextRole? typeMicro,
    String? fontDisplay,
    String? fontGrotesk,
    String? fontText,
    String? fontFolio,
    String? fontLiterata,
    String? fontSourceSerif,
    String? fontAtkinson,
  }) {
    return CineTokens(
      colorPaper0: colorPaper0 ?? this.colorPaper0,
      colorPaper1: colorPaper1 ?? this.colorPaper1,
      colorPaper2: colorPaper2 ?? this.colorPaper2,
      colorPaper3: colorPaper3 ?? this.colorPaper3,
      colorPaper4: colorPaper4 ?? this.colorPaper4,
      colorRule1: colorRule1 ?? this.colorRule1,
      colorRule2: colorRule2 ?? this.colorRule2,
      colorInk30: colorInk30 ?? this.colorInk30,
      colorInk45: colorInk45 ?? this.colorInk45,
      colorInk60: colorInk60 ?? this.colorInk60,
      colorInk80: colorInk80 ?? this.colorInk80,
      colorInk100: colorInk100 ?? this.colorInk100,
      colorSpot: colorSpot ?? this.colorSpot,
      colorSpotPress: colorSpotPress ?? this.colorSpotPress,
      colorSpotWash: colorSpotWash ?? this.colorSpotWash,
      colorSpotGlow: colorSpotGlow ?? this.colorSpotGlow,
      colorProof: colorProof ?? this.colorProof,
      colorProofPress: colorProofPress ?? this.colorProofPress,
      colorProofWash: colorProofWash ?? this.colorProofWash,
      colorSet: colorSet ?? this.colorSet,
      colorInfo: colorInfo ?? this.colorInfo,
      colorNote: colorNote ?? this.colorNote,
      colorOnart: colorOnart ?? this.colorOnart,
      colorHairlineArt: colorHairlineArt ?? this.colorHairlineArt,
      colorGalley: colorGalley ?? this.colorGalley,
      colorLeaderSweep: colorLeaderSweep ?? this.colorLeaderSweep,
      colorLightbox: colorLightbox ?? this.colorLightbox,
      colorMatteGuided: colorMatteGuided ?? this.colorMatteGuided,
      colorWarmth: colorWarmth ?? this.colorWarmth,
      colorAmbientFallbackDuo: colorAmbientFallbackDuo ?? this.colorAmbientFallbackDuo,
      colorAmbientFallbackTint: colorAmbientFallbackTint ?? this.colorAmbientFallbackTint,
      colorAmbientFallbackInk: colorAmbientFallbackInk ?? this.colorAmbientFallbackInk,
      colorMoodRomantic: colorMoodRomantic ?? this.colorMoodRomantic,
      colorMoodAction: colorMoodAction ?? this.colorMoodAction,
      colorMoodComedy: colorMoodComedy ?? this.colorMoodComedy,
      colorMoodHorror: colorMoodHorror ?? this.colorMoodHorror,
      colorMoodSliceOfLife: colorMoodSliceOfLife ?? this.colorMoodSliceOfLife,
      colorMoodFantasy: colorMoodFantasy ?? this.colorMoodFantasy,
      colorSpeaker1: colorSpeaker1 ?? this.colorSpeaker1,
      colorSpeaker2: colorSpeaker2 ?? this.colorSpeaker2,
      colorSpeaker3: colorSpeaker3 ?? this.colorSpeaker3,
      colorSpeaker4: colorSpeaker4 ?? this.colorSpeaker4,
      colorSpeaker5: colorSpeaker5 ?? this.colorSpeaker5,
      colorSpeaker6: colorSpeaker6 ?? this.colorSpeaker6,
      colorSpeaker7: colorSpeaker7 ?? this.colorSpeaker7,
      colorSpeaker8: colorSpeaker8 ?? this.colorSpeaker8,
      colorSpeaker9: colorSpeaker9 ?? this.colorSpeaker9,
      colorSpeaker10: colorSpeaker10 ?? this.colorSpeaker10,
      colorStockNitratePage: colorStockNitratePage ?? this.colorStockNitratePage,
      colorStockNitrateInk: colorStockNitrateInk ?? this.colorStockNitrateInk,
      colorStockNitrateMuted: colorStockNitrateMuted ?? this.colorStockNitrateMuted,
      colorStockInkPage: colorStockInkPage ?? this.colorStockInkPage,
      colorStockInkInk: colorStockInkInk ?? this.colorStockInkInk,
      colorStockInkMuted: colorStockInkMuted ?? this.colorStockInkMuted,
      colorStockSepiaNightPage: colorStockSepiaNightPage ?? this.colorStockSepiaNightPage,
      colorStockSepiaNightInk: colorStockSepiaNightInk ?? this.colorStockSepiaNightInk,
      colorStockSepiaNightMuted: colorStockSepiaNightMuted ?? this.colorStockSepiaNightMuted,
      colorStockDuskPage: colorStockDuskPage ?? this.colorStockDuskPage,
      colorStockDuskInk: colorStockDuskInk ?? this.colorStockDuskInk,
      colorStockDuskMuted: colorStockDuskMuted ?? this.colorStockDuskMuted,
      colorStockMossPage: colorStockMossPage ?? this.colorStockMossPage,
      colorStockMossInk: colorStockMossInk ?? this.colorStockMossInk,
      colorStockMossMuted: colorStockMossMuted ?? this.colorStockMossMuted,
      colorStockRosewoodPage: colorStockRosewoodPage ?? this.colorStockRosewoodPage,
      colorStockRosewoodInk: colorStockRosewoodInk ?? this.colorStockRosewoodInk,
      colorStockRosewoodMuted: colorStockRosewoodMuted ?? this.colorStockRosewoodMuted,
      colorGroundBlack: colorGroundBlack ?? this.colorGroundBlack,
      colorGroundInk: colorGroundInk ?? this.colorGroundInk,
      colorGroundSlate: colorGroundSlate ?? this.colorGroundSlate,
      colorAvatarViolet: colorAvatarViolet ?? this.colorAvatarViolet,
      colorAvatarCyan: colorAvatarCyan ?? this.colorAvatarCyan,
      colorAvatarRose: colorAvatarRose ?? this.colorAvatarRose,
      colorAvatarAmber: colorAvatarAmber ?? this.colorAvatarAmber,
      colorAvatarEmerald: colorAvatarEmerald ?? this.colorAvatarEmerald,
      colorAvatarEmber: colorAvatarEmber ?? this.colorAvatarEmber,
      colorAvatarBlade: colorAvatarBlade ?? this.colorAvatarBlade,
      colorAvatarPhantom: colorAvatarPhantom ?? this.colorAvatarPhantom,
      colorAvatarArcane: colorAvatarArcane ?? this.colorAvatarArcane,
      colorAvatarLunar: colorAvatarLunar ?? this.colorAvatarLunar,
      colorAvatarStar: colorAvatarStar ?? this.colorAvatarStar,
      colorAvatarReader: colorAvatarReader ?? this.colorAvatarReader,
      space0: space0 ?? this.space0,
      space1: space1 ?? this.space1,
      space2: space2 ?? this.space2,
      space3: space3 ?? this.space3,
      space4: space4 ?? this.space4,
      space5: space5 ?? this.space5,
      space6: space6 ?? this.space6,
      space8: space8 ?? this.space8,
      space10: space10 ?? this.space10,
      space12: space12 ?? this.space12,
      space16: space16 ?? this.space16,
      space20: space20 ?? this.space20,
      space24: space24 ?? this.space24,
      space32: space32 ?? this.space32,
      gridPhone: gridPhone ?? this.gridPhone,
      gridTablet: gridTablet ?? this.gridTablet,
      gridDesktop: gridDesktop ?? this.gridDesktop,
      gridWide: gridWide ?? this.gridWide,
      gridCinema: gridCinema ?? this.gridCinema,
      bpTablet: bpTablet ?? this.bpTablet,
      bpFrame: bpFrame ?? this.bpFrame,
      bpDesktop: bpDesktop ?? this.bpDesktop,
      bpWide: bpWide ?? this.bpWide,
      bpCinema: bpCinema ?? this.bpCinema,
      radius0: radius0 ?? this.radius0,
      radiusRound: radiusRound ?? this.radiusRound,
      blurLetter: blurLetter ?? this.blurLetter,
      blurRack: blurRack ?? this.blurRack,
      blurBleed: blurBleed ?? this.blurBleed,
      blurCard: blurCard ?? this.blurCard,
      blurDefocus: blurDefocus ?? this.blurDefocus,
      hitMin: hitMin ?? this.hitMin,
      hitAndroid: hitAndroid ?? this.hitAndroid,
      hitFine: hitFine ?? this.hitFine,
      ruleHair: ruleHair ?? this.ruleHair,
      ruleStrong: ruleStrong ?? this.ruleStrong,
      ruleInk: ruleInk ?? this.ruleInk,
      ruleHeavy: ruleHeavy ?? this.ruleHeavy,
      ruleSpot: ruleSpot ?? this.ruleSpot,
      ruleProof: ruleProof ?? this.ruleProof,
      ruleOxford: ruleOxford ?? this.ruleOxford,
      focusWidth: focusWidth ?? this.focusWidth,
      focusOffset: focusOffset ?? this.focusOffset,
      focusHalo: focusHalo ?? this.focusHalo,
      zPage: zPage ?? this.zPage,
      zSticky: zSticky ?? this.zSticky,
      zChrome: zChrome ?? this.zChrome,
      zPanel: zPanel ?? this.zPanel,
      zSheet: zSheet ?? this.zSheet,
      zDialog: zDialog ?? this.zDialog,
      zToast: zToast ?? this.zToast,
      zLightbox: zLightbox ?? this.zLightbox,
      zShutter: zShutter ?? this.zShutter,
      zDebug: zDebug ?? this.zDebug,
      scrimGutter: scrimGutter ?? this.scrimGutter,
      scrimFootBlack: scrimFootBlack ?? this.scrimFootBlack,
      scrimRailEnd: scrimRailEnd ?? this.scrimRailEnd,
      scrimVignette: scrimVignette ?? this.scrimVignette,
      scrimModal: scrimModal ?? this.scrimModal,
      durCut: durCut ?? this.durCut,
      durTick: durTick ?? this.durTick,
      durBeat: durBeat ?? this.durBeat,
      durLine: durLine ?? this.durLine,
      durColumn: durColumn ?? this.durColumn,
      durSpread: durSpread ?? this.durSpread,
      durWipeClose: durWipeClose ?? this.durWipeClose,
      durWipeOpen: durWipeOpen ?? this.durWipeOpen,
      durDissolve: durDissolve ?? this.durDissolve,
      durReel: durReel ?? this.durReel,
      durDrift: durDrift ?? this.durDrift,
      durType: durType ?? this.durType,
      durCaret: durCaret ?? this.durCaret,
      durLetter: durLetter ?? this.durLetter,
      durLetterBlur: durLetterBlur ?? this.durLetterBlur,
      durHoldToast: durHoldToast ?? this.durHoldToast,
      durHoldToastError: durHoldToastError ?? this.durHoldToastError,
      durHoldToastAction: durHoldToastAction ?? this.durHoldToastAction,
      durHoldToastUndo: durHoldToastUndo ?? this.durHoldToastUndo,
      durHoldRating: durHoldRating ?? this.durHoldRating,
      durHoldPanelBase: durHoldPanelBase ?? this.durHoldPanelBase,
      durHoldPanelWord: durHoldPanelWord ?? this.durHoldPanelWord,
      durHoldPanelCap: durHoldPanelCap ?? this.durHoldPanelCap,
      durHoldDip: durHoldDip ?? this.durHoldDip,
      durHoldError: durHoldError ?? this.durHoldError,
      durHoldGlance: durHoldGlance ?? this.durHoldGlance,
      durHoldSuccess: durHoldSuccess ?? this.durHoldSuccess,
      durHoldConnected: durHoldConnected ?? this.durHoldConnected,
      durHoldChip: durHoldChip ?? this.durHoldChip,
      durHoldFlash: durHoldFlash ?? this.durHoldFlash,
      durHoldBrief: durHoldBrief ?? this.durHoldBrief,
      durHoldEdition: durHoldEdition ?? this.durHoldEdition,
      durHoldAnnualPage: durHoldAnnualPage ?? this.durHoldAnnualPage,
      durHoldAnnualList: durHoldAnnualList ?? this.durHoldAnnualList,
      durDwellPreview: durDwellPreview ?? this.durDwellPreview,
      durDwellBackdrop: durDwellBackdrop ?? this.durDwellBackdrop,
      durFlicker: durFlicker ?? this.durFlicker,
      durArm: durArm ?? this.durArm,
      durCountdownRecap: durCountdownRecap ?? this.durCountdownRecap,
      durCountdownNext: durCountdownNext ?? this.durCountdownNext,
      durSampleTint: durSampleTint ?? this.durSampleTint,
      durPageturn: durPageturn ?? this.durPageturn,
      durSnap: durSnap ?? this.durSnap,
      durReduced: durReduced ?? this.durReduced,
      durClip: durClip ?? this.durClip,
      durPageOut: durPageOut ?? this.durPageOut,
      durDim: durDim ?? this.durDim,
      durTapscroll: durTapscroll ?? this.durTapscroll,
      durMatchBack: durMatchBack ?? this.durMatchBack,
      durRise: durRise ?? this.durRise,
      durGlide: durGlide ?? this.durGlide,
      durStoppress: durStoppress ?? this.durStoppress,
      durRack: durRack ?? this.durRack,
      durIrisOut: durIrisOut ?? this.durIrisOut,
      durLoopRule: durLoopRule ?? this.durLoopRule,
      durLoopPreview: durLoopPreview ?? this.durLoopPreview,
      durFlameFlicker: durFlameFlicker ?? this.durFlameFlicker,
      durFlameRisk: durFlameRisk ?? this.durFlameRisk,
      durFlameRing: durFlameRing ?? this.durFlameRing,
      durFlameSpark: durFlameSpark ?? this.durFlameSpark,
      durFadeFirst: durFadeFirst ?? this.durFadeFirst,
      durFadeCut: durFadeCut ?? this.durFadeCut,
      durFadeHint: durFadeHint ?? this.durFadeHint,
      durLeader: durLeader ?? this.durLeader,
      durRollColophon: durRollColophon ?? this.durRollColophon,
      easeSettle: easeSettle ?? this.easeSettle,
      easeLift: easeLift ?? this.easeLift,
      easeTurn: easeTurn ?? this.easeTurn,
      easeSet: easeSet ?? this.easeSet,
      easeDrift: easeDrift ?? this.easeDrift,
      easeScroll: easeScroll ?? this.easeScroll,
      easeLinear: easeLinear ?? this.easeLinear,
      springRelease: springRelease ?? this.springRelease,
      springSheet: springSheet ?? this.springSheet,
      springScrub: springScrub ?? this.springScrub,
      scalarStaggerGrid: scalarStaggerGrid ?? this.scalarStaggerGrid,
      scalarStaggerList: scalarStaggerList ?? this.scalarStaggerList,
      scalarStaggerLetter: scalarStaggerLetter ?? this.scalarStaggerLetter,
      scalarStaggerWord: scalarStaggerWord ?? this.scalarStaggerWord,
      scalarStaggerFly: scalarStaggerFly ?? this.scalarStaggerFly,
      scalarLetterRise: scalarLetterRise ?? this.scalarLetterRise,
      scalarRubber: scalarRubber ?? this.scalarRubber,
      scalarPaceTop: scalarPaceTop ?? this.scalarPaceTop,
      scalarPaceWords: scalarPaceWords ?? this.scalarPaceWords,
      scalarPaceMin: scalarPaceMin ?? this.scalarPaceMin,
      scalarPaceMax: scalarPaceMax ?? this.scalarPaceMax,
      typeCover: typeCover ?? this.typeCover,
      typeMasthead: typeMasthead ?? this.typeMasthead,
      typeHeadline: typeHeadline ?? this.typeHeadline,
      typeSection: typeSection ?? this.typeSection,
      typeSubhead: typeSubhead ?? this.typeSubhead,
      typeNumeral: typeNumeral ?? this.typeNumeral,
      typePull: typePull ?? this.typePull,
      typeField: typeField ?? this.typeField,
      typeDeck: typeDeck ?? this.typeDeck,
      typeBody: typeBody ?? this.typeBody,
      typeBodyItalic: typeBodyItalic ?? this.typeBodyItalic,
      typeTitle: typeTitle ?? this.typeTitle,
      typeUi: typeUi ?? this.typeUi,
      typeLabel: typeLabel ?? this.typeLabel,
      typeKicker: typeKicker ?? this.typeKicker,
      typeCredit: typeCredit ?? this.typeCredit,
      typeCreditLabel: typeCreditLabel ?? this.typeCreditLabel,
      typeNav: typeNav ?? this.typeNav,
      typeCaption: typeCaption ?? this.typeCaption,
      typeFolio: typeFolio ?? this.typeFolio,
      typeFolioLg: typeFolioLg ?? this.typeFolioLg,
      typeMicro: typeMicro ?? this.typeMicro,
      fontDisplay: fontDisplay ?? this.fontDisplay,
      fontGrotesk: fontGrotesk ?? this.fontGrotesk,
      fontText: fontText ?? this.fontText,
      fontFolio: fontFolio ?? this.fontFolio,
      fontLiterata: fontLiterata ?? this.fontLiterata,
      fontSourceSerif: fontSourceSerif ?? this.fontSourceSerif,
      fontAtkinson: fontAtkinson ?? this.fontAtkinson,
    );
  }

  @override
  CineTokens lerp(covariant ThemeExtension<CineTokens>? other, double t) {
    if (other is! CineTokens) return this;
    return CineTokens(
      colorPaper0: Color.lerp(colorPaper0, other.colorPaper0, t)!,
      colorPaper1: Color.lerp(colorPaper1, other.colorPaper1, t)!,
      colorPaper2: Color.lerp(colorPaper2, other.colorPaper2, t)!,
      colorPaper3: Color.lerp(colorPaper3, other.colorPaper3, t)!,
      colorPaper4: Color.lerp(colorPaper4, other.colorPaper4, t)!,
      colorRule1: Color.lerp(colorRule1, other.colorRule1, t)!,
      colorRule2: Color.lerp(colorRule2, other.colorRule2, t)!,
      colorInk30: Color.lerp(colorInk30, other.colorInk30, t)!,
      colorInk45: Color.lerp(colorInk45, other.colorInk45, t)!,
      colorInk60: Color.lerp(colorInk60, other.colorInk60, t)!,
      colorInk80: Color.lerp(colorInk80, other.colorInk80, t)!,
      colorInk100: Color.lerp(colorInk100, other.colorInk100, t)!,
      colorSpot: Color.lerp(colorSpot, other.colorSpot, t)!,
      colorSpotPress: Color.lerp(colorSpotPress, other.colorSpotPress, t)!,
      colorSpotWash: Color.lerp(colorSpotWash, other.colorSpotWash, t)!,
      colorSpotGlow: Color.lerp(colorSpotGlow, other.colorSpotGlow, t)!,
      colorProof: Color.lerp(colorProof, other.colorProof, t)!,
      colorProofPress: Color.lerp(colorProofPress, other.colorProofPress, t)!,
      colorProofWash: Color.lerp(colorProofWash, other.colorProofWash, t)!,
      colorSet: Color.lerp(colorSet, other.colorSet, t)!,
      colorInfo: Color.lerp(colorInfo, other.colorInfo, t)!,
      colorNote: Color.lerp(colorNote, other.colorNote, t)!,
      colorOnart: Color.lerp(colorOnart, other.colorOnart, t)!,
      colorHairlineArt: Color.lerp(colorHairlineArt, other.colorHairlineArt, t)!,
      colorGalley: Color.lerp(colorGalley, other.colorGalley, t)!,
      colorLeaderSweep: Color.lerp(colorLeaderSweep, other.colorLeaderSweep, t)!,
      colorLightbox: Color.lerp(colorLightbox, other.colorLightbox, t)!,
      colorMatteGuided: Color.lerp(colorMatteGuided, other.colorMatteGuided, t)!,
      colorWarmth: Color.lerp(colorWarmth, other.colorWarmth, t)!,
      colorAmbientFallbackDuo: Color.lerp(colorAmbientFallbackDuo, other.colorAmbientFallbackDuo, t)!,
      colorAmbientFallbackTint: Color.lerp(colorAmbientFallbackTint, other.colorAmbientFallbackTint, t)!,
      colorAmbientFallbackInk: Color.lerp(colorAmbientFallbackInk, other.colorAmbientFallbackInk, t)!,
      colorMoodRomantic: Color.lerp(colorMoodRomantic, other.colorMoodRomantic, t)!,
      colorMoodAction: Color.lerp(colorMoodAction, other.colorMoodAction, t)!,
      colorMoodComedy: Color.lerp(colorMoodComedy, other.colorMoodComedy, t)!,
      colorMoodHorror: Color.lerp(colorMoodHorror, other.colorMoodHorror, t)!,
      colorMoodSliceOfLife: Color.lerp(colorMoodSliceOfLife, other.colorMoodSliceOfLife, t)!,
      colorMoodFantasy: Color.lerp(colorMoodFantasy, other.colorMoodFantasy, t)!,
      colorSpeaker1: Color.lerp(colorSpeaker1, other.colorSpeaker1, t)!,
      colorSpeaker2: Color.lerp(colorSpeaker2, other.colorSpeaker2, t)!,
      colorSpeaker3: Color.lerp(colorSpeaker3, other.colorSpeaker3, t)!,
      colorSpeaker4: Color.lerp(colorSpeaker4, other.colorSpeaker4, t)!,
      colorSpeaker5: Color.lerp(colorSpeaker5, other.colorSpeaker5, t)!,
      colorSpeaker6: Color.lerp(colorSpeaker6, other.colorSpeaker6, t)!,
      colorSpeaker7: Color.lerp(colorSpeaker7, other.colorSpeaker7, t)!,
      colorSpeaker8: Color.lerp(colorSpeaker8, other.colorSpeaker8, t)!,
      colorSpeaker9: Color.lerp(colorSpeaker9, other.colorSpeaker9, t)!,
      colorSpeaker10: Color.lerp(colorSpeaker10, other.colorSpeaker10, t)!,
      colorStockNitratePage: Color.lerp(colorStockNitratePage, other.colorStockNitratePage, t)!,
      colorStockNitrateInk: Color.lerp(colorStockNitrateInk, other.colorStockNitrateInk, t)!,
      colorStockNitrateMuted: Color.lerp(colorStockNitrateMuted, other.colorStockNitrateMuted, t)!,
      colorStockInkPage: Color.lerp(colorStockInkPage, other.colorStockInkPage, t)!,
      colorStockInkInk: Color.lerp(colorStockInkInk, other.colorStockInkInk, t)!,
      colorStockInkMuted: Color.lerp(colorStockInkMuted, other.colorStockInkMuted, t)!,
      colorStockSepiaNightPage: Color.lerp(colorStockSepiaNightPage, other.colorStockSepiaNightPage, t)!,
      colorStockSepiaNightInk: Color.lerp(colorStockSepiaNightInk, other.colorStockSepiaNightInk, t)!,
      colorStockSepiaNightMuted: Color.lerp(colorStockSepiaNightMuted, other.colorStockSepiaNightMuted, t)!,
      colorStockDuskPage: Color.lerp(colorStockDuskPage, other.colorStockDuskPage, t)!,
      colorStockDuskInk: Color.lerp(colorStockDuskInk, other.colorStockDuskInk, t)!,
      colorStockDuskMuted: Color.lerp(colorStockDuskMuted, other.colorStockDuskMuted, t)!,
      colorStockMossPage: Color.lerp(colorStockMossPage, other.colorStockMossPage, t)!,
      colorStockMossInk: Color.lerp(colorStockMossInk, other.colorStockMossInk, t)!,
      colorStockMossMuted: Color.lerp(colorStockMossMuted, other.colorStockMossMuted, t)!,
      colorStockRosewoodPage: Color.lerp(colorStockRosewoodPage, other.colorStockRosewoodPage, t)!,
      colorStockRosewoodInk: Color.lerp(colorStockRosewoodInk, other.colorStockRosewoodInk, t)!,
      colorStockRosewoodMuted: Color.lerp(colorStockRosewoodMuted, other.colorStockRosewoodMuted, t)!,
      colorGroundBlack: Color.lerp(colorGroundBlack, other.colorGroundBlack, t)!,
      colorGroundInk: Color.lerp(colorGroundInk, other.colorGroundInk, t)!,
      colorGroundSlate: Color.lerp(colorGroundSlate, other.colorGroundSlate, t)!,
      colorAvatarViolet: Color.lerp(colorAvatarViolet, other.colorAvatarViolet, t)!,
      colorAvatarCyan: Color.lerp(colorAvatarCyan, other.colorAvatarCyan, t)!,
      colorAvatarRose: Color.lerp(colorAvatarRose, other.colorAvatarRose, t)!,
      colorAvatarAmber: Color.lerp(colorAvatarAmber, other.colorAvatarAmber, t)!,
      colorAvatarEmerald: Color.lerp(colorAvatarEmerald, other.colorAvatarEmerald, t)!,
      colorAvatarEmber: Color.lerp(colorAvatarEmber, other.colorAvatarEmber, t)!,
      colorAvatarBlade: Color.lerp(colorAvatarBlade, other.colorAvatarBlade, t)!,
      colorAvatarPhantom: Color.lerp(colorAvatarPhantom, other.colorAvatarPhantom, t)!,
      colorAvatarArcane: Color.lerp(colorAvatarArcane, other.colorAvatarArcane, t)!,
      colorAvatarLunar: Color.lerp(colorAvatarLunar, other.colorAvatarLunar, t)!,
      colorAvatarStar: Color.lerp(colorAvatarStar, other.colorAvatarStar, t)!,
      colorAvatarReader: Color.lerp(colorAvatarReader, other.colorAvatarReader, t)!,
      space0: t < 0.5 ? space0 : other.space0,
      space1: t < 0.5 ? space1 : other.space1,
      space2: t < 0.5 ? space2 : other.space2,
      space3: t < 0.5 ? space3 : other.space3,
      space4: t < 0.5 ? space4 : other.space4,
      space5: t < 0.5 ? space5 : other.space5,
      space6: t < 0.5 ? space6 : other.space6,
      space8: t < 0.5 ? space8 : other.space8,
      space10: t < 0.5 ? space10 : other.space10,
      space12: t < 0.5 ? space12 : other.space12,
      space16: t < 0.5 ? space16 : other.space16,
      space20: t < 0.5 ? space20 : other.space20,
      space24: t < 0.5 ? space24 : other.space24,
      space32: t < 0.5 ? space32 : other.space32,
      gridPhone: t < 0.5 ? gridPhone : other.gridPhone,
      gridTablet: t < 0.5 ? gridTablet : other.gridTablet,
      gridDesktop: t < 0.5 ? gridDesktop : other.gridDesktop,
      gridWide: t < 0.5 ? gridWide : other.gridWide,
      gridCinema: t < 0.5 ? gridCinema : other.gridCinema,
      bpTablet: t < 0.5 ? bpTablet : other.bpTablet,
      bpFrame: t < 0.5 ? bpFrame : other.bpFrame,
      bpDesktop: t < 0.5 ? bpDesktop : other.bpDesktop,
      bpWide: t < 0.5 ? bpWide : other.bpWide,
      bpCinema: t < 0.5 ? bpCinema : other.bpCinema,
      radius0: t < 0.5 ? radius0 : other.radius0,
      radiusRound: t < 0.5 ? radiusRound : other.radiusRound,
      blurLetter: t < 0.5 ? blurLetter : other.blurLetter,
      blurRack: t < 0.5 ? blurRack : other.blurRack,
      blurBleed: t < 0.5 ? blurBleed : other.blurBleed,
      blurCard: t < 0.5 ? blurCard : other.blurCard,
      blurDefocus: t < 0.5 ? blurDefocus : other.blurDefocus,
      hitMin: t < 0.5 ? hitMin : other.hitMin,
      hitAndroid: t < 0.5 ? hitAndroid : other.hitAndroid,
      hitFine: t < 0.5 ? hitFine : other.hitFine,
      ruleHair: t < 0.5 ? ruleHair : other.ruleHair,
      ruleStrong: t < 0.5 ? ruleStrong : other.ruleStrong,
      ruleInk: t < 0.5 ? ruleInk : other.ruleInk,
      ruleHeavy: t < 0.5 ? ruleHeavy : other.ruleHeavy,
      ruleSpot: t < 0.5 ? ruleSpot : other.ruleSpot,
      ruleProof: t < 0.5 ? ruleProof : other.ruleProof,
      ruleOxford: t < 0.5 ? ruleOxford : other.ruleOxford,
      focusWidth: t < 0.5 ? focusWidth : other.focusWidth,
      focusOffset: t < 0.5 ? focusOffset : other.focusOffset,
      focusHalo: t < 0.5 ? focusHalo : other.focusHalo,
      zPage: t < 0.5 ? zPage : other.zPage,
      zSticky: t < 0.5 ? zSticky : other.zSticky,
      zChrome: t < 0.5 ? zChrome : other.zChrome,
      zPanel: t < 0.5 ? zPanel : other.zPanel,
      zSheet: t < 0.5 ? zSheet : other.zSheet,
      zDialog: t < 0.5 ? zDialog : other.zDialog,
      zToast: t < 0.5 ? zToast : other.zToast,
      zLightbox: t < 0.5 ? zLightbox : other.zLightbox,
      zShutter: t < 0.5 ? zShutter : other.zShutter,
      zDebug: t < 0.5 ? zDebug : other.zDebug,
      scrimGutter: t < 0.5 ? scrimGutter : other.scrimGutter,
      scrimFootBlack: t < 0.5 ? scrimFootBlack : other.scrimFootBlack,
      scrimRailEnd: t < 0.5 ? scrimRailEnd : other.scrimRailEnd,
      scrimVignette: t < 0.5 ? scrimVignette : other.scrimVignette,
      scrimModal: Color.lerp(scrimModal, other.scrimModal, t)!,
      durCut: t < 0.5 ? durCut : other.durCut,
      durTick: t < 0.5 ? durTick : other.durTick,
      durBeat: t < 0.5 ? durBeat : other.durBeat,
      durLine: t < 0.5 ? durLine : other.durLine,
      durColumn: t < 0.5 ? durColumn : other.durColumn,
      durSpread: t < 0.5 ? durSpread : other.durSpread,
      durWipeClose: t < 0.5 ? durWipeClose : other.durWipeClose,
      durWipeOpen: t < 0.5 ? durWipeOpen : other.durWipeOpen,
      durDissolve: t < 0.5 ? durDissolve : other.durDissolve,
      durReel: t < 0.5 ? durReel : other.durReel,
      durDrift: t < 0.5 ? durDrift : other.durDrift,
      durType: t < 0.5 ? durType : other.durType,
      durCaret: t < 0.5 ? durCaret : other.durCaret,
      durLetter: t < 0.5 ? durLetter : other.durLetter,
      durLetterBlur: t < 0.5 ? durLetterBlur : other.durLetterBlur,
      durHoldToast: t < 0.5 ? durHoldToast : other.durHoldToast,
      durHoldToastError: t < 0.5 ? durHoldToastError : other.durHoldToastError,
      durHoldToastAction: t < 0.5 ? durHoldToastAction : other.durHoldToastAction,
      durHoldToastUndo: t < 0.5 ? durHoldToastUndo : other.durHoldToastUndo,
      durHoldRating: t < 0.5 ? durHoldRating : other.durHoldRating,
      durHoldPanelBase: t < 0.5 ? durHoldPanelBase : other.durHoldPanelBase,
      durHoldPanelWord: t < 0.5 ? durHoldPanelWord : other.durHoldPanelWord,
      durHoldPanelCap: t < 0.5 ? durHoldPanelCap : other.durHoldPanelCap,
      durHoldDip: t < 0.5 ? durHoldDip : other.durHoldDip,
      durHoldError: t < 0.5 ? durHoldError : other.durHoldError,
      durHoldGlance: t < 0.5 ? durHoldGlance : other.durHoldGlance,
      durHoldSuccess: t < 0.5 ? durHoldSuccess : other.durHoldSuccess,
      durHoldConnected: t < 0.5 ? durHoldConnected : other.durHoldConnected,
      durHoldChip: t < 0.5 ? durHoldChip : other.durHoldChip,
      durHoldFlash: t < 0.5 ? durHoldFlash : other.durHoldFlash,
      durHoldBrief: t < 0.5 ? durHoldBrief : other.durHoldBrief,
      durHoldEdition: t < 0.5 ? durHoldEdition : other.durHoldEdition,
      durHoldAnnualPage: t < 0.5 ? durHoldAnnualPage : other.durHoldAnnualPage,
      durHoldAnnualList: t < 0.5 ? durHoldAnnualList : other.durHoldAnnualList,
      durDwellPreview: t < 0.5 ? durDwellPreview : other.durDwellPreview,
      durDwellBackdrop: t < 0.5 ? durDwellBackdrop : other.durDwellBackdrop,
      durFlicker: t < 0.5 ? durFlicker : other.durFlicker,
      durArm: t < 0.5 ? durArm : other.durArm,
      durCountdownRecap: t < 0.5 ? durCountdownRecap : other.durCountdownRecap,
      durCountdownNext: t < 0.5 ? durCountdownNext : other.durCountdownNext,
      durSampleTint: t < 0.5 ? durSampleTint : other.durSampleTint,
      durPageturn: t < 0.5 ? durPageturn : other.durPageturn,
      durSnap: t < 0.5 ? durSnap : other.durSnap,
      durReduced: t < 0.5 ? durReduced : other.durReduced,
      durClip: t < 0.5 ? durClip : other.durClip,
      durPageOut: t < 0.5 ? durPageOut : other.durPageOut,
      durDim: t < 0.5 ? durDim : other.durDim,
      durTapscroll: t < 0.5 ? durTapscroll : other.durTapscroll,
      durMatchBack: t < 0.5 ? durMatchBack : other.durMatchBack,
      durRise: t < 0.5 ? durRise : other.durRise,
      durGlide: t < 0.5 ? durGlide : other.durGlide,
      durStoppress: t < 0.5 ? durStoppress : other.durStoppress,
      durRack: t < 0.5 ? durRack : other.durRack,
      durIrisOut: t < 0.5 ? durIrisOut : other.durIrisOut,
      durLoopRule: t < 0.5 ? durLoopRule : other.durLoopRule,
      durLoopPreview: t < 0.5 ? durLoopPreview : other.durLoopPreview,
      durFlameFlicker: t < 0.5 ? durFlameFlicker : other.durFlameFlicker,
      durFlameRisk: t < 0.5 ? durFlameRisk : other.durFlameRisk,
      durFlameRing: t < 0.5 ? durFlameRing : other.durFlameRing,
      durFlameSpark: t < 0.5 ? durFlameSpark : other.durFlameSpark,
      durFadeFirst: t < 0.5 ? durFadeFirst : other.durFadeFirst,
      durFadeCut: t < 0.5 ? durFadeCut : other.durFadeCut,
      durFadeHint: t < 0.5 ? durFadeHint : other.durFadeHint,
      durLeader: t < 0.5 ? durLeader : other.durLeader,
      durRollColophon: t < 0.5 ? durRollColophon : other.durRollColophon,
      easeSettle: t < 0.5 ? easeSettle : other.easeSettle,
      easeLift: t < 0.5 ? easeLift : other.easeLift,
      easeTurn: t < 0.5 ? easeTurn : other.easeTurn,
      easeSet: t < 0.5 ? easeSet : other.easeSet,
      easeDrift: t < 0.5 ? easeDrift : other.easeDrift,
      easeScroll: t < 0.5 ? easeScroll : other.easeScroll,
      easeLinear: t < 0.5 ? easeLinear : other.easeLinear,
      springRelease: t < 0.5 ? springRelease : other.springRelease,
      springSheet: t < 0.5 ? springSheet : other.springSheet,
      springScrub: t < 0.5 ? springScrub : other.springScrub,
      scalarStaggerGrid: t < 0.5 ? scalarStaggerGrid : other.scalarStaggerGrid,
      scalarStaggerList: t < 0.5 ? scalarStaggerList : other.scalarStaggerList,
      scalarStaggerLetter: t < 0.5 ? scalarStaggerLetter : other.scalarStaggerLetter,
      scalarStaggerWord: t < 0.5 ? scalarStaggerWord : other.scalarStaggerWord,
      scalarStaggerFly: t < 0.5 ? scalarStaggerFly : other.scalarStaggerFly,
      scalarLetterRise: t < 0.5 ? scalarLetterRise : other.scalarLetterRise,
      scalarRubber: t < 0.5 ? scalarRubber : other.scalarRubber,
      scalarPaceTop: t < 0.5 ? scalarPaceTop : other.scalarPaceTop,
      scalarPaceWords: t < 0.5 ? scalarPaceWords : other.scalarPaceWords,
      scalarPaceMin: t < 0.5 ? scalarPaceMin : other.scalarPaceMin,
      scalarPaceMax: t < 0.5 ? scalarPaceMax : other.scalarPaceMax,
      typeCover: t < 0.5 ? typeCover : other.typeCover,
      typeMasthead: t < 0.5 ? typeMasthead : other.typeMasthead,
      typeHeadline: t < 0.5 ? typeHeadline : other.typeHeadline,
      typeSection: t < 0.5 ? typeSection : other.typeSection,
      typeSubhead: t < 0.5 ? typeSubhead : other.typeSubhead,
      typeNumeral: t < 0.5 ? typeNumeral : other.typeNumeral,
      typePull: t < 0.5 ? typePull : other.typePull,
      typeField: t < 0.5 ? typeField : other.typeField,
      typeDeck: t < 0.5 ? typeDeck : other.typeDeck,
      typeBody: t < 0.5 ? typeBody : other.typeBody,
      typeBodyItalic: t < 0.5 ? typeBodyItalic : other.typeBodyItalic,
      typeTitle: t < 0.5 ? typeTitle : other.typeTitle,
      typeUi: t < 0.5 ? typeUi : other.typeUi,
      typeLabel: t < 0.5 ? typeLabel : other.typeLabel,
      typeKicker: t < 0.5 ? typeKicker : other.typeKicker,
      typeCredit: t < 0.5 ? typeCredit : other.typeCredit,
      typeCreditLabel: t < 0.5 ? typeCreditLabel : other.typeCreditLabel,
      typeNav: t < 0.5 ? typeNav : other.typeNav,
      typeCaption: t < 0.5 ? typeCaption : other.typeCaption,
      typeFolio: t < 0.5 ? typeFolio : other.typeFolio,
      typeFolioLg: t < 0.5 ? typeFolioLg : other.typeFolioLg,
      typeMicro: t < 0.5 ? typeMicro : other.typeMicro,
      fontDisplay: t < 0.5 ? fontDisplay : other.fontDisplay,
      fontGrotesk: t < 0.5 ? fontGrotesk : other.fontGrotesk,
      fontText: t < 0.5 ? fontText : other.fontText,
      fontFolio: t < 0.5 ? fontFolio : other.fontFolio,
      fontLiterata: t < 0.5 ? fontLiterata : other.fontLiterata,
      fontSourceSerif: t < 0.5 ? fontSourceSerif : other.fontSourceSerif,
      fontAtkinson: t < 0.5 ? fontAtkinson : other.fontAtkinson,
    );
  }
}

const cinematicTokens = CineTokens(
  colorPaper0: CineColors.paper0,
  colorPaper1: CineColors.paper1,
  colorPaper2: CineColors.paper2,
  colorPaper3: CineColors.paper3,
  colorPaper4: CineColors.paper4,
  colorRule1: CineColors.rule1,
  colorRule2: CineColors.rule2,
  colorInk30: CineColors.ink30,
  colorInk45: CineColors.ink45,
  colorInk60: CineColors.ink60,
  colorInk80: CineColors.ink80,
  colorInk100: CineColors.ink100,
  colorSpot: CineColors.spot,
  colorSpotPress: CineColors.spotPress,
  colorSpotWash: CineColors.spotWash,
  colorSpotGlow: CineColors.spotGlow,
  colorProof: CineColors.proof,
  colorProofPress: CineColors.proofPress,
  colorProofWash: CineColors.proofWash,
  colorSet: CineColors.colorSet,
  colorInfo: CineColors.info,
  colorNote: CineColors.note,
  colorOnart: CineColors.onart,
  colorHairlineArt: CineColors.hairlineArt,
  colorGalley: CineColors.galley,
  colorLeaderSweep: CineColors.leaderSweep,
  colorLightbox: CineColors.lightbox,
  colorMatteGuided: CineColors.matteGuided,
  colorWarmth: CineColors.warmth,
  colorAmbientFallbackDuo: CineColors.ambientFallbackDuo,
  colorAmbientFallbackTint: CineColors.ambientFallbackTint,
  colorAmbientFallbackInk: CineColors.ambientFallbackInk,
  colorMoodRomantic: CineColors.moodRomantic,
  colorMoodAction: CineColors.moodAction,
  colorMoodComedy: CineColors.moodComedy,
  colorMoodHorror: CineColors.moodHorror,
  colorMoodSliceOfLife: CineColors.moodSliceOfLife,
  colorMoodFantasy: CineColors.moodFantasy,
  colorSpeaker1: CineColors.speaker1,
  colorSpeaker2: CineColors.speaker2,
  colorSpeaker3: CineColors.speaker3,
  colorSpeaker4: CineColors.speaker4,
  colorSpeaker5: CineColors.speaker5,
  colorSpeaker6: CineColors.speaker6,
  colorSpeaker7: CineColors.speaker7,
  colorSpeaker8: CineColors.speaker8,
  colorSpeaker9: CineColors.speaker9,
  colorSpeaker10: CineColors.speaker10,
  colorStockNitratePage: CineColors.stockNitratePage,
  colorStockNitrateInk: CineColors.stockNitrateInk,
  colorStockNitrateMuted: CineColors.stockNitrateMuted,
  colorStockInkPage: CineColors.stockInkPage,
  colorStockInkInk: CineColors.stockInkInk,
  colorStockInkMuted: CineColors.stockInkMuted,
  colorStockSepiaNightPage: CineColors.stockSepiaNightPage,
  colorStockSepiaNightInk: CineColors.stockSepiaNightInk,
  colorStockSepiaNightMuted: CineColors.stockSepiaNightMuted,
  colorStockDuskPage: CineColors.stockDuskPage,
  colorStockDuskInk: CineColors.stockDuskInk,
  colorStockDuskMuted: CineColors.stockDuskMuted,
  colorStockMossPage: CineColors.stockMossPage,
  colorStockMossInk: CineColors.stockMossInk,
  colorStockMossMuted: CineColors.stockMossMuted,
  colorStockRosewoodPage: CineColors.stockRosewoodPage,
  colorStockRosewoodInk: CineColors.stockRosewoodInk,
  colorStockRosewoodMuted: CineColors.stockRosewoodMuted,
  colorGroundBlack: CineColors.groundBlack,
  colorGroundInk: CineColors.groundInk,
  colorGroundSlate: CineColors.groundSlate,
  colorAvatarViolet: CineColors.avatarViolet,
  colorAvatarCyan: CineColors.avatarCyan,
  colorAvatarRose: CineColors.avatarRose,
  colorAvatarAmber: CineColors.avatarAmber,
  colorAvatarEmerald: CineColors.avatarEmerald,
  colorAvatarEmber: CineColors.avatarEmber,
  colorAvatarBlade: CineColors.avatarBlade,
  colorAvatarPhantom: CineColors.avatarPhantom,
  colorAvatarArcane: CineColors.avatarArcane,
  colorAvatarLunar: CineColors.avatarLunar,
  colorAvatarStar: CineColors.avatarStar,
  colorAvatarReader: CineColors.avatarReader,
  space0: CineSpace.s0,
  space1: CineSpace.s1,
  space2: CineSpace.s2,
  space3: CineSpace.s3,
  space4: CineSpace.s4,
  space5: CineSpace.s5,
  space6: CineSpace.s6,
  space8: CineSpace.s8,
  space10: CineSpace.s10,
  space12: CineSpace.s12,
  space16: CineSpace.s16,
  space20: CineSpace.s20,
  space24: CineSpace.s24,
  space32: CineSpace.s32,
  gridPhone: GridSpec(columns: 4, margin: 16.0, gutter: 12.0, max: double.infinity),
  gridTablet: GridSpec(columns: 8, margin: 32.0, gutter: 16.0, max: double.infinity),
  gridDesktop: GridSpec(columns: 12, margin: 48.0, gutter: 24.0, max: double.infinity),
  gridWide: GridSpec(columns: 12, margin: 72.0, gutter: 24.0, max: 1760.0),
  gridCinema: GridSpec(columns: 12, margin: 96.0, gutter: 32.0, max: 1760.0),
  bpTablet: 600.0,
  bpFrame: 768.0,
  bpDesktop: 1024.0,
  bpWide: 1440.0,
  bpCinema: 1920.0,
  radius0: 0.0,
  radiusRound: 9999.0,
  blurLetter: 8.0,
  blurRack: 14.0,
  blurBleed: 56.0,
  blurCard: 24.0,
  blurDefocus: 6.0,
  hitMin: 44.0,
  hitAndroid: 48.0,
  hitFine: 32.0,
  ruleHair: BorderSide(color: Color(0xFF2B2A27), width: 1.0),
  ruleStrong: BorderSide(color: Color(0xFF3D3C38), width: 1.0),
  ruleInk: BorderSide(color: Color(0xFFF3F0E8), width: 1.0),
  ruleHeavy: BorderSide(color: Color(0xFFF3F0E8), width: 3.0),
  ruleSpot: BorderSide(color: Color(0xFFF4D03F), width: 2.0),
  ruleProof: BorderSide(color: Color(0xFFFF5B4A), width: 2.0),
  ruleOxford: OxfordRule(thick: 3.0, gap: 2.0, thin: 1.0, color: Color(0xFFF3F0E8)),
  focusWidth: 2.0,
  focusOffset: 2.0,
  focusHalo: 6.0,
  zPage: 0,
  zSticky: 10,
  zChrome: 20,
  zPanel: 30,
  zSheet: 40,
  zDialog: 50,
  zToast: 60,
  zLightbox: 70,
  zShutter: 80,
  zDebug: 90,
  scrimGutter: CineScrim.gutter,
  scrimFootBlack: CineScrim.footBlack,
  scrimRailEnd: CineScrim.railEnd,
  scrimVignette: CineScrim.vignette,
  scrimModal: CineScrim.modal,
  durCut: CineDur.cut,
  durTick: CineDur.tick,
  durBeat: CineDur.beat,
  durLine: CineDur.line,
  durColumn: CineDur.column,
  durSpread: CineDur.spread,
  durWipeClose: CineDur.wipeClose,
  durWipeOpen: CineDur.wipeOpen,
  durDissolve: CineDur.dissolve,
  durReel: CineDur.reel,
  durDrift: CineDur.drift,
  durType: CineDur.type,
  durCaret: CineDur.caret,
  durLetter: CineDur.letter,
  durLetterBlur: CineDur.letterBlur,
  durHoldToast: CineDur.holdToast,
  durHoldToastError: CineDur.holdToastError,
  durHoldToastAction: CineDur.holdToastAction,
  durHoldToastUndo: CineDur.holdToastUndo,
  durHoldRating: CineDur.holdRating,
  durHoldPanelBase: CineDur.holdPanelBase,
  durHoldPanelWord: CineDur.holdPanelWord,
  durHoldPanelCap: CineDur.holdPanelCap,
  durHoldDip: CineDur.holdDip,
  durHoldError: CineDur.holdError,
  durHoldGlance: CineDur.holdGlance,
  durHoldSuccess: CineDur.holdSuccess,
  durHoldConnected: CineDur.holdConnected,
  durHoldChip: CineDur.holdChip,
  durHoldFlash: CineDur.holdFlash,
  durHoldBrief: CineDur.holdBrief,
  durHoldEdition: CineDur.holdEdition,
  durHoldAnnualPage: CineDur.holdAnnualPage,
  durHoldAnnualList: CineDur.holdAnnualList,
  durDwellPreview: CineDur.dwellPreview,
  durDwellBackdrop: CineDur.dwellBackdrop,
  durFlicker: CineDur.flicker,
  durArm: CineDur.arm,
  durCountdownRecap: CineDur.countdownRecap,
  durCountdownNext: CineDur.countdownNext,
  durSampleTint: CineDur.sampleTint,
  durPageturn: CineDur.pageturn,
  durSnap: CineDur.snap,
  durReduced: CineDur.reduced,
  durClip: CineDur.clip,
  durPageOut: CineDur.pageOut,
  durDim: CineDur.dim,
  durTapscroll: CineDur.tapscroll,
  durMatchBack: CineDur.matchBack,
  durRise: CineDur.rise,
  durGlide: CineDur.glide,
  durStoppress: CineDur.stoppress,
  durRack: CineDur.rack,
  durIrisOut: CineDur.irisOut,
  durLoopRule: CineDur.loopRule,
  durLoopPreview: CineDur.loopPreview,
  durFlameFlicker: CineDur.flameFlicker,
  durFlameRisk: CineDur.flameRisk,
  durFlameRing: CineDur.flameRing,
  durFlameSpark: CineDur.flameSpark,
  durFadeFirst: CineDur.fadeFirst,
  durFadeCut: CineDur.fadeCut,
  durFadeHint: CineDur.fadeHint,
  durLeader: CineDur.leader,
  durRollColophon: CineDur.rollColophon,
  easeSettle: CineCurves.settle,
  easeLift: CineCurves.lift,
  easeTurn: CineCurves.turn,
  easeSet: CineCurves.easeSet,
  easeDrift: CineCurves.drift,
  easeScroll: CineCurves.scroll,
  easeLinear: CineCurves.linear,
  springRelease: CineSprings.release,
  springSheet: CineSprings.sheet,
  springScrub: CineSprings.scrub,
  scalarStaggerGrid: MotionStagger(item: 32, row: 64, cap: 480),
  scalarStaggerList: MotionStagger(item: 24, cap: 360),
  scalarStaggerLetter: MotionStagger(item: 24, cap: 560, startDelay: 120),
  scalarStaggerWord: MotionStagger(item: 30, fade: 160),
  scalarStaggerFly: MotionStagger(item: 60),
  scalarLetterRise: 0.42,
  scalarRubber: 0.35,
  scalarPaceTop: 1.2,
  scalarPaceWords: 60.0,
  scalarPaceMin: 0.5,
  scalarPaceMax: 1.0,
  typeCover: CineTextRole(family: 'BodoniModa', italic: false, wght: 700.0, axes: {'opsz': 96.0}, sizes: [44.0, 64.0, 88.0, 120.0], lines: [44.0, 60.0, 84.0, 112.0], trackingEm: -0.04, cap: 1.15),
  typeMasthead: CineTextRole(family: 'BodoniModa', italic: false, wght: 800.0, axes: {'opsz': 96.0}, sizes: [40.0, 56.0, 72.0, 88.0], lines: [40.0, 56.0, 68.0, 84.0], trackingEm: -0.035, cap: 1.15),
  typeHeadline: CineTextRole(family: 'BodoniModa', italic: false, wght: 700.0, axes: {'opsz': 72.0}, sizes: [32.0, 44.0, 56.0, 64.0], lines: [36.0, 48.0, 56.0, 64.0], trackingEm: -0.03, cap: 1.15),
  typeSection: CineTextRole(family: 'BodoniModa', italic: true, wght: 600.0, axes: {'opsz': 48.0}, sizes: [24.0, 28.0, 32.0, 36.0], lines: [28.0, 32.0, 36.0, 40.0], trackingEm: -0.02, cap: 1.3),
  typeSubhead: CineTextRole(family: 'BodoniModa', italic: false, wght: 600.0, axes: {'opsz': 28.0}, sizes: [20.0, 22.0, 24.0, 24.0], lines: [24.0, 28.0, 28.0, 28.0], trackingEm: -0.01, cap: 1.3),
  typeNumeral: CineTextRole(family: 'BodoniModa', italic: false, wght: 900.0, axes: {'opsz': 96.0}, sizes: [56.0, 72.0, 96.0, 120.0], lines: [56.0, 72.0, 88.0, 112.0], trackingEm: -0.03, cap: 1.15),
  typePull: CineTextRole(family: 'BodoniModa', italic: true, wght: 500.0, axes: {'opsz': 72.0}, sizes: [24.0, 28.0, 36.0, 40.0], lines: [32.0, 36.0, 44.0, 48.0], trackingEm: -0.015, cap: 1.3),
  typeField: CineTextRole(family: 'BodoniModa', italic: true, wght: 500.0, axes: {'opsz': 48.0}, sizes: [28.0, 32.0, 36.0, 40.0], lines: [36.0, 40.0, 44.0, 48.0], trackingEm: -0.015, cap: 1.3),
  typeDeck: CineTextRole(family: 'Newsreader', italic: false, wght: 400.0, axes: {'opsz': 20.0}, sizes: [17.0, 18.0, 20.0, 22.0], lines: [24.0, 28.0, 28.0, 32.0], trackingEm: 0.0, cap: 2.0),
  typeBody: CineTextRole(family: 'Newsreader', italic: false, wght: 400.0, axes: {'opsz': 16.0}, sizes: [16.0, 16.0, 17.0, 17.0], lines: [24.0, 24.0, 28.0, 28.0], trackingEm: 0.0, cap: 2.0),
  typeBodyItalic: CineTextRole(family: 'Newsreader', italic: true, wght: 400.0, axes: {'opsz': 16.0}, sizes: [16.0, 16.0, 17.0, 17.0], lines: [24.0, 24.0, 28.0, 28.0], trackingEm: 0.0, cap: 2.0),
  typeTitle: CineTextRole(family: 'Archivo', italic: false, wght: 600.0, axes: {'wdth': 100.0}, sizes: [15.0, 15.0, 16.0, 16.0], lines: [20.0, 20.0, 20.0, 20.0], trackingEm: -0.005, cap: 2.0),
  typeUi: CineTextRole(family: 'Archivo', italic: false, wght: 500.0, axes: {'wdth': 100.0}, sizes: [15.0, 15.0, 14.0, 14.0], lines: [20.0, 20.0, 20.0, 20.0], trackingEm: 0.0, cap: 2.0),
  typeLabel: CineTextRole(family: 'Archivo', italic: false, wght: 650.0, axes: {'wdth': 100.0}, sizes: [15.0, 15.0, 14.0, 15.0], lines: [20.0, 20.0, 20.0, 20.0], trackingEm: 0.005, cap: 2.0),
  typeKicker: CineTextRole(family: 'Archivo', italic: false, wght: 700.0, axes: {'wdth': 62.0}, sizes: [11.0, 12.0, 12.0, 13.0], lines: [16.0, 16.0, 16.0, 16.0], trackingEm: 0.16, cap: 2.0, upper: true),
  typeCredit: CineTextRole(family: 'Archivo', italic: false, wght: 700.0, axes: {'wdth': 70.0}, sizes: [12.0, 12.0, 12.0, 13.0], lines: [16.0, 16.0, 16.0, 16.0], trackingEm: 0.08, cap: 2.0, upper: true),
  typeCreditLabel: CineTextRole(family: 'Archivo', italic: false, wght: 500.0, axes: {'wdth': 70.0}, sizes: [12.0, 12.0, 12.0, 13.0], lines: [16.0, 16.0, 16.0, 16.0], trackingEm: 0.08, cap: 2.0, upper: true),
  typeNav: CineTextRole(family: 'Archivo', italic: false, wght: 600.0, axes: {'wdth': 75.0}, sizes: [10.0, 12.0, 13.0, 13.0], lines: [12.0, 16.0, 16.0, 16.0], trackingEm: 0.12, cap: 1.5, upper: true),
  typeCaption: CineTextRole(family: 'Archivo', italic: false, wght: 450.0, axes: {'wdth': 90.0}, sizes: [13.0, 13.0, 13.0, 13.0], lines: [16.0, 16.0, 16.0, 16.0], trackingEm: 0.005, cap: 2.0),
  typeFolio: CineTextRole(family: 'IBMPlexMono', italic: false, wght: 500.0, axes: {}, sizes: [12.0, 12.0, 12.0, 13.0], lines: [16.0, 16.0, 16.0, 16.0], trackingEm: 0.02, cap: 2.0),
  typeFolioLg: CineTextRole(family: 'IBMPlexMono', italic: false, wght: 500.0, axes: {}, sizes: [15.0, 15.0, 15.0, 16.0], lines: [20.0, 20.0, 20.0, 20.0], trackingEm: 0.0, cap: 2.0),
  typeMicro: CineTextRole(family: 'Archivo', italic: false, wght: 700.0, axes: {'wdth': 62.0}, sizes: [10.0, 10.0, 10.0, 11.0], lines: [12.0, 12.0, 12.0, 12.0], trackingEm: 0.12, cap: 1.5, upper: true),
  fontDisplay: 'BodoniModa',
  fontGrotesk: 'Archivo',
  fontText: 'Newsreader',
  fontFolio: 'IBMPlexMono',
  fontLiterata: 'Literata',
  fontSourceSerif: 'SourceSerif4',
  fontAtkinson: 'AtkinsonHyperlegibleNext',
);

extension CineTokensContext on BuildContext {
  CineTokens get cine => Theme.of(this).extension<CineTokens>()!;
}

abstract final class CineColors {
  static const paper0 = Color(0xFF000000);
  static const paper1 = Color(0xFF0B0B0A);
  static const paper2 = Color(0xFF121211);
  static const paper3 = Color(0xFF1A1A18);
  static const paper4 = Color(0xFF232220);
  static const rule1 = Color(0xFF2B2A27);
  static const rule2 = Color(0xFF3D3C38);
  static const ink30 = Color(0xFF4D4B47);
  static const ink45 = Color(0xFF7A7770);
  static const ink60 = Color(0xFF9A978F);
  static const ink80 = Color(0xFFC9C6BE);
  static const ink100 = Color(0xFFF3F0E8);
  static const spot = Color(0xFFF4D03F);
  static const spotPress = Color(0xFFD9B62C);
  static const spotWash = Color(0x29F4D03F);
  static const spotGlow = Color(0x59F4D03F);
  static const proof = Color(0xFFFF5B4A);
  static const proofPress = Color(0xFFE0483A);
  static const proofWash = Color(0x1FFF5B4A);
  static const colorSet = Color(0xFF57D68D);
  static const info = Color(0xFF9CC8FF);
  static const note = Color(0xFFF4D03F);
  static const onart = Color(0xA3000000);
  static const hairlineArt = Color(0x14F3F0E8);
  static const galley = Color(0x0FF3F0E8);
  static const leaderSweep = Color(0x38F3F0E8);
  static const lightbox = Color(0xF5000000);
  static const matteGuided = Color(0xD9000000);
  static const warmth = Color(0xFFFF8A00);
  static const ambientFallbackDuo = Color(0xFFB8B2A4);
  static const ambientFallbackTint = Color(0xFF0E0D0B);
  static const ambientFallbackInk = Color(0xFFF3F0E8);
  static const moodRomantic = Color(0xFF1A0B10);
  static const moodAction = Color(0xFF1A0D08);
  static const moodComedy = Color(0xFF17130A);
  static const moodHorror = Color(0xFF0F0A0D);
  static const moodSliceOfLife = Color(0xFF0F120C);
  static const moodFantasy = Color(0xFF120C18);
  static const speaker1 = Color(0xFF7CC4FF);
  static const speaker2 = Color(0xFFFF8A7A);
  static const speaker3 = Color(0xFF9BE08A);
  static const speaker4 = Color(0xFFD6A3FF);
  static const speaker5 = Color(0xFFFFC266);
  static const speaker6 = Color(0xFF6FE3D6);
  static const speaker7 = Color(0xFFFF9FCB);
  static const speaker8 = Color(0xFFC9B38A);
  static const speaker9 = Color(0xFFA6B4FF);
  static const speaker10 = Color(0xFFE0E0A0);
  static const stockNitratePage = Color(0xFF000000);
  static const stockNitrateInk = Color(0xFFD9D6D0);
  static const stockNitrateMuted = Color(0xFF8A877F);
  static const stockInkPage = Color(0xFF0B0B0C);
  static const stockInkInk = Color(0xFFE6E3DD);
  static const stockInkMuted = Color(0xFF8F8C86);
  static const stockSepiaNightPage = Color(0xFF15110C);
  static const stockSepiaNightInk = Color(0xFFE8D8BE);
  static const stockSepiaNightMuted = Color(0xFF9C8E78);
  static const stockDuskPage = Color(0xFF0D1117);
  static const stockDuskInk = Color(0xFFD3DAE3);
  static const stockDuskMuted = Color(0xFF8590A0);
  static const stockMossPage = Color(0xFF0E130F);
  static const stockMossInk = Color(0xFFD5DECF);
  static const stockMossMuted = Color(0xFF879384);
  static const stockRosewoodPage = Color(0xFF160E10);
  static const stockRosewoodInk = Color(0xFFEBD5D8);
  static const stockRosewoodMuted = Color(0xFFA08A8E);
  static const groundBlack = Color(0xFF000000);
  static const groundInk = Color(0xFF0B0B0A);
  static const groundSlate = Color(0xFF1A1A18);
  static const avatarViolet = Color(0xFF6E56CF);
  static const avatarCyan = Color(0xFF1A778C);
  static const avatarRose = Color(0xFFB83A56);
  static const avatarAmber = Color(0xFF95630F);
  static const avatarEmerald = Color(0xFF1A7B54);
  static const avatarEmber = Color(0xFFBE4523);
  static const avatarBlade = Color(0xFF5E6878);
  static const avatarPhantom = Color(0xFF474B94);
  static const avatarArcane = Color(0xFF7D45B8);
  static const avatarLunar = Color(0xFF2B5699);
  static const avatarStar = Color(0xFF85690C);
  static const avatarReader = Color(0xFF177878);
}

abstract final class CineSpace {
  static const s0 = 0.0;
  static const s1 = 4.0;
  static const s2 = 8.0;
  static const s3 = 12.0;
  static const s4 = 16.0;
  static const s5 = 20.0;
  static const s6 = 24.0;
  static const s8 = 32.0;
  static const s10 = 40.0;
  static const s12 = 48.0;
  static const s16 = 64.0;
  static const s20 = 80.0;
  static const s24 = 96.0;
  static const s32 = 128.0;
}

abstract final class CineDur {
  static const cut = Duration(milliseconds: 0);
  static const tick = Duration(milliseconds: 80);
  static const beat = Duration(milliseconds: 160);
  static const line = Duration(milliseconds: 240);
  static const column = Duration(milliseconds: 320);
  static const spread = Duration(milliseconds: 480);
  static const wipeClose = Duration(milliseconds: 200);
  static const wipeOpen = Duration(milliseconds: 280);
  static const dissolve = Duration(milliseconds: 800);
  static const reel = Duration(milliseconds: 1400);
  static const drift = Duration(milliseconds: 26000);
  static const type = Duration(milliseconds: 50);
  static const caret = Duration(milliseconds: 530);
  static const letter = Duration(milliseconds: 640);
  static const letterBlur = Duration(milliseconds: 440);
  static const holdToast = Duration(milliseconds: 3600);
  static const holdToastError = Duration(milliseconds: 6000);
  static const holdToastAction = Duration(milliseconds: 8000);
  static const holdToastUndo = Duration(milliseconds: 10000);
  static const holdRating = Duration(milliseconds: 3000);
  static const holdPanelBase = Duration(milliseconds: 1200);
  static const holdPanelWord = Duration(milliseconds: 250);
  static const holdPanelCap = Duration(milliseconds: 6000);
  static const holdDip = Duration(milliseconds: 40);
  static const holdError = Duration(milliseconds: 2000);
  static const holdGlance = Duration(milliseconds: 1500);
  static const holdSuccess = Duration(milliseconds: 1600);
  static const holdConnected = Duration(milliseconds: 400);
  static const holdChip = Duration(milliseconds: 1200);
  static const holdFlash = Duration(milliseconds: 1200);
  static const holdBrief = Duration(milliseconds: 2000);
  static const holdEdition = Duration(milliseconds: 4000);
  static const holdAnnualPage = Duration(milliseconds: 6000);
  static const holdAnnualList = Duration(milliseconds: 8000);
  static const dwellPreview = Duration(milliseconds: 600);
  static const dwellBackdrop = Duration(milliseconds: 400);
  static const flicker = Duration(milliseconds: 1400);
  static const arm = Duration(milliseconds: 1000);
  static const countdownRecap = Duration(milliseconds: 12000);
  static const countdownNext = Duration(milliseconds: 5000);
  static const sampleTint = Duration(milliseconds: 600);
  static const pageturn = Duration(milliseconds: 280);
  static const snap = Duration(milliseconds: 120);
  static const reduced = Duration(milliseconds: 150);
  static const clip = Duration(milliseconds: 200);
  static const pageOut = Duration(milliseconds: 224);
  static const dim = Duration(milliseconds: 280);
  static const tapscroll = Duration(milliseconds: 300);
  static const matchBack = Duration(milliseconds: 336);
  static const rise = Duration(milliseconds: 360);
  static const glide = Duration(milliseconds: 400);
  static const stoppress = Duration(milliseconds: 500);
  static const rack = Duration(milliseconds: 520);
  static const irisOut = Duration(milliseconds: 560);
  static const loopRule = Duration(milliseconds: 1200);
  static const loopPreview = Duration(milliseconds: 12000);
  static const flameFlicker = Duration(milliseconds: 2000);
  static const flameRisk = Duration(milliseconds: 800);
  static const flameRing = Duration(milliseconds: 24000);
  static const flameSpark = Duration(milliseconds: 900);
  static const fadeFirst = Duration(milliseconds: 100);
  static const fadeCut = Duration(milliseconds: 250);
  static const fadeHint = Duration(milliseconds: 1000);
  static const leader = Duration(milliseconds: 1000);
  static const rollColophon = Duration(milliseconds: 10000);
}

abstract final class CineCurves {
  static const settle = Cubic(0.16, 1.0, 0.3, 1.0);
  static const lift = Cubic(0.7, 0.0, 0.84, 0.0);
  static const turn = Cubic(0.65, 0.0, 0.35, 1.0);
  static const easeSet = Cubic(0.2, 0.0, 0.0, 1.0);
  static const drift = Cubic(0.37, 0.0, 0.63, 1.0);
  static const scroll = Cubic(0.5, 1.0, 0.89, 1.0);
  static const linear = Curves.linear;
}

abstract final class CineSprings {
  static const release = SpringToken(ms: 420, bounce: 0.0);
  static const sheet = SpringToken(ms: 480, bounce: 0.0);
  static const scrub = SpringToken(ms: 240, bounce: 0.0);
}

abstract final class CineScrim {
  static const List<double> kScrimStops = [0.0, 0.018, 0.048, 0.09, 0.139, 0.198, 0.27, 0.35, 0.435, 0.53, 0.66, 0.81, 1.0];
  static const List<double> kScrimAlpha = [0.0, 0.002, 0.008, 0.021, 0.042, 0.075, 0.126, 0.194, 0.278, 0.382, 0.541, 0.738, 1.0];
  static const gutter = LinearGradient(begin: Alignment(1.0, 0.0), end: Alignment.centerLeft, stops: kScrimStops, colors: [Color.from(alpha: 0.0, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.002, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.008, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.021, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.042, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.075, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.126, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.194, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.278, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.382, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.541, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.738, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 1.0, red: 0.0, green: 0.0, blue: 0.0)]);
  static const footBlack = LinearGradient(begin: Alignment(0.0, -0.2), end: Alignment.bottomCenter, stops: kScrimStops, colors: [Color.from(alpha: 0.0, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.002, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.008, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.021, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.042, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.075, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.126, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.194, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.278, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.382, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.541, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 0.738, red: 0.0, green: 0.0, blue: 0.0), Color.from(alpha: 1.0, red: 0.0, green: 0.0, blue: 0.0)]);
  static const railEnd = LinearGradient(begin: Alignment(-1.0, 0.0), end: Alignment.centerRight, colors: [Color(0xFF000000), Color(0x00000000)]);
  static const vignette = RadialGradient(center: Alignment(0.0, -0.2), radius: 1.0, stops: [0.6, 1.0], colors: [Color(0x00000000), Color(0x73000000)], transform: CssEllipse(rx: 1.2, ry: 0.9, cx: 0.5, cy: 0.4));
  static const modal = Color(0xC7000000);
}

class CineTextRole {
  const CineTextRole({
    required this.family,
    required this.italic,
    required this.wght,
    required this.axes,
    required this.sizes,
    required this.lines,
    required this.trackingEm,
    required this.cap,
    this.upper = false,
  });

  final String family;
  final bool italic;
  final double wght;
  final Map<String, double> axes;
  /// Per breakpoint: phone, tablet, desktop, wide.
  final List<double> sizes;
  final List<double> lines;
  final double trackingEm;
  final double cap;
  final bool upper;
}

abstract final class CineType {
  static const Map<String, double> _wghtMax = {'BodoniModa': 900.0, 'Archivo': 900.0, 'Newsreader': 800.0, 'IBMPlexMono': 600.0, 'Literata': 900.0, 'SourceSerif4': 900.0, 'AtkinsonHyperlegibleNext': 800.0};
  static const Set<String> _wghtAxis = {'BodoniModa', 'Archivo', 'Newsreader', 'Literata', 'SourceSerif4', 'AtkinsonHyperlegibleNext'};
  static const Set<String> _opszAxis = {'BodoniModa', 'Newsreader', 'Literata', 'SourceSerif4'};
  static const String _legibleFrom = 'Newsreader';
  static const String _legibleTo = 'AtkinsonHyperlegibleNext';
  static const double _legibleAddLine = 4.0;

  static int _breakpoint(BuildContext context) {
    final w = MediaQuery.sizeOf(context).width;
    return w < 600 ? 0 : w < 1024 ? 1 : w < 1440 ? 2 : 3;
  }

  static FontWeight _weight(double wght) => FontWeight.values[((wght / 100).round() - 1).clamp(0, 8)];

  static TextStyle style(BuildContext context, CineTextRole role, {bool legible = false}) {
    final i = _breakpoint(context);
    final size = role.sizes[i];
    var line = role.lines[i];
    var family = role.family;
    if (legible && family == _legibleFrom) {
      family = _legibleTo;
      line += _legibleAddLine;
    }
    var wght = role.wght;
    if (MediaQuery.boldTextOf(context)) wght = math.min(wght + 120, _wghtMax[family] ?? wght + 120);
    return TextStyle(
      fontFamily: family,
      fontStyle: role.italic ? FontStyle.italic : FontStyle.normal,
      fontSize: size,
      height: line / size,
      letterSpacing: role.trackingEm * size,
      fontWeight: _weight(wght),
      fontVariations: [
        if (_wghtAxis.contains(family)) FontVariation('wght', wght),
        if (_opszAxis.contains(family)) FontVariation('opsz', math.min(size, 96)),
        for (final e in role.axes.entries)
          if (e.key != 'opsz' && e.key != 'wght') FontVariation(e.key, e.value),
      ],
    );
  }

  static TextScaler scaler(BuildContext context, CineTextRole role) => MediaQuery.textScalerOf(context).clamp(maxScaleFactor: role.cap);

  /// 3 × paragraph line height; opsz = min(size, 96).
  static TextStyle dropcap(double paragraphLineHeightPx) {
    final size = 3 * paragraphLineHeightPx;
    return TextStyle(
      fontFamily: 'BodoniModa',
      fontSize: size,
      height: 1,
      letterSpacing: -0.02 * size,
      fontWeight: _weight(800.0),
      fontVariations: [FontVariation('wght', 800.0), FontVariation('opsz', math.min(size, 96))],
    );
  }
}

const Map<HapticEvent, List<HapticStep>> cinematicHaptics = {
  HapticEvent.tapPrimary: [HapticStep(pattern: 'ahap:impress')],
  HapticEvent.tapSecondary: [],
  HapticEvent.toggleOn: [HapticStep(pattern: 'medium')],
  HapticEvent.toggleOff: [HapticStep(pattern: 'light')],
  HapticEvent.select: [HapticStep(pattern: 'selection')],
  HapticEvent.navChange: [HapticStep(pattern: 'rigid')],
  HapticEvent.longpressOpen: [HapticStep(pattern: 'heavy')],
  HapticEvent.sheetDetent: [HapticStep(pattern: 'light')],
  HapticEvent.sheetDismiss: [],
  HapticEvent.refreshArm: [HapticStep(pattern: 'medium')],
  HapticEvent.refreshFire: [],
  HapticEvent.followAdd: [HapticStep(pattern: 'ahap:stamp')],
  HapticEvent.followRemove: [HapticStep(pattern: 'light')],
  HapticEvent.favorite: [HapticStep(pattern: 'light')],
  HapticEvent.bookmarkAdd: [HapticStep(pattern: 'ahap:impress')],
  HapticEvent.downloadStart: [HapticStep(pattern: 'light')],
  HapticEvent.downloadDone: [HapticStep(pattern: 'success')],
  HapticEvent.downloadFail: [HapticStep(pattern: 'error')],
  HapticEvent.deleteConfirm: [HapticStep(pattern: 'warning')],
  HapticEvent.undo: [HapticStep(pattern: 'light')],
  HapticEvent.readerEnter: [HapticStep(pattern: 'ahap:wipe')],
  HapticEvent.pageTurn: [HapticStep(pattern: 'selection')],
  HapticEvent.scrubTick: [HapticStep(pattern: 'selection')],
  HapticEvent.scrubBoundary: [HapticStep(pattern: 'medium')],
  HapticEvent.chapterComplete: [HapticStep(pattern: 'medium'), HapticStep(pattern: 'light', afterMs: 120)],
  HapticEvent.chapterNext: [HapticStep(pattern: 'heavy')],
  HapticEvent.autoscrollToggle: [HapticStep(pattern: 'rigid')],
  HapticEvent.autoscrollStep: [HapticStep(pattern: 'selection')],
  HapticEvent.autoscrollEnd: [HapticStep(pattern: 'heavy')],
  HapticEvent.zoomSnap: [HapticStep(pattern: 'light')],
  HapticEvent.listenToggle: [HapticStep(pattern: 'rigid')],
  HapticEvent.voiceAssign: [HapticStep(pattern: 'ahap:impress')],
  HapticEvent.sleepFade: [HapticStep(pattern: 'soft')],
  HapticEvent.streakExtend: [HapticStep(pattern: 'ahap:ignite')],
  HapticEvent.streakMilestone: [HapticStep(pattern: 'ahap:ignite'), HapticStep(pattern: 'ahap:stamp', afterMs: 520)],
  HapticEvent.recapCountdownEnd: [],
  HapticEvent.annualPage: [HapticStep(pattern: 'selection')],
  HapticEvent.shareExport: [HapticStep(pattern: 'ahap:pressrun')],
  HapticEvent.reactionSend: [HapticStep(pattern: 'ahap:stamp')],
  HapticEvent.recommendSend: [HapticStep(pattern: 'ahap:pass')],
  HapticEvent.gateConfirm: [HapticStep(pattern: 'ahap:stamp')],
  HapticEvent.splashImpress: [HapticStep(pattern: 'ahap:impress')],
  HapticEvent.profileSelect: [HapticStep(pattern: 'heavy')],
  HapticEvent.skinSwitch: [HapticStep(pattern: 'heavy')],
  HapticEvent.readerUnlock: [HapticStep(pattern: 'medium')],
  HapticEvent.success: [HapticStep(pattern: 'success')],
  HapticEvent.error: [HapticStep(pattern: 'error')],
  HapticEvent.navScrub: [],
  HapticEvent.navReselect: [],
  HapticEvent.navPush: [],
  HapticEvent.navPop: [],
  HapticEvent.navRoot: [],
  HapticEvent.stackOpen: [],
  HapticEvent.stackPick: [],
  HapticEvent.detentTick: [],
  HapticEvent.detentMagnet: [],
  HapticEvent.detentLimit: [],
  HapticEvent.pressLift: [],
  HapticEvent.throwCommit: [],
  HapticEvent.motionCatch: [],
  HapticEvent.magnetCapture: [],
  HapticEvent.magnetDrop: [],
  HapticEvent.reorderLift: [],
  HapticEvent.reorderPass: [],
  HapticEvent.reorderDrop: [],
  HapticEvent.sheetPass: [],
  HapticEvent.thresholdCross: [],
  HapticEvent.thresholdBack: [],
  HapticEvent.refreshDone: [],
  HapticEvent.holdRamp: [],
  HapticEvent.holdDone: [],
  HapticEvent.chapterArm: [],
  HapticEvent.chapterSeam: [],
  HapticEvent.zoomLimit: [],
  HapticEvent.panelStep: [],
  HapticEvent.ocrHit: [],
  HapticEvent.autoscrollStart: [],
  HapticEvent.voiceCenter: [],
  HapticEvent.recapReady: [],
  HapticEvent.goalMet: [],
  HapticEvent.shareLift: [],
  HapticEvent.shareFlip: [],
  HapticEvent.reactionBloom: [],
  HapticEvent.reactionCross: [],
  HapticEvent.logoLand: [],
  HapticEvent.logoSettle: [],
  HapticEvent.logoReduced: [],
  HapticEvent.annualPodium: [],
  HapticEvent.annualSummary: [],
  HapticEvent.warning: [],
};

const Map<String, List<AhapEvent>> cinematicAhap = {
  'impress': [AhapEvent(type: 'T', time: 0.0, intensity: 0.9, sharpness: 0.2), AhapEvent(type: 'T', time: 0.045, intensity: 0.3, sharpness: 0.1)],
  'stamp': [AhapEvent(type: 'T', time: 0.0, intensity: 0.5, sharpness: 0.3), AhapEvent(type: 'T', time: 0.07, intensity: 1.0, sharpness: 0.2)],
  'wipe': [AhapEvent(type: 'C', time: 0.0, duration: 0.3, intensity: 0.3, sharpness: 0.15), AhapEvent(type: 'T', time: 0.3, intensity: 0.7, sharpness: 0.25)],
  'ignite': [AhapEvent(type: 'C', time: 0.0, duration: 0.4, intensity: 0.5, sharpness: 0.2), AhapEvent(type: 'T', time: 0.4, intensity: 1.0, sharpness: 0.3)],
  'pressrun': [AhapEvent(type: 'T', time: 0.0, intensity: 0.4, sharpness: 0.3), AhapEvent(type: 'T', time: 0.06, intensity: 0.6, sharpness: 0.3), AhapEvent(type: 'T', time: 0.12, intensity: 0.9, sharpness: 0.25)],
  'pass': [AhapEvent(type: 'T', time: 0.0, intensity: 0.6, sharpness: 0.4), AhapEvent(type: 'T', time: 0.1, intensity: 0.3, sharpness: 0.6)],
};

const Map<String, String> cinematicSoundCues = {
  'tick': 'assets/sounds/cinematic/tick.wav',
  'set': 'assets/sounds/cinematic/set.wav',
  'impress': 'assets/sounds/cinematic/impress.wav',
  'turn': 'assets/sounds/cinematic/turn.wav',
  'wipe': 'assets/sounds/cinematic/wipe.wav',
  'done': 'assets/sounds/cinematic/done.wav',
  'bell': 'assets/sounds/cinematic/bell.wav',
  'pass': 'assets/sounds/cinematic/pass.wav',
  'error': 'assets/sounds/cinematic/error.wav',
  'toggle.on': 'assets/sounds/cinematic/toggle-on.wav',
  'toggle.off': 'assets/sounds/cinematic/toggle-off.wav',
  'sheet': 'assets/sounds/cinematic/sheet.wav',
  'reel': 'assets/sounds/cinematic/reel.wav',
};

const Map<SoundEvent, List<String>> cinematicSoundEvents = {
  SoundEvent.tapPrimary: ['set'],
  SoundEvent.toggleOn: ['toggle.on'],
  SoundEvent.toggleOff: ['toggle.off'],
  SoundEvent.select: ['tick'],
  SoundEvent.navChange: ['tick'],
  SoundEvent.followAdd: ['impress'],
  SoundEvent.favorite: ['tick'],
  SoundEvent.bookmarkAdd: ['set'],
  SoundEvent.downloadDone: ['done'],
  SoundEvent.downloadFail: ['error'],
  SoundEvent.undo: ['tick'],
  SoundEvent.readerEnter: ['wipe'],
  SoundEvent.pageTurn: ['turn'],
  SoundEvent.refreshArm: ['tick'],
  SoundEvent.scrubBoundary: ['tick'],
  SoundEvent.chapterComplete: ['done'],
  SoundEvent.chapterNext: ['turn'],
  SoundEvent.autoscrollToggle: ['tick'],
  SoundEvent.voiceAssign: ['set'],
  SoundEvent.streakExtend: ['bell'],
  SoundEvent.streakMilestone: ['bell'],
  SoundEvent.annualPage: ['turn'],
  SoundEvent.shareExport: ['set'],
  SoundEvent.reactionSend: ['impress'],
  SoundEvent.recommendSend: ['pass'],
  SoundEvent.gateConfirm: ['impress'],
  SoundEvent.skinSwitch: ['impress'],
  SoundEvent.readerUnlock: ['toggle.on'],
  SoundEvent.error: ['error'],
  SoundEvent.sheetOpen: ['sheet'],
  SoundEvent.splashReveal: ['reel'],
  SoundEvent.detentTick: [],
  SoundEvent.sheetPass: [],
  SoundEvent.scrubTick: [],
  SoundEvent.navScrub: [],
  SoundEvent.sheetClose: [],
  SoundEvent.navPush: [],
  SoundEvent.navPop: [],
  SoundEvent.navRoot: [],
  SoundEvent.stackOpen: [],
  SoundEvent.logoLand: [],
  SoundEvent.throwCommit: [],
  SoundEvent.motionCatch: [],
  SoundEvent.magnetCapture: [],
  SoundEvent.recapReady: [],
  SoundEvent.magnetDrop: [],
  SoundEvent.annualPodium: [],
  SoundEvent.holdDone: [],
  SoundEvent.goalMet: [],
  SoundEvent.annualSummary: [],
  SoundEvent.shareFlip: [],
  SoundEvent.logoSettle: [],
};
