// Builds the Open-source licences data (glass 8.25.14, mobile/40 A4). Dart stdlib only. Run from `mobile/`:
//   /srv/manhwamaniacs/dev/flutter/bin/dart run tool/licenses/build_licences.dart
// Writes lib/features/settings/utils/package_versions.g.dart and assets/licenses/art_and_sounds.json; reads everything else.
import 'dart:convert';
import 'dart:io';

void main() {
  final lock = File('pubspec.lock').readAsStringSync();
  final versions = <String, String>{};
  for (final m in RegExp(r'^  ([a-z0-9_]+):\n((?:    .*\n|      .*\n)+)', multiLine: true).allMatches(lock)) {
    final v = RegExp(r'^    version: "([^"]+)"', multiLine: true).firstMatch(m.group(2)!);
    if (v != null) versions[m.group(1)!] = v.group(1)!;
  }
  final names = versions.keys.toList()..sort();
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/licenses/build_licences.dart — do not edit')
    ..writeln()
    ..writeln('/// Each locked package and its version (pubspec.lock), for the Open-source licences sheet.')
    ..writeln('const Map<String, String> kPackageVersions = {');
  for (final n in names) {
    out.writeln("  '$n': '${versions[n]}',");
  }
  out.writeln('};');
  File('lib/features/settings/utils/package_versions.g.dart').writeAsStringSync(out.toString());

  final art = <Map<String, String>>[];
  void add(String name, String text) => art.add({'name': name, 'licence': 'CC0', 'text': text});
  if (Directory('../brand/onboarding/styles').existsSync()) add('Onboarding art', 'Onboarding art © ManhwaManiacs contributors, CC0');
  if (Directory('../brand/demo').existsSync()) add('Demo covers and pages', 'Procedural demo art made for ManhwaManiacs, CC0');
  if (Directory('../design/sounds/glass').existsSync() || Directory('assets/sounds/glass').existsSync()) {
    add('Glass UI sounds', 'Synthesized with sox for ManhwaManiacs, CC0');
  }
  if (File('../backend/media/soundscapes/glass/deep-bed.ogg').existsSync()) {
    add('Deep soundscape layers', 'Synthesized with sox for ManhwaManiacs, CC0');
  }
  final sources = File('../backend/media/soundscapes/glass/SOURCES.md');
  if (sources.existsSync()) {
    List<String> cells(String line) => line.trim().replaceAll(RegExp(r'^\||\|$'), '').split('|').map((c) => c.trim()).toList();
    List<String>? header;
    for (final line in sources.readAsLinesSync()) {
      if (!line.trimLeft().startsWith('|')) {
        header = null;
        continue;
      }
      final c = cells(line);
      if (header == null) {
        if (c.contains('Id') && c.contains('Freesound URL')) header = c;
        continue;
      }
      if (c.every((x) => RegExp(r'^-+$').hasMatch(x))) continue;
      String col(String k) => header!.indexOf(k) < c.length ? c[header.indexOf(k)] : '';
      final url = col('Freesound URL');
      if (!url.startsWith('http') || col('Licence') != 'CC0 1.0') continue;
      add(col('Id'), 'Author: ${col('Author')}\nFreesound URL: $url');
    }
  }
  File('assets/licenses/art_and_sounds.json').writeAsStringSync('${const JsonEncoder.withIndent('  ').convert(art)}\n');
  stdout.writeln('${names.length} package versions, ${art.length} art and sound entries');
}
