#!/usr/bin/env node
// The design generator (stack-decision.md §2.1, cinematic/DESIGN.md §2.8, §15.1, §15.10 S16).
// Reads design/contract.json and every design/tokens/*.json, validates them, and writes:
//   frontend/src/skins/theme.generated.css          shared @property, @theme and @utility block
//   frontend/src/skins/contract.generated.ts        screen ids, route builders, flags, event unions
//   frontend/src/skins/<skin>/tokens.generated.css  [data-skin="<skin>"] custom properties
//   frontend/src/skins/<skin>/tokens.generated.ts   the same values for Motion and scripts
//   mobile/lib/skins/token_types.g.dart             value types both skins' Dart tokens use
//   mobile/lib/skins/contract.g.dart                ScreenId, Routes, SettingsSection, events
//   mobile/lib/skins/<skin>/tokens.g.dart           the ThemeExtension, static consts, CineType
//   mobile/test/skins/generated_contract_test.dart  compile proof (the analyzer skips *.g.dart)
//   mobile/test/skins/generated_glass_test.dart     the same for Glass and both motion enums
// and, through design/build-haptics.mjs, the AHAP assets and motion-name unions of every skin.
// A skin whose tokens carry a `glass` group uses the Glass emitters (lib/emit-glass-*.mjs).
//
//   node design/build.mjs           write the files
//   node design/build.mjs --check   compare in memory, print each differing path, exit 1 on any
//                                   difference or validation error, then run lint-utilities.mjs
//                                   and check-contrast.mjs
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { cssName, twName, dartField, leaves } from "./lib/naming.mjs";
import { hapticErrors } from "./lib/haptics.mjs";
import { emitSkinCss, emitThemeCss, colorLeaves } from "./lib/emit-css.mjs";
import { emitContractTs, emitTokensTs } from "./lib/emit-ts.mjs";
import { emitTokensDart, emitTokenTypesDart, emitContractDart, emitContractTestDart } from "./lib/emit-dart.mjs";
import { emitGlassCss, isGlassTokens } from "./lib/emit-glass-css.mjs";
import { emitGlassTs } from "./lib/emit-glass-ts.mjs";
import { emitGlassDart, emitGlassTestDart } from "./lib/emit-glass-dart.mjs";
import { hapticsOutputs } from "./build-haptics.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const read = (p) => JSON.parse(readFileSync(join(root, p), "utf8"));
const head = (src) => `GENERATED by design/build.mjs from ${src} — do not edit.`;

const contract = read("design/contract.json");
const skins = readdirSync(join(root, "design/tokens")).filter((f) => f.endsWith(".json")).sort()
  .map((f) => ({ id: f.replace(/\.json$/, ""), src: `design/tokens/${f}`, t: read(`design/tokens/${f}`) }));

// ---- validation (both modes) ----
const errors = [];
for (const { id, t } of skins) {
  const ahap = new Set(Object.keys(t.ahap ?? {}));
  for (const e of contract.hapticEvents) {
    if (!(e in (t.haptics ?? {}))) errors.push(`${id}: haptics is missing ${e}`);
    else for (const m of hapticErrors(t.haptics[e], ahap)) errors.push(`${id}: haptics ${e}: ${m}`);
  }
  for (const e of Object.keys(t.haptics ?? {})) if (!contract.hapticEvents.includes(e)) errors.push(`${id}: haptics names unknown event ${e}`);
  for (const e of Object.keys(t.hapticsWeb ?? {})) if (!contract.hapticEvents.includes(e)) errors.push(`${id}: hapticsWeb names unknown event ${e}`);
  for (const e of contract.soundEvents) {
    if (!(e in (t.soundEvents ?? {}))) errors.push(`${id}: soundEvents is missing ${e}`);
    else for (const cue of [t.soundEvents[e]].flat()) if (cue !== null && !(cue in (t.sounds ?? {}))) errors.push(`${id}: soundEvents ${e} names unknown cue ${cue}`);
  }
  for (const e of Object.keys(t.soundEvents ?? {})) if (!contract.soundEvents.includes(e)) errors.push(`${id}: soundEvents names unknown event ${e}`);
  // No key may collide after naming, for any target.
  const keys = [];
  for (const g of Object.keys(t)) {
    if (g.startsWith("_") || g === "runtime" || typeof t[g] !== "object" || Array.isArray(t[g])) continue;
    keys.push(...leaves(t[g], (v) => typeof v !== "object" || v === null || Array.isArray(v) || "value" in v || "bezier" in v || "ms" in v || "font" in v || "kind" in v, g).map(([k]) => k));
  }
  for (const fn of [cssName, twName, dartField]) {
    const seen = new Map();
    for (const k of keys) { const n = fn(k); if (seen.has(n) && seen.get(n) !== k) errors.push(`${id}: ${seen.get(n)} and ${k} both name ${n}`); seen.set(n, k); }
  }
  for (const [k, v] of colorLeaves(t)) if (!/^#[0-9A-Fa-f]{6}$|^rgba\(\d+,\d+,\d+,(0|1|0?\.\d+)\)$/.test(v)) errors.push(`${id}: ${k} is not hex or rgba(): ${v}`);
}

// ---- render ----
const out = new Map();
const cSrc = "design/contract.json";
out.set("frontend/src/skins/theme.generated.css", emitThemeCss(skins, head("design/tokens/*.json"), errors));
out.set("frontend/src/skins/contract.generated.ts", emitContractTs(contract, head(cSrc)));
out.set("mobile/lib/skins/token_types.g.dart", emitTokenTypesDart(head("design/tokens/*.json")));
out.set("mobile/lib/skins/contract.g.dart", emitContractDart(contract, head(cSrc)));
for (const { id, src, t } of skins) {
  const glass = isGlassTokens(t);
  out.set(`frontend/src/skins/${id}/tokens.generated.css`, (glass ? emitGlassCss : emitSkinCss)(id, t, head(src)));
  out.set(`frontend/src/skins/${id}/tokens.generated.ts`, glass ? emitGlassTs(t, head(src)) : emitTokensTs(t, head(src)));
  out.set(`mobile/lib/skins/${id}/tokens.g.dart`, (glass ? emitGlassDart : emitTokensDart)(id, t, head(src)));
}
out.set("mobile/test/skins/generated_contract_test.dart", emitContractTestDart(head(`${cSrc} and design/tokens/cinematic.json`)));
out.set("mobile/test/skins/generated_glass_test.dart", emitGlassTestDart(head("design/tokens/glass.json and design/tokens/cinematic.json")));
for (const [p, content] of hapticsOutputs(skins, head, errors)) out.set(p, content);

if (errors.length) {
  for (const e of errors) console.error(`design: ${e}`);
  process.exit(1);
}

if (check) {
  let differ = 0;
  for (const [p, content] of out) {
    const abs = join(root, p);
    if (!existsSync(abs) || readFileSync(abs, "utf8") !== content) { console.error(`differs: ${p}`); differ++; }
  }
  console.log(differ ? `design: ${differ} of ${out.size} generated files differ; run node design/build.mjs` : `design: ${out.size} generated files match`);
  if (differ) process.exit(1);
  for (const step of ["design/lint-utilities.mjs", "design/check-contrast.mjs"]) {
    const r = spawnSync(process.execPath, [join(root, step)], { stdio: step.includes("contrast") ? ["inherit", "pipe", "inherit"] : "inherit", encoding: "utf8" });
    if (step.includes("contrast")) process.stdout.write(r.status ? r.stdout : r.stdout.split("\n").filter((l) => /^(WARN|check-contrast)/.test(l)).join("\n") + "\n");
    if (r.status !== 0) process.exit(r.status ?? 1);
  }
} else {
  for (const [p, content] of out) {
    const abs = join(root, p);
    mkdirSync(dirname(abs), { recursive: true });
    if (!existsSync(abs) || readFileSync(abs, "utf8") !== content) { writeFileSync(abs, content); console.log(`wrote ${relative(root, abs)}`); }
  }
  console.log(`design: ${out.size} generated files up to date`);
}
