#!/usr/bin/env node
// Writes docs/redesign/proof/shared-00/cinematic-tokens.svg: every colour (with WCAG 2.x contrast
// on #000000), the springs plotted from their generated linear() samples, the duration scale and
// the type roles. Two layouts in one file (wide, and narrow under 600 px) switched by a media
// query. Not part of build.mjs or --check.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { leaves } from "./lib/naming.mjs";
import { colorLeaves, roleLeaves } from "./lib/emit-css.mjs";
import { springCss } from "./lib/spring.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const t = JSON.parse(readFileSync(join(root, "design/tokens/cinematic.json"), "utf8"));
const out = join(root, "docs/redesign/proof/shared-00/cinematic-tokens.svg");
const INK = "#F3F0E8", MUTED = "#9A978F", RULE = "#2B2A27", SPOT = "#F4D03F";
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;");

function rgba(c) {
  const h = /^#([0-9a-f]{6})$/i.exec(c);
  if (h) return [...h[1].match(/../g).map((x) => parseInt(x, 16)), 1];
  return /\(([^)]+)\)/.exec(c)[1].split(",").map(Number);
}
// WCAG 2.x contrast of a colour (composited over black) against #000000.
function contrast(c) {
  const [r, g, b, a] = rgba(c);
  const lin = (v) => { const s = (v * a) / 255; return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4; };
  const L = 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
  return (L + 0.05) / 0.05;
}

function layout(W, cls) {
  const m = W > 600 ? 48 : 16, el = [];
  let y = m;
  const text = (x, yy, s, size = 12, fill = INK, extra = "") => el.push(`<text x="${x}" y="${yy}" font-size="${size}" fill="${fill}" ${extra}>${esc(s)}</text>`);
  const head = (s, short = s) => { s = W > 600 ? s : short; y += 40; text(m, y, s.toUpperCase(), 12, SPOT, 'letter-spacing="0.16em" font-weight="700"'); el.push(`<rect x="${m}" y="${y + 8}" width="${W - 2 * m}" height="1" fill="${RULE}"/>`); y += 28; };
  text(m, y + 28, "Cinematic tokens", W > 600 ? 40 : 28, INK, 'font-family="Georgia, serif" font-style="italic"');
  text(m, y + 52, W > 600 ? "design/tokens/cinematic.json · generated by design/proof-sheet.mjs" : "design/tokens/cinematic.json", 12, MUTED); y += 60;

  head(`Colour · ${colorLeaves(t).length} tokens · contrast on #000000`, `Colour · ${colorLeaves(t).length} · on #000`);
  const cols = Math.max(2, Math.floor((W - 2 * m) / 210)), cw = (W - 2 * m) / cols;
  const rowH = W > 600 ? 64 : 76;
  colorLeaves(t).forEach(([k, v], i) => {
    const x = m + (i % cols) * cw, name = k.slice(6), wrap = W <= 600 && name.length > 17;
    let yy = y + Math.floor(i / cols) * rowH;
    el.push(`<rect x="${x}" y="${yy}" width="48" height="48" fill="${v}" stroke="${RULE}"/>`);
    if (wrap) { text(x + 58, yy + 14, name.slice(0, name.lastIndexOf(".") + 1), 12); yy += 14; }
    text(x + 58, yy + 14, wrap ? name.slice(name.lastIndexOf(".") + 1) : name, 12);
    const [r, g, b, a] = rgba(v), short = `#${[r, g, b].map((n) => n.toString(16).toUpperCase().padStart(2, "0")).join("")} @ ${a}`;
    text(x + 58, yy + 30, W > 600 || a === 1 ? v : short, 11, MUTED, 'font-family="monospace"');
    text(x + 58, yy + 45, `${contrast(v).toFixed(2)}:1`, 11, MUTED, 'font-family="monospace"');
  });
  y += Math.ceil(colorLeaves(t).length / cols) * rowH;

  head("Springs · plotted from the generated linear() · settle time T", "Springs · linear() · settle T");
  const pw = W > 600 ? 360 : W - 2 * m, ph = 140;
  Object.entries(t.spring).forEach(([k, s], i) => {
    const { ms, easing } = springCss(s.ms, s.bounce);
    const pts = easing.slice(7, -1).split(", ").map(Number);
    const x0 = W > 600 ? m + i * (pw + 40) : m, y0 = W > 600 ? y : y + i * (ph + 56);
    el.push(`<rect x="${x0}" y="${y0}" width="${pw}" height="${ph}" fill="none" stroke="${RULE}"/>`);
    el.push(`<polyline fill="none" stroke="${SPOT}" stroke-width="2" points="${pts.map((p, j) => `${(x0 + (j / (pts.length - 1)) * pw).toFixed(1)},${(y0 + ph - p * (ph - 10)).toFixed(1)}`).join(" ")}"/>`);
    text(x0, y0 + ph + 20, W > 600 ? `spring.${k}  {ms ${s.ms}, bounce ${s.bounce}}  →  T ${ms} ms, ${pts.length} samples` : `${k} {${s.ms}, ${s.bounce}} → T ${ms} ms · ${pts.length} pts`, 12);
  });
  y += W > 600 ? ph + 30 : 3 * (ph + 56) - 26;

  const durs = leaves(t.dur, (v) => "value" in v, "dur");
  head(`Durations · ${durs.length} tokens · log scale`, `Durations · ${durs.length} · log scale`);
  const lx = m + (W > 600 ? 220 : 150), bw = W - m - lx - 70, max = Math.log10(26000);
  durs.forEach(([k, v], i) => {
    const yy = y + i * 16;
    text(m, yy + 10, k.slice(4), 11);
    el.push(`<rect x="${lx}" y="${yy + 2}" width="${Math.max(1, (Math.log10(Math.max(v.value, 1)) / max) * bw).toFixed(1)}" height="9" fill="${INK}"/>`);
    text(W - m - 60, yy + 10, `${v.value} ms`, 11, MUTED, 'font-family="monospace"');
  });
  y += durs.length * 16;

  const roles = roleLeaves(t);
  head(`Type roles · ${roles.length} · size/line px per breakpoint (phone · tablet · desktop · wide)`, `Type roles · ${roles.length} · px per breakpoint`);
  roles.forEach(([k, r], i) => {
    const yy = y + i * (W > 600 ? 22 : 40);
    const face = `${t.font[r.font].family}${r.italic ? " Italic" : ""} ${r.wght}${Object.entries(r.axes ?? {}).map(([a, v]) => ` ${a} ${v}`).join("")}`;
    const sizes = r.size ? Object.values(r.size).map(([s, l]) => `${s}/${l}`).join(" · ") + `  ${r.tracking}em  cap ${r.scaleCap}${r.upper ? "  UPPER" : ""}${r.fluid ? "  fluid" : ""}` : r.sizeRule;
    text(m, yy + 12, k.slice(5), 12);
    if (W > 600) { text(m + 150, yy + 12, face, 12, MUTED); text(m + 520, yy + 12, sizes, 12, INK, 'font-family="monospace"'); }
    else { text(m + 110, yy + 12, face, 11, MUTED); text(m, yy + 28, sizes, 11, INK, 'font-family="monospace"'); }
  });
  y += roles.length * (W > 600 ? 22 : 40) + m;
  return { svg: `<g class="${cls}" font-family="system-ui, sans-serif">${el.join("")}</g>`, h: Math.ceil(y) };
}

const wide = layout(1440, "w"), narrow = layout(390, "n");
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="${wide.h}">
<style>svg{background:#000}.n{display:none}@media (max-width:600px){svg{height:${narrow.h}px}.w{display:none}.n{display:inline}}</style>
<rect width="100%" height="100%" fill="#000"/>
${wide.svg}
${narrow.svg}
</svg>
`;
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, svg);
console.log(`wrote ${out.slice(root.length + 1)} (${wide.h} px wide layout, ${narrow.h} px narrow)`);
