// GENERATED by brand/build-glyphs.mjs from design/icons.json and brand/cinematic/glyphs — do not edit.
// Strings only: web/01 imports the named components from "@phosphor-icons/react/ssr".

export const ICON_ROLES = {
  back: { kind: "phosphor", name: "arrow-left", component: "ArrowLeftIcon" },
  close: { kind: "phosphor", name: "x", component: "XIcon" },
  search: { kind: "phosphor", name: "magnifying-glass", component: "MagnifyingGlassIcon" },
  home: { kind: "phosphor", name: "moon-stars", component: "MoonStarsIcon" },
  library: { kind: "phosphor", name: "books", component: "BooksIcon" },
  discover: { kind: "phosphor", name: "compass", component: "CompassIcon" },
  downloads: { kind: "phosphor", name: "download-simple", component: "DownloadSimpleIcon" },
  index: { kind: "phosphor", name: "list-numbers", component: "ListNumbersIcon" },
  updates: { kind: "phosphor", name: "bell-simple", component: "BellSimpleIcon" },
  sources: { kind: "phosphor", name: "globe-simple", component: "GlobeSimpleIcon" },
  collections: { kind: "phosphor", name: "stack-simple", component: "StackSimpleIcon" },
  history: { kind: "phosphor", name: "clock-counter-clockwise", component: "ClockCounterClockwiseIcon" },
  bookmark: { kind: "phosphor", name: "bookmark-simple", component: "BookmarkSimpleIcon" },
  stats: { kind: "phosphor", name: "chart-bar", component: "ChartBarIcon" },
  circle: { kind: "phosphor", name: "users-three", component: "UsersThreeIcon" },
  settings: { kind: "phosphor", name: "gear-six", component: "GearSixIcon" },
  status: { kind: "phosphor", name: "pulse", component: "PulseIcon" },
  picks: { kind: "phosphor", name: "sparkle", component: "SparkleIcon" },
  "dialogue-search": { kind: "glyph", name: "bubble-search" },
  "reader-settings": { kind: "phosphor", name: "sliders-horizontal", component: "SlidersHorizontalIcon" },
  type: { kind: "phosphor", name: "text-aa", component: "TextAaIcon" },
  contents: { kind: "phosphor", name: "list-numbers", component: "ListNumbersIcon" },
  listen: { kind: "phosphor", name: "headphones", component: "HeadphonesIcon" },
  play: { kind: "phosphor", name: "play", component: "PlayIcon" },
  pause: { kind: "phosphor", name: "pause", component: "PauseIcon" },
  "chapter-previous": { kind: "phosphor", name: "skip-back", component: "SkipBackIcon" },
  "chapter-next": { kind: "phosphor", name: "skip-forward", component: "SkipForwardIcon" },
  download: { kind: "phosphor", name: "cloud-arrow-down", component: "CloudArrowDownIcon" },
  downloaded: { kind: "phosphor", name: "check-square", component: "CheckSquareIcon" },
  pin: { kind: "phosphor", name: "push-pin", component: "PushPinIcon" },
  favourite: { kind: "phosphor", name: "star", component: "StarIcon" },
  follow: { kind: "phosphor", name: "plus", component: "PlusIcon" },
  following: { kind: "phosphor", name: "check", component: "CheckIcon" },
  notify: { kind: "phosphor", name: "bell-ringing", component: "BellRingingIcon" },
  share: { kind: "phosphor", name: "export", component: "ExportIcon" },
  recommend: { kind: "phosphor", name: "paper-plane-tilt", component: "PaperPlaneTiltIcon" },
  filter: { kind: "phosphor", name: "funnel-simple", component: "FunnelSimpleIcon" },
  sort: { kind: "phosphor", name: "arrows-down-up", component: "ArrowsDownUpIcon" },
  "view-grid": { kind: "phosphor", name: "squares-four", component: "SquaresFourIcon" },
  "view-list": { kind: "phosphor", name: "rows", component: "RowsIcon" },
  select: { kind: "phosphor", name: "check-square-offset", component: "CheckSquareOffsetIcon" },
  delete: { kind: "phosphor", name: "trash-simple", component: "TrashSimpleIcon" },
  edit: { kind: "phosphor", name: "pencil-simple-line", component: "PencilSimpleLineIcon" },
  overflow: { kind: "phosphor", name: "dots-three", component: "DotsThreeIcon" },
  "fullscreen-enter": { kind: "phosphor", name: "corners-out", component: "CornersOutIcon" },
  "fullscreen-exit": { kind: "phosphor", name: "corners-in", component: "CornersInIcon" },
  "zoom-in": { kind: "phosphor", name: "magnifying-glass-plus", component: "MagnifyingGlassPlusIcon" },
  "zoom-out": { kind: "phosphor", name: "magnifying-glass-minus", component: "MagnifyingGlassMinusIcon" },
  brightness: { kind: "phosphor", name: "sun-dim", component: "SunDimIcon" },
  warmth: { kind: "phosphor", name: "thermometer-simple", component: "ThermometerSimpleIcon" },
  offline: { kind: "phosphor", name: "wifi-slash", component: "WifiSlashIcon" },
  refresh: { kind: "phosphor", name: "arrow-clockwise", component: "ArrowClockwiseIcon" },
  external: { kind: "phosphor", name: "arrow-square-out", component: "ArrowSquareOutIcon" },
  soundscape: { kind: "phosphor", name: "waveform", component: "WaveformIcon" },
  "auto-scroll": { kind: "glyph", name: "strip-scroll" },
  "strip-mode": { kind: "glyph", name: "strip-scroll" },
  "guided-view": { kind: "glyph", name: "panel-focus" },
  flame: { kind: "phosphor", name: "flame", component: "FlameIcon" },
  "streak-short": { kind: "glyph", name: "flame-1" },
  "streak-long": { kind: "glyph", name: "flame-3" },
  "age-gate": { kind: "glyph", name: "certificate-18" },
  "voice-cast": { kind: "glyph", name: "voice-31" },
  annual: { kind: "glyph", name: "annual" },
  highlighter: { kind: "glyph", name: "highlighter" },
  "brand-mark": { kind: "glyph", name: "mm-mark" },
} as const;

export type IconRole = keyof typeof ICON_ROLES;

export const ICON_RULES = {
  phosphorWeights: [
    "light",
    "regular",
    "fill"
  ],
  glyphWeights: [
    "light",
    "regular",
    "fill"
  ],
  rules: {
    default: "light",
    smallAtOrBelow: 20,
    small: "regular",
    active: "fill"
  },
  sizes: {
    caption: 16,
    button: 20,
    bar: 24,
    notice: 32
  },
  hit: {
    coarse: 44,
    android: 48,
    fine: 32
  }
} as const;
