// Phosphor glyphs the You hub, the admin settings and System status need (codepoints from brand/phosphor/codepoints.json).
import 'package:flutter/widgets.dart';
import 'package:manhwamaniacs/skins/glass/primitives/glyphs.dart';

abstract final class YouGlyphs {
  static const deviceMobile = Glyph(regular: IconData(0xe1e0, fontFamily: 'PhosphorRegular'), fill: IconData(0xe1e0, fontFamily: 'PhosphorFill'), bold: IconData(0xe1e0, fontFamily: 'PhosphorBold'), light: IconData(0xe1e0, fontFamily: 'PhosphorLight'));
  static const browser = Glyph(regular: IconData(0xe0f4, fontFamily: 'PhosphorRegular'), fill: IconData(0xe0f4, fontFamily: 'PhosphorFill'), bold: IconData(0xe0f4, fontFamily: 'PhosphorBold'), light: IconData(0xe0f4, fontFamily: 'PhosphorLight'));
  static const question = Glyph(regular: IconData(0xe3e8, fontFamily: 'PhosphorRegular'), fill: IconData(0xe3e8, fontFamily: 'PhosphorFill'), bold: IconData(0xe3e8, fontFamily: 'PhosphorBold'), light: IconData(0xe3e8, fontFamily: 'PhosphorLight'));
  static const arrowsClockwise = Glyph(regular: IconData(0xe094, fontFamily: 'PhosphorRegular'), fill: IconData(0xe094, fontFamily: 'PhosphorFill'), bold: IconData(0xe094, fontFamily: 'PhosphorBold'), light: IconData(0xe094, fontFamily: 'PhosphorLight'));
  static const shield = Glyph(regular: IconData(0xe40a, fontFamily: 'PhosphorRegular'), fill: IconData(0xe40a, fontFamily: 'PhosphorFill'), bold: IconData(0xe40a, fontFamily: 'PhosphorBold'), light: IconData(0xe40a, fontFamily: 'PhosphorLight'));
  static const flame = Glyph(regular: IconData(0xe624, fontFamily: 'PhosphorRegular'), fill: IconData(0xe624, fontFamily: 'PhosphorFill'), bold: IconData(0xe624, fontFamily: 'PhosphorBold'), light: IconData(0xe624, fontFamily: 'PhosphorLight'));
  static const checkCircle = Glyph(regular: IconData(0xe184, fontFamily: 'PhosphorRegular'), fill: IconData(0xe184, fontFamily: 'PhosphorFill'), bold: IconData(0xe184, fontFamily: 'PhosphorBold'), light: IconData(0xe184, fontFamily: 'PhosphorLight'));
  static const bellSimple = Glyph(regular: IconData(0xe0d0, fontFamily: 'PhosphorRegular'), fill: IconData(0xe0d0, fontFamily: 'PhosphorFill'), bold: IconData(0xe0d0, fontFamily: 'PhosphorBold'), light: IconData(0xe0d0, fontFamily: 'PhosphorLight'));
  static const clockCounterClockwise = Glyph(regular: IconData(0xe1a0, fontFamily: 'PhosphorRegular'), fill: IconData(0xe1a0, fontFamily: 'PhosphorFill'), bold: IconData(0xe1a0, fontFamily: 'PhosphorBold'), light: IconData(0xe1a0, fontFamily: 'PhosphorLight'));
  static const bookmarkSimple = Glyph(regular: IconData(0xe0ea, fontFamily: 'PhosphorRegular'), fill: IconData(0xe0ea, fontFamily: 'PhosphorFill'), bold: IconData(0xe0ea, fontFamily: 'PhosphorBold'), light: IconData(0xe0ea, fontFamily: 'PhosphorLight'));
  static const downloadSimple = Glyph(regular: IconData(0xe20c, fontFamily: 'PhosphorRegular'), fill: IconData(0xe20c, fontFamily: 'PhosphorFill'), bold: IconData(0xe20c, fontFamily: 'PhosphorBold'), light: IconData(0xe20c, fontFamily: 'PhosphorLight'));
  static const stack = Glyph(regular: IconData(0xe466, fontFamily: 'PhosphorRegular'), fill: IconData(0xe466, fontFamily: 'PhosphorFill'), bold: IconData(0xe466, fontFamily: 'PhosphorBold'), light: IconData(0xe466, fontFamily: 'PhosphorLight'));
  static const chatText = Glyph(regular: IconData(0xe17a, fontFamily: 'PhosphorRegular'), fill: IconData(0xe17a, fontFamily: 'PhosphorFill'), bold: IconData(0xe17a, fontFamily: 'PhosphorBold'), light: IconData(0xe17a, fontFamily: 'PhosphorLight'));
  static const books = Glyph(regular: IconData(0xe758, fontFamily: 'PhosphorRegular'), fill: IconData(0xe758, fontFamily: 'PhosphorFill'), bold: IconData(0xe758, fontFamily: 'PhosphorBold'), light: IconData(0xe758, fontFamily: 'PhosphorLight'));
  static const signOut = Glyph(regular: IconData(0xe42a, fontFamily: 'PhosphorRegular'), fill: IconData(0xe42a, fontFamily: 'PhosphorFill'), bold: IconData(0xe42a, fontFamily: 'PhosphorBold'), light: IconData(0xe42a, fontFamily: 'PhosphorLight'));
  static const userSwitch = Glyph(regular: IconData(0xe756, fontFamily: 'PhosphorRegular'), fill: IconData(0xe756, fontFamily: 'PhosphorFill'), bold: IconData(0xe756, fontFamily: 'PhosphorBold'), light: IconData(0xe756, fontFamily: 'PhosphorLight'));
  static const copy = Glyph(regular: IconData(0xe1ca, fontFamily: 'PhosphorRegular'), fill: IconData(0xe1ca, fontFamily: 'PhosphorFill'), bold: IconData(0xe1ca, fontFamily: 'PhosphorBold'), light: IconData(0xe1ca, fontFamily: 'PhosphorLight'));
  static const dotsThree = Glyph(regular: IconData(0xe1fe, fontFamily: 'PhosphorRegular'), fill: IconData(0xe1fe, fontFamily: 'PhosphorFill'), bold: IconData(0xe1fe, fontFamily: 'PhosphorBold'), light: IconData(0xe1fe, fontFamily: 'PhosphorLight'));
  static const wifiSlash = Glyph(regular: IconData(0xe4f2, fontFamily: 'PhosphorRegular'), fill: IconData(0xe4f2, fontFamily: 'PhosphorFill'), bold: IconData(0xe4f2, fontFamily: 'PhosphorBold'), light: IconData(0xe4f2, fontFamily: 'PhosphorLight'));
  static const sparkle = Glyph(regular: IconData(0xe6a2, fontFamily: 'PhosphorRegular'), fill: IconData(0xe6a2, fontFamily: 'PhosphorFill'), bold: IconData(0xe6a2, fontFamily: 'PhosphorBold'), light: IconData(0xe6a2, fontFamily: 'PhosphorLight'));
  static const usersThree = Glyph(regular: IconData(0xe68e, fontFamily: 'PhosphorRegular'), fill: IconData(0xe68e, fontFamily: 'PhosphorFill'), bold: IconData(0xe68e, fontFamily: 'PhosphorBold'), light: IconData(0xe68e, fontFamily: 'PhosphorLight'));
  static const pulse = Glyph(regular: IconData(0xe000, fontFamily: 'PhosphorRegular'), fill: IconData(0xe000, fontFamily: 'PhosphorFill'), bold: IconData(0xe000, fontFamily: 'PhosphorBold'), light: IconData(0xe000, fontFamily: 'PhosphorLight'));
  static const cloudArrowUp = Glyph(regular: IconData(0xe1ae, fontFamily: 'PhosphorRegular'), fill: IconData(0xe1ae, fontFamily: 'PhosphorFill'), bold: IconData(0xe1ae, fontFamily: 'PhosphorBold'), light: IconData(0xe1ae, fontFamily: 'PhosphorLight'));
  static const tray = Glyph(regular: IconData(0xe4aa, fontFamily: 'PhosphorRegular'), fill: IconData(0xe4aa, fontFamily: 'PhosphorFill'), bold: IconData(0xe4aa, fontFamily: 'PhosphorBold'), light: IconData(0xe4aa, fontFamily: 'PhosphorLight'));
  static const info = Glyph(regular: IconData(0xe2ce, fontFamily: 'PhosphorRegular'), fill: IconData(0xe2ce, fontFamily: 'PhosphorFill'), bold: IconData(0xe2ce, fontFamily: 'PhosphorBold'), light: IconData(0xe2ce, fontFamily: 'PhosphorLight'));
  static const warning = Glyph(regular: IconData(0xe4e0, fontFamily: 'PhosphorRegular'), fill: IconData(0xe4e0, fontFamily: 'PhosphorFill'), bold: IconData(0xe4e0, fontFamily: 'PhosphorBold'), light: IconData(0xe4e0, fontFamily: 'PhosphorLight'));
  static const warningCircle = Glyph(regular: IconData(0xe4e2, fontFamily: 'PhosphorRegular'), fill: IconData(0xe4e2, fontFamily: 'PhosphorFill'), bold: IconData(0xe4e2, fontFamily: 'PhosphorBold'), light: IconData(0xe4e2, fontFamily: 'PhosphorLight'));
}
