// GENERATED by design/build.mjs from design/contract.json and design/tokens/cinematic.json — do not edit.

import 'package:flutter/painting.dart';
import 'package:flutter/physics.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:manhwamaniacs/skins/cinematic/tokens.g.dart';
import 'package:manhwamaniacs/skins/contract.g.dart';

void main() {
  test('screen ids', () {
    expect(ScreenId.values.length, 35);
    expect(ScreenId.indexHub.id, 'index');
    expect(ScreenId.indexHub.path, '/more');
  });

  test('route builders encode like the web', () {
    expect(Routes.feature('mangadex', 'a/b c%'), '/sources/mangadex/series/a%2Fb%20c%25');
    expect(Routes.reader('s1', 'x!y', 'é'), '/reader/s1/x!y/%C3%A9');
    expect(Routes.recap('s1', 'k', {'to': '12'}), '/recap/s1/k?to=12');
    expect(Routes.library({'q': 'solo leveling', 'fav': 1}), '/library?q=solo+leveling&fav=1');
    expect(Routes.discover({'q': 'a~b*c é'}), '/search?q=a%7Eb*c+%C3%A9');
    expect(Routes.settings(), '/settings');
    expect(Routes.settings(SettingsSection.readingManga), '/settings/reading-manga');
  });

  test('event vocabularies', () {
    expect(HapticEvent.values.length, 90);
    expect(SoundEvent.values.length, 52);
    expect(HapticEvent.tapPrimary.id, 'tap.primary');
  });

  test('colours', () {
    expect(CineColors.spot, const Color(0xFFF4D03F));
    expect(cinematicTokens.colorSpotWash, const Color(0x29F4D03F));
  });

  test('springs map through ms x 1.2', () {
    final release = CineSprings.release.description;
    expect(release.stiffness, closeTo(155.42, 0.01));
    expect(release.damping, closeTo(24.93, 0.01));
    final sheet = CineSprings.sheet.description;
    final expected = SpringDescription.withDurationAndBounce(
      duration: const Duration(milliseconds: 576),
    );
    expect(sheet.stiffness, expected.stiffness);
    expect(sheet.damping, expected.damping);
  });

  test('haptics and sounds cover every event', () {
    final complete = cinematicHaptics[HapticEvent.chapterComplete]!;
    expect(complete.length, 2);
    expect(complete[1].afterMs, 120);
    for (final e in HapticEvent.values) {
      expect(cinematicHaptics.containsKey(e), isTrue, reason: e.id);
    }
    for (final e in SoundEvent.values) {
      expect(cinematicSoundEvents.containsKey(e), isTrue, reason: e.id);
    }
  });
}
