// GENERATED by design/build.mjs from design/tokens/glass.json and design/tokens/cinematic.json — do not edit.

import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:manhwamaniacs/skins/cinematic/motion_names.g.dart' as cine;
import 'package:manhwamaniacs/skins/contract.g.dart';
import 'package:manhwamaniacs/skins/glass/motion_names.g.dart' as glass;
import 'package:manhwamaniacs/skins/glass/tokens.g.dart';

void main() {
  test('colours', () {
    expect(GlassColors.iris600, const Color(0xFF7563F2));
    expect(glassTokens.colorLabel2, const Color(0xA3EBEBF5));
  });

  test('physical springs: withDurationAndBounce at ms x 1.0', () {
    final page = GlassSprings.page.description;
    expect(page.stiffness, closeTo(146.0, 0.05));
    expect(page.damping, closeTo(24.17, 0.01));
    expect(GlassSprings.track.description.stiffness, closeTo(1754.6, 0.1));
  });

  test('layout, snap and focus', () {
    expect(glassTokens.glassSnap, [36, 57, 97]);
    expect(glassTokens.layoutTouchMin, 44);
    expect(glassTokens.layoutTouchMinAndroid, 48);
    expect(glassTokens.borderFocusRing.width, 2);
    expect(glassTokens.legible, isFalse);
  });

  test('motion names', () {
    expect(glass.MotionName.values.length, 116);
    expect(glass.MotionName.throwMove.label, 'THROW');
    expect(cine.MotionName.values.length, 38);
  });

  test('haptics and sounds cover every event', () {
    for (final e in HapticEvent.values) {
      expect(glassHaptics.containsKey(e), isTrue, reason: e.id);
    }
    for (final e in SoundEvent.values) {
      expect(glassSoundEvents.containsKey(e), isTrue, reason: e.id);
    }
    expect(glassSoundEvents[SoundEvent.navPush]!.length, 4);
    expect(glassHaptics[HapticEvent.navRoot]!.single.maxRepeats, 4);
  });
}
