// GENERATED by brand/build-glyphs.mjs from design/icons.json and brand/{cinematic,glass}/glyphs — do not edit.
import 'package:flutter_test/flutter_test.dart';
import 'package:manhwamaniacs/skins/cinematic/icons/cine_glyphs.g.dart';
import 'package:manhwamaniacs/skins/cinematic/icons/icon_roles.g.dart';
import 'package:manhwamaniacs/skins/glass/icons/glass_glyphs.g.dart';
import 'package:manhwamaniacs/skins/glass/icons/icon_roles.g.dart';
import 'package:manhwamaniacs/skins/glass/icons/phosphor.g.dart' as glass;

void main() {
  test('every Cinematic role has all three weights', () {
    expect(cineIcons.keys, unorderedEquals(CineIconRole.values));
    for (final role in CineIconRole.values) {
      expect(cineIcons[role]!.keys, unorderedEquals(CineIconWeight.values), reason: role.name);
    }
  });

  test('every Glass role has all six weights', () {
    expect(glassIcons.keys, unorderedEquals(GlassIconRole.values));
    for (final role in GlassIconRole.values) {
      expect(glassIcons[role]!.keys, unorderedEquals(GlassIconWeight.values), reason: role.name);
    }
  });

  test('font families', () {
    expect(CineGlyphs.mmMarkFill.fontFamily, 'CineGlyphs');
    expect(GlassGlyphs.mmMarkFill.fontFamily, 'GlassGlyphs');
    expect(glass.PhosphorRegular.caretLeft.fontFamily, 'PhosphorRegular');
    expect(glass.PhosphorDuotone.houseSimpleSecondary.fontFamily, 'PhosphorDuotone');
  });

  test('every Glass role whose duotone exists has a secondary', () {
    const expected = <GlassIconRole>[
      GlassIconRole.back,
      GlassIconRole.backDepth,
      GlassIconRole.close,
      GlassIconRole.search,
      GlassIconRole.home,
      GlassIconRole.library,
      GlassIconRole.updates,
      GlassIconRole.sources,
      GlassIconRole.bookmark,
      GlassIconRole.stats,
      GlassIconRole.circle,
      GlassIconRole.settings,
      GlassIconRole.status,
      GlassIconRole.picks,
      GlassIconRole.dialogueSearch,
      GlassIconRole.readerSettings,
      GlassIconRole.type,
      GlassIconRole.contents,
      GlassIconRole.listen,
      GlassIconRole.play,
      GlassIconRole.pause,
      GlassIconRole.chapterPrevious,
      GlassIconRole.chapterNext,
      GlassIconRole.download,
      GlassIconRole.downloaded,
      GlassIconRole.pin,
      GlassIconRole.favourite,
      GlassIconRole.follow,
      GlassIconRole.following,
      GlassIconRole.notify,
      GlassIconRole.share,
      GlassIconRole.recommend,
      GlassIconRole.filter,
      GlassIconRole.sort,
      GlassIconRole.select,
      GlassIconRole.delete,
      GlassIconRole.edit,
      GlassIconRole.overflow,
      GlassIconRole.brightness,
      GlassIconRole.warmth,
      GlassIconRole.offline,
      GlassIconRole.refresh,
      GlassIconRole.external,
      GlassIconRole.soundscape,
      GlassIconRole.autoScroll,
      GlassIconRole.stripMode,
      GlassIconRole.guidedView,
      GlassIconRole.flame,
      GlassIconRole.ageGate,
      GlassIconRole.voiceCast,
      GlassIconRole.brandMark,
      GlassIconRole.aiUnavailable,
    ];
    expect(glassDuotoneSecondary.keys, unorderedEquals(expected));
  });
}
