// GENERATED by brand/glass/export.mjs — do not edit
// ignore_for_file: type=lint
import 'dart:ui';

abstract final class GlassMarkGeometry {
  static const Rect column = Rect.fromLTRB(240, 192, 784, 832);
  static const double stroke = 88;
  static const double barStroke = 64;
  static const List<Offset> topM = [Offset(284, 436), Offset(284, 236), Offset(512, 386), Offset(740, 236), Offset(740, 436)];
  static const List<Offset> bottomM = [Offset(284, 788), Offset(284, 588), Offset(512, 738), Offset(740, 588), Offset(740, 788)];
  static Path bar() => Path()..moveTo(272, 512)..quadraticBezierTo(512, 530, 752, 512);
  static const Color frost = Color(0xFFF5F7FA);
  static const Color iris400 = Color(0xFFA99BFF);
}
