// Writes every Glass SVG master and renders every PNG / generated file. Deterministic: no timestamps.
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import * as M from "./mark.mjs";
import { svgToPng, toOpaquePng, resize } from "../lib/render.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../..");
const outputs = [];
function put(rel, data, size) {
  const p = join(root, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, data);
  if (size) outputs.push({ path: rel, width: size[0], height: size[1] });
}
const svgFile = (name, s) => writeFileSync(join(here, name), s);
const S = (n) => readFileSync(join(here, n), "utf8");
const png = (n, w = 1024) => svgToPng(S(n), { width: w });

async function writeMasters() {
  svgFile("field.svg", M.fieldSvg());
  for (const s of M.SLABS) svgFile(`${s.id}.svg`, M.slabLayerSvg(s.id));
  svgFile("icon.svg", M.iconSvg());
  svgFile("icon-dark.svg", M.iconDarkSvg());
  svgFile("icon-tinted.svg", M.iconTintedSvg());
  svgFile("icon-foreground.svg", M.iconForegroundSvg());
  svgFile("icon-monochrome.svg", M.iconMonochromeSvg());
  svgFile("neutral-mark.svg", M.neutralMarkSvg());
  svgFile("column-small.svg", M.columnSmallSvg());
  svgFile("wordmark-stacked.svg", (await M.wordmarkStacked()).svg);
  svgFile("wordmark-stacked-flat.svg", await M.wordmarkStackedFlat());
  svgFile("wordmark-line.svg", await M.wordmarkLine());
  svgFile("favicon.svg", M.faviconSvg());
  svgFile("droplets.svg", M.dropletsSvg());
}

const f = (n) => (Number.isInteger(n) ? String(n) : String(n));
function writeCode() {
  const g = M.G, hdr = "// GENERATED by brand/glass/export.mjs — do not edit\n";
  const pts = (a) => "[" + a.map((p) => `[${p[0]}, ${p[1]}]`).join(", ") + "]";
  const c = g.capsule;
  put("frontend/src/skins/glass/mark.generated.ts", hdr +
    `export const GLASS_MARK = { viewBox: "${g.viewBox}", stroke: ${g.stroke}, topM: ${pts(g.topM)}, bottomM: ${pts(g.bottomM)}, ` +
    `bar: { d: "${g.bar.d}", stroke: ${g.bar.stroke} }, capsule: { x: ${c.x}, y: ${c.y}, width: ${c.width}, height: ${c.height}, radius: ${c.radius} }, ` +
    `frost: "${g.frost}", iris400: "${g.iris400}" } as const;\n`);
  const offs = (a) => "[" + a.map((p) => `Offset(${p[0]}, ${p[1]})`).join(", ") + "]";
  const hex = (h) => "0xFF" + h.slice(1).toUpperCase();
  put("mobile/lib/skins/glass/brand_mark.g.dart", hdr +
    `// ignore_for_file: type=lint\nimport 'dart:ui';\n\nabstract final class GlassMarkGeometry {\n` +
    `  static const Rect column = Rect.fromLTRB(${g.column.x0}, ${g.column.y0}, ${g.column.x1}, ${g.column.y1});\n` +
    `  static const double stroke = ${g.stroke};\n  static const double barStroke = ${g.bar.stroke};\n` +
    `  static const List<Offset> topM = ${offs(g.topM)};\n  static const List<Offset> bottomM = ${offs(g.bottomM)};\n` +
    `  static Path bar() => Path()..moveTo(${g.bar.p0.join(", ")})..quadraticBezierTo(${g.bar.c.join(", ")}, ${g.bar.p1.join(", ")});\n` +
    `  static const Color frost = Color(${hex(g.frost)});\n  static const Color iris400 = Color(${hex(g.iris400)});\n}\n`);
}

async function main() {
  await writeMasters();
  const E = "brand/glass/export";
  const field = await toOpaquePng(png("field.svg"));
  put(`${E}/field-1024.png`, field, [1024, 1024]);
  const icon = await toOpaquePng(png("icon.svg"));
  const dark = png("icon-dark.svg");
  const tinted = await toOpaquePng(png("icon-tinted.svg"));
  put(`${E}/icon-ios-1024.png`, icon, [1024, 1024]);
  put(`${E}/icon-ios-dark-1024.png`, dark, [1024, 1024]);
  put(`${E}/icon-ios-tinted-1024.png`, tinted, [1024, 1024]);
  const fg = png("icon-foreground.svg"), mono = png("icon-monochrome.svg");
  put(`${E}/android-foreground-1024.png`, fg, [1024, 1024]);
  put(`${E}/android-monochrome-1024.png`, mono, [1024, 1024]);

  const X = "mobile/ios/Runner/Assets.xcassets/AppIcon-Glass.appiconset";
  put(`${X}/AppIcon-Glass-1024.png`, icon, [1024, 1024]);
  put(`${X}/AppIcon-Glass-1024-dark.png`, dark, [1024, 1024]);
  put(`${X}/AppIcon-Glass-1024-tinted.png`, tinted, [1024, 1024]);
  put(`${X}/Contents.json`, JSON.stringify({
    images: [
      { filename: "AppIcon-Glass-1024.png", idiom: "universal", platform: "ios", size: "1024x1024" },
      { appearances: [{ appearance: "luminosity", value: "dark" }], filename: "AppIcon-Glass-1024-dark.png", idiom: "universal", platform: "ios", size: "1024x1024" },
      { appearances: [{ appearance: "luminosity", value: "tinted" }], filename: "AppIcon-Glass-1024-tinted.png", idiom: "universal", platform: "ios", size: "1024x1024" },
    ],
    info: { author: "xcode", version: 1 },
  }, null, 2) + "\n");

  const I = "mobile/ios/Runner/AppIcon-Glass.icon";
  put(`${I}/icon.json`, JSON.stringify(iconComposer(), null, 2) + "\n");
  put(`${I}/Assets/field.png`, field, [1024, 1024]);
  for (const id of ["bottom-m", "gutter-bar", "top-m"]) put(`${I}/Assets/${id}.svg`, S(`${id}.svg`));

  const R = "mobile/android/app/src/main/res";
  for (const [d, px] of [["mdpi", 108], ["hdpi", 162], ["xhdpi", 216], ["xxhdpi", 324], ["xxxhdpi", 432]]) {
    put(`${R}/drawable-${d}/ic_launcher_glass_foreground.png`, await resize(fg, px), [px, px]);
    put(`${R}/drawable-${d}/ic_launcher_glass_background.png`, await resize(field, px), [px, px]);
    put(`${R}/drawable-${d}/ic_launcher_glass_monochrome.png`, await resize(mono, px), [px, px]);
  }
  for (const [d, px] of [["mdpi", 48], ["hdpi", 72], ["xhdpi", 96], ["xxhdpi", 144], ["xxxhdpi", 192]])
    put(`${R}/mipmap-${d}/ic_launcher_glass.png`, await resize(icon, px), [px, px]);
  put(`${R}/mipmap-anydpi-v26/ic_launcher_glass.xml`,
    `<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n` +
    `    <background android:drawable="@drawable/ic_launcher_glass_background" />\n    <foreground android:drawable="@drawable/ic_launcher_glass_foreground" />\n` +
    `    <monochrome android:drawable="@drawable/ic_launcher_glass_monochrome" />\n</adaptive-icon>\n`);

  put("frontend/public/favicon-glass.svg", S("favicon.svg").replace(/>\s+</g, "><"));
  put("frontend/public/glass/droplets.webp",
    await sharp(png("droplets.svg", 480)).webp({ lossless: true, effort: 6 }).toBuffer(), [480, 480]);
  writeCode();
  const ex = M.extents();
  console.log(`column x ${ex.column.x0}..${ex.column.x1}, y ${ex.column.y0}..${ex.column.y1}; bar bow ${ex.bow}; capsule x ${ex.capsule.x}..${ex.capsule.x + ex.capsule.width}, y ${ex.capsule.y}..${ex.capsule.y + ex.capsule.height}, radius ${ex.capsule.radius}`);
  console.log(`leading ${(352 / M.LOWER.size).toFixed(3)} (baselines 352 apart, size ${M.LOWER.size})`);
  outputs.sort((a, b) => (a.path < b.path ? -1 : 1));
  put(`${E}/manifest.json`, JSON.stringify({ outputs }, null, 1) + "\n");
  console.log(`exported ${outputs.length} files`);
}

function iconComposer() {
  const frost = { solid: "extended-srgb:0.96078,0.96863,0.98039,1.00000" };
  const pos = { scale: 1, "translation-in-points": [0, 0] };
  const grp = (name, tr, tint, extra = {}) => ({
    name, lighting: "individual", specular: true, shadow: { kind: "neutral", opacity: 0.5 }, translucency: { enabled: true, value: tr },
    layers: [{ name, "image-name": `${name}.svg`, glass: true, ...extra,
      "fill-specializations": [{ value: frost }, { appearance: "tinted", value: { solid: `extended-gray:1.00000,${tint}` } }], position: pos }],
  });
  return {
    fill: { "linear-gradient": ["extended-srgb:0.03922,0.05882,0.12157,1.00000", "extended-srgb:0.00000,0.00000,0.00000,1.00000"] },
    groups: [
      grp("top-m", 0.5, "1.00000"),
      grp("gutter-bar", 0.9, "0.55000", { opacity: 0.35 }),
      grp("bottom-m", 0.5, "0.80000"),
      { name: "field", specular: false, shadow: { kind: "none", opacity: 0 }, translucency: { enabled: false, value: 0 },
        layers: [{ name: "field", "image-name": "field.png", glass: false, "opacity-specializations": [{ value: 1 }, { appearance: "tinted", value: 0 }], position: pos }] },
    ],
    "supported-platforms": { squares: "shared" },
  };
}
await main();
